"""Rebuild solvated_fragment.pdb with real backbone geometry.

The previous version placed six alanines along a helical path without
constructing the backbone, so C(i)-N(i+1) came out at 4.4-5.2 A instead of
1.33 A -- no peptide bonds at all -- and residues 4 and 5 interpenetrated
(O4-CB5 = 0.63 A). Anything asserting about inferred bonds on that file was
asserting about nonsense.

Built here by natural extension reference frame (NeRF) placement from ideal
internal coordinates, which is how a peptide is actually constructed: each atom
is positioned from the previous three by a bond length, a bond angle and a
torsion.
"""

from __future__ import annotations

import numpy as np

# Ideal geometry (Engh & Huber-ish values used by every builder).
B_N_CA, B_CA_C, B_C_N = 1.458, 1.525, 1.329
B_C_O, B_CA_CB = 1.231, 1.521
A_N_CA_C, A_CA_C_N, A_C_N_CA = 111.2, 116.2, 121.7
A_CA_C_O, A_N_CA_CB = 120.8, 110.5
PHI, PSI, OMEGA = -57.0, -47.0, 180.0  # right-handed alpha helix


def place(a, b, c, length, angle_deg, torsion_deg):
    """Position a fourth atom from three, by length/angle/torsion (NeRF)."""
    angle, torsion = np.radians(angle_deg), np.radians(torsion_deg)
    bc = c - b
    bc /= np.linalg.norm(bc)
    n = np.cross(b - a, bc)
    n /= np.linalg.norm(n)
    m = np.cross(n, bc)
    d = np.array(
        [
            -length * np.cos(angle),
            length * np.sin(angle) * np.cos(torsion),
            length * np.sin(angle) * np.sin(torsion),
        ]
    )
    return c + d[0] * bc + d[1] * m + d[2] * n


def build_polyalanine(n_res: int):
    """Return a list of (res_id, atom_name, element, xyz) for a helix."""
    atoms = []
    # Seed the first residue explicitly; the rest follow by torsion.
    n0 = np.array([0.0, 0.0, 0.0])
    ca0 = np.array([B_N_CA, 0.0, 0.0])
    angle = np.radians(A_N_CA_C)
    c0 = ca0 + B_CA_C * np.array([-np.cos(angle), np.sin(angle), 0.0])

    prev_n, prev_ca, prev_c = n0, ca0, c0
    for res in range(1, n_res + 1):
        if res == 1:
            n, ca, c = n0, ca0, c0
        else:
            # C(i-1) -> N(i) -> CA(i) -> C(i)
            n = place(prev_n, prev_ca, prev_c, B_C_N, A_CA_C_N, PSI)
            ca = place(prev_ca, prev_c, n, B_N_CA, A_C_N_CA, OMEGA)
            c = place(prev_c, n, ca, B_CA_C, A_N_CA_C, PHI)
        # O sits trans to the next N across the C, i.e. psi + 180.
        o = place(n, ca, c, B_C_O, A_CA_C_O, PSI + 180.0)
        cb = place(c, n, ca, B_CA_CB, A_N_CA_CB, 122.5)
        atoms += [
            (res, "N", "N", n),
            (res, "CA", "C", ca),
            (res, "C", "C", c),
            (res, "O", "O", o),
            (res, "CB", "C", cb),
        ]
        prev_n, prev_ca, prev_c = n, ca, c
    return atoms


def main(path: str):
    atoms = build_polyalanine(6)
    coords = np.array([a[3] for a in atoms])

    # A zinc ion and eight waters, all clear of the peptide and of each other.
    centre = coords.mean(axis=0)
    extent = float(np.abs(coords - centre).max())
    zn = centre + np.array([extent + 6.0, 0.0, 0.0])
    waters = [
        centre
        + np.array(
            [
                (extent + 9.0 + 3.2 * (k % 3)),
                3.4 * ((k // 3) - 1),
                3.4 * (1 if k % 2 else -1),
            ]
        )
        for k in range(8)
    ]

    lines = [
        "REMARK   Generated by make_fragment.py -- ideal alpha-helical "
        "hexa-alanine, one Zn, eight waters"
    ]
    serial = 0

    def atom_line(kind, serial, name, resn, chain, resi, xyz, element):
        return (
            f"{kind:<6}{serial:>5} {name:^4}{'':1}{resn:>3} {chain}{resi:>4}"
            f"{'':4}{xyz[0]:>8.3f}{xyz[1]:>8.3f}{xyz[2]:>8.3f}"
            f"{1.00:>6.2f}{20.00:>6.2f}{'':10}{element:>2}"
        )

    for res, name, element, xyz in atoms:
        serial += 1
        lines.append(atom_line("ATOM", serial, name, "ALA", "A", res, xyz, element))
    serial += 1
    lines.append(atom_line("HETATM", serial, "ZN", "ZN", "A", 20, zn, "ZN"))
    for k, w in enumerate(waters):
        serial += 1
        lines.append(atom_line("HETATM", serial, "O", "HOH", "A", 100 + k, w, "O"))
    lines += ["TER", "END", ""]
    open(path, "w").write("\n".join(lines))

    # --- checks: the file is only useful if the geometry is right -------------
    names = [a[1] for a in atoms]
    res_ids = [a[0] for a in atoms]
    bad = []
    for r in range(1, 6):
        ci = next(i for i, (rr, nn) in enumerate(zip(res_ids, names)) if rr == r and nn == "C")
        nj = next(i for i, (rr, nn) in enumerate(zip(res_ids, names)) if rr == r + 1 and nn == "N")
        d = float(np.linalg.norm(coords[ci] - coords[nj]))
        if not (1.2 < d < 1.5):
            bad.append(f"C({r})-N({r + 1}) = {d:.2f}")
        print(f"  C({r})-N({r + 1}) = {d:.3f}")
    allc = np.vstack([coords, zn[None, :], np.array(waters)])
    d = np.linalg.norm(allc[:, None, :] - allc[None, :, :], axis=-1)
    np.fill_diagonal(d, 9e9)
    print(f"  closest contact overall = {d.min():.3f} A")
    if d.min() < 1.0:
        bad.append(f"atoms interpenetrate: {d.min():.2f} A")
    print("  OK" if not bad else "  BAD: " + "; ".join(bad))
    return 0 if not bad else 1


if __name__ == "__main__":
    import sys

    raise SystemExit(main(sys.argv[1]))
