"""Tests for the bundle-relocation step of the installer builder.

Console scripts generated by micromamba/pip carry the absolute build-time
prefix in their shebang; the shipped ``.app``/AppImage lives somewhere else
entirely. These tests move the tree after rewriting and execute the scripts
from their new location.
"""

from __future__ import annotations

import importlib.util
import os
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent

_spec = importlib.util.spec_from_file_location(
    "build_installer", REPO_ROOT / "build_tools" / "build_installer.py"
)
build_installer = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(build_installer)

BODY = "import sys\nprint('ran', sys.argv[1:])\n"


def _make_prefix(root: Path) -> Path:
    """Create a fake env prefix with a python and two console scripts in bin."""
    prefix = root / "build" / "dist" / "osx"
    bin_dir = prefix / "bin"
    bin_dir.mkdir(parents=True)
    (bin_dir / "python3.12").symlink_to(sys.executable)

    py = bin_dir / "python3.12"
    # Plain shebang, as pip writes when the path is short enough.
    plain = bin_dir / "plain_script"
    plain.write_text(f"#!{py}\n{BODY}")
    # setuptools' long-shebang workaround, used once the path exceeds 127 chars.
    sh_exec = bin_dir / "sh_exec_script"
    sh_exec.write_text(f"#!/bin/sh\n'''exec' \"{py}\" \"$0\" \"$@\" #'''\n{BODY}")
    for f in (plain, sh_exec):
        f.chmod(0o755)
    return prefix


@pytest.mark.skipif(sys.platform.startswith("win"), reason="POSIX shebangs only")
@pytest.mark.parametrize("name", ["plain_script", "sh_exec_script"])
def test_scripts_run_after_the_bundle_moves(tmp_path: Path, name: str) -> None:
    prefix = _make_prefix(tmp_path)
    assert build_installer.relocate_scripts(prefix / "bin", prefix) == 2

    moved = tmp_path / "Applications" / "ChiSurf.app" / "Contents"
    moved.parent.mkdir(parents=True)
    (prefix).rename(moved)

    out = subprocess.run([moved / "bin" / name, "arg"], capture_output=True, text=True)
    assert out.returncode == 0, out.stderr
    assert out.stdout.strip() == "ran ['arg']"


@pytest.mark.skipif(sys.platform.startswith("win"), reason="POSIX shebangs only")
def test_scripts_run_when_found_through_path(tmp_path: Path) -> None:
    prefix = _make_prefix(tmp_path)
    build_installer.relocate_scripts(prefix / "bin", prefix)

    env = dict(os.environ, PATH=f"{prefix / 'bin'}{os.pathsep}{os.environ['PATH']}")
    out = subprocess.run(["plain_script"], capture_output=True, text=True, env=env)
    assert out.returncode == 0, out.stderr
    assert out.stdout.strip() == "ran []"


@pytest.mark.skipif(sys.platform.startswith("win"), reason="POSIX shebangs only")
def test_foreign_and_system_shebangs_are_left_alone(tmp_path: Path, capsys) -> None:
    prefix = _make_prefix(tmp_path)
    bin_dir = prefix / "bin"

    # A system shebang: not ours to touch.
    activate = bin_dir / "activate"
    activate.write_text("#!/bin/sh\necho hi\n")
    # A non-Python interpreter inside the prefix: the sh-exec wrapper would not
    # be valid in its language, so it must be reported rather than mangled.
    perl_script = bin_dir / "perl_script"
    perl_script.write_text(f"#!{bin_dir / 'perl'}\nprint 1;\n")

    assert build_installer.relocate_scripts(bin_dir, prefix) == 2
    assert activate.read_text() == "#!/bin/sh\necho hi\n"
    assert perl_script.read_text().startswith(f"#!{bin_dir / 'perl'}")
    assert "perl_script" in capsys.readouterr().out


@pytest.mark.skipif(sys.platform.startswith("win"), reason="POSIX shebangs only")
def test_rewriting_is_idempotent(tmp_path: Path) -> None:
    prefix = _make_prefix(tmp_path)
    build_installer.relocate_scripts(prefix / "bin", prefix)
    before = (prefix / "bin" / "plain_script").read_bytes()

    assert build_installer.relocate_scripts(prefix / "bin", prefix) == 0
    assert (prefix / "bin" / "plain_script").read_bytes() == before
