"""Simulated smFRET bursts with exchange on a chosen timescale.

**This is a code test, never a physics test.** A simulator built from the same
assumptions as the model it validates will pass whatever error the two share; what
it can prove is that the implementation computes what it claims to, and nothing
about whether that claim describes a molecule. PRD-71 says so, and it is repeated
here because a generator this convenient is exactly the kind that quietly becomes
the only evidence.

Within that limit it earns its keep, because it is **generated by a different route
than it is fitted**. The model computes the occupation-time law ``P(f | T, K)`` in
closed form and the micro-time pattern from moments; this module samples an explicit
continuous-time Markov path per burst, assigns each photon to whichever state was
occupied when it arrived, and draws its micro time as an instrument-response sample
plus an exponential delay. Nothing is shared but the physics being asserted, so a
mistake in the propagator, in the nested background sum, or in the wrapped moments
shows up as a disagreement rather than cancelling.

The point of the exercise is the **timescale**. Exchange is only visible when it is
comparable to how long a molecule spends in the focus, and the three regimes look
entirely different:

* far slower than a burst — indistinguishable from two static populations;
* comparable — bursts caught mid-exchange fill the space between the states and pull
  the cloud off the static line, which is the signal;
* far faster — one averaged population, narrower than either state.

:data:`REGIMES` names them in units of *transitions per burst*, so a test can ask
for "one transition per burst" without knowing the burst duration.
"""

from __future__ import annotations

import pathlib
from dataclasses import dataclass, field
from typing import Any

import numpy as np

from chisurf.core.fluorescence.mfd.patterns import (
    FretState,
    Optics,
    noncentral_chi_distance_distribution,
    red_probability,
)

__all__ = [
    "REGIMES",
    "SimulatedMfd",
    "SimulationParameters",
    "rate_matrix_for",
    "simulate_mfd",
]

#: Exchange regimes, in **transitions per burst**. Named rather than given as rates
#: because a rate only means something next to a burst duration: 500 s⁻¹ is slow
#: exchange for a 10 ms transit and fast exchange for a 0.1 ms one.
REGIMES: dict[str, float] = {
    "static": 0.0,
    "slow": 0.05,
    "intermediate": 1.5,
    "fast": 60.0,
}

#: Routing channels of the simulated detectors, matching the conventional
#: two-colour confocal setup that :func:`~chisurf.core.fluorescence.burst.photons.default_streams`
#: describes, so a simulated folder reads with the same channel definition as a
#: measured one.
GREEN_CHANNEL = 0
RED_CHANNEL = 1

#: Perpendicular counterparts, used when ``polarized`` is on. The pairs (0, 8) and
#: (1, 9) are the conventional two-colour two-polarization layout that
#: :func:`~chisurf.core.fluorescence.burst.photons.default_streams` already assumes,
#: so a polarization-resolved simulated folder still reads as green/red for the FRET
#: axis while additionally supporting the anisotropy one.
GREEN_PERP_CHANNEL = 8
RED_PERP_CHANNEL = 9


@dataclass
class SimulationParameters:
    """Everything a simulated measurement declares about itself.

    Attributes
    ----------
    states : list of FretState
        The conformational states, by mean donor–acceptor distance.
    populations : sequence of float, optional
        Equilibrium populations; equal when omitted. For an exchanging system these
        are what the rate matrix must reproduce, so they are *derived* from the
        rates rather than imposed — see :func:`rate_matrix_for`.
    rate_matrix : numpy.ndarray, optional
        Exchange rates in Hz, ``K[target, source]``. ``None`` is a static mixture.
    optics : Optics
        Förster radius, lifetimes, linker width and the correction factors.
    donor_only : float
        Fraction of molecules with no active acceptor.
    n_bursts : int
        Number of bursts to generate.
    mean_photons : float
        Mean signal photons per burst. Drawn from a log-normal so the burst-size
        distribution has the long tail a real one does — a Poisson budget would
        make every burst the same size and hide the shot-noise structure the fit
        is built on.
    photon_spread : float
        Log-normal shape parameter of the burst-size distribution.
    mean_duration : float
        Mean burst duration, seconds.
    background_rates : tuple of float
        ``(green, red)`` background count rates, s⁻¹.
    scatter_fraction : float
        Fraction of the background that is scattered excitation light rather than
        dark counts. Non-zero is what lets a simulated folder's instrument response
        be estimated from its own non-burst photons, as a real one's is.
    irf_centre, irf_width : float
        Instrument response position and standard deviation, nanoseconds.
    period : float
        Laser period — one TAC window, nanoseconds.
    n_micro_time_channels : int
        Micro-time channels per period.
    macro_time_resolution : float
        Macro-time tick, seconds.
    inter_burst : float
        Mean dark time between bursts, seconds. Real acquisitions are mostly empty,
        and those photons are where the response and the background rate come from.
    polarized : bool
        Split every detector into a parallel and a perpendicular channel, with the
        split drawn from each photon's own emission anisotropy. Needed for the
        ``H[r, ⟨t⟩]`` axis; the FRET axis is unaffected, because the two
        polarizations of a colour still read as that colour.
    seed : int
        Random seed.
    """

    states: list[FretState] = field(
        default_factory=lambda: [
            FretState(distance=40.0, name="closed"),
            FretState(distance=70.0, name="open"),
        ]
    )
    populations: tuple[float, ...] | None = None
    rate_matrix: np.ndarray | None = None
    optics: Optics = field(
        default_factory=lambda: Optics(
            r0=52.0, tau_d0=4.0, tau_a=3.0, sigma=6.0, alpha=0.02, delta=0.0, gamma=1.0
        )
    )
    donor_only: float = 0.15
    n_bursts: int = 3000
    mean_photons: float = 90.0
    photon_spread: float = 0.55
    mean_duration: float = 2.0e-3
    background_rates: tuple[float, float] = (600.0, 350.0)
    scatter_fraction: float = 0.35
    irf_centre: float = 1.2
    irf_width: float = 0.09
    period: float = 13.6
    n_micro_time_channels: int = 4096
    macro_time_resolution: float = 1.35e-8
    inter_burst: float = 6.0e-3
    polarized: bool = False
    seed: int = 20260803

    @property
    def dt(self) -> float:
        """Return the micro-time channel width, nanoseconds."""
        return self.period / float(self.n_micro_time_channels)

    def equilibrium(self) -> np.ndarray:
        """Return the equilibrium populations actually simulated.

        With a rate matrix, these come *from the rates* rather than from
        ``populations`` — a scheme cannot have an equilibrium its own rates
        contradict, and quietly using both is how a simulated truth stops being
        one.

        Returns
        -------
        numpy.ndarray
        """
        from chisurf.core.fluorescence.kinetics import equilibrium_populations

        if self.rate_matrix is not None:
            return equilibrium_populations(np.asarray(self.rate_matrix, dtype=float))
        if self.populations is None:
            return np.full(len(self.states), 1.0 / len(self.states))
        values = np.clip(np.asarray(self.populations, dtype=float), 0.0, None)
        return values / values.sum()


def rate_matrix_for(
    regime: str | float,
    *,
    mean_duration: float,
    populations=(0.5, 0.5),
) -> np.ndarray | None:
    """Return the two-state rate matrix that gives a regime, at a burst duration.

    Exchange is only meaningful relative to the observation window, so the regime is
    named in transitions per burst and converted here. The two rates are then fixed
    by that total and by the equilibrium populations, which is the only way to vary
    the timescale without also moving the populations.

    Parameters
    ----------
    regime : str or float
        A key of :data:`REGIMES`, or a number of transitions per burst.
    mean_duration : float
        Mean burst duration, seconds.
    populations : sequence of float
        Equilibrium populations of the two states.

    Returns
    -------
    numpy.ndarray or None
        ``K[target, source]`` in Hz, or ``None`` for the static regime.
    """
    per_burst = REGIMES[regime] if isinstance(regime, str) else float(regime)
    if per_burst <= 0.0:
        return None
    weights = np.clip(np.asarray(populations, dtype=float), 1e-9, None)
    weights = weights / weights.sum()
    # Transitions per burst counts *both* directions, and the process spends
    # population[i] of its time in state i, so the observed transition rate is
    # 2 * p0 * k01 for a two-state system at equilibrium.
    total = per_burst / float(mean_duration)
    k01 = total / (2.0 * weights[0])
    k10 = k01 * weights[0] / weights[1]
    return np.array([[0.0, k10], [k01, 0.0]])


@dataclass
class SimulatedMfd:
    """A simulated measurement, and the truth it was generated from.

    Attributes
    ----------
    macro_times : numpy.ndarray
        Photon macro times, in macro-time ticks.
    micro_times : numpy.ndarray
        Photon micro times, in TAC channels.
    channels : numpy.ndarray
        Photon routing channels.
    start_stop : list of tuple
        ``(first, last)`` photon index per burst, **inclusive** — the convention the
        current ``.bur`` writer uses.
    truth : dict
        Every declared input, so a recovered value can be compared with what
        generated it.
    parameters : SimulationParameters
        The parameters used.
    """

    macro_times: np.ndarray
    micro_times: np.ndarray
    channels: np.ndarray
    start_stop: list[tuple[int, int]]
    truth: dict[str, Any]
    parameters: SimulationParameters

    def true_responses(self) -> dict:
        """Return the instrument responses and background rates as *declared*.

        Estimating the response from a measurement's own non-burst photons is what
        a real folder has to do, and it is contaminated: bursts below the search
        threshold are not detected, so their fluorescence lands in the "non-burst"
        stream and drags the response late. That is a property of the *experiment*,
        not of this simulator — the same contamination is visible on real data — so
        it is worth being able to separate.

        Handing the declared response to a fit isolates whatever is under test from
        that contamination. Comparing it against the estimated one *measures* the
        contamination instead of arguing about it.

        Returns
        -------
        dict
            Detector name to
            :class:`~chisurf.core.fluorescence.mfd.patterns.ChannelResponse`.
        """
        from chisurf.core.fluorescence.mfd.patterns import ChannelResponse

        parameters = self.parameters
        channels = np.arange(parameters.n_micro_time_channels, dtype=float)
        time = channels * parameters.dt
        # The response is periodic like everything else in the window, so a centre
        # near either end must wrap rather than be clipped.
        offset = np.mod(time - parameters.irf_centre + 0.5 * parameters.period,
                        parameters.period) - 0.5 * parameters.period
        irf = np.exp(-0.5 * (offset / parameters.irf_width) ** 2)
        return {
            name: ChannelResponse(
                irf=irf.copy(), dt=parameters.dt, background_rate=float(rate)
            )
            for name, rate in zip(
                ("green", "red"), parameters.background_rates
            )
        }

    def tttr(self):
        """Return the photon stream as a ``tttrlib.TTTR`` object.

        Returns
        -------
        tttrlib.TTTR
        """
        import tttrlib

        out = tttrlib.TTTR()
        out.append_events(
            np.asarray(self.macro_times, dtype=np.uint64),
            np.asarray(self.micro_times, dtype=np.uint16),
            np.asarray(self.channels, dtype=np.int8),
            np.zeros(self.channels.size, dtype=np.int8),
            shift_macro_time=False,
        )
        header = out.header
        header.set_macro_time_resolution(float(self.parameters.macro_time_resolution))
        header.set_micro_time_resolution(float(self.parameters.dt) * 1e-9)
        header.set_number_of_micro_time_channels(
            int(self.parameters.n_micro_time_channels)
        )
        out.set_header(header)
        return out

    def write_folder(self, directory: pathlib.Path | str, stem: str = "sim") -> pathlib.Path:
        """Write a real burst-analysis folder, readable by the ordinary path.

        Produces the photon file, the ``bi4_bur`` tables and the analysis manifest,
        so a simulated measurement goes through the *same* reader, the same channel
        verification and the same response estimation as a measured one. A simulator
        that bypassed all of that would test the model and none of the machinery
        around it.

        Parameters
        ----------
        directory : path-like
            Where to create the folder.
        stem : str
            Base name of the measurement file.

        Returns
        -------
        pathlib.Path
            The analysis folder to hand to the reader.
        """
        from chisurf.core.fio.fluorescence.burst import write_bur_file
        from chisurf.core.fio.fluorescence.burst_manifest import (
            describe_tttr_source,
            write_analysis_manifest,
        )

        directory = pathlib.Path(directory)
        directory.mkdir(parents=True, exist_ok=True)
        tttr = self.tttr()
        source = directory / f"{stem}.ht3"
        tttr.write(str(source))

        analysis = directory / "burstwise_All 0.1000#15"
        bur_dir = analysis / "bi4_bur"
        bur_dir.mkdir(parents=True, exist_ok=True)

        # In polarized mode the colour detectors must cover *both* polarizations,
        # or half the photons vanish from the FRET axis without anything
        # complaining — the per-detector columns would simply be half as large and
        # the proximity ratio would still look reasonable. The polarization
        # detectors are written alongside them, so one folder serves both axes.
        if self.parameters.polarized:
            detectors = {
                "green": {
                    "chs": [GREEN_CHANNEL, GREEN_PERP_CHANNEL],
                    "micro_time_ranges": [],
                },
                "red": {
                    "chs": [RED_CHANNEL, RED_PERP_CHANNEL],
                    "micro_time_ranges": [],
                },
                "green_par": {"chs": [GREEN_CHANNEL], "micro_time_ranges": []},
                "green_perp": {"chs": [GREEN_PERP_CHANNEL], "micro_time_ranges": []},
            }
        else:
            detectors = {
                "green": {"chs": [GREEN_CHANNEL], "micro_time_ranges": []},
                "red": {"chs": [RED_CHANNEL], "micro_time_ranges": []},
            }
        windows = {"prompt": (0, self.parameters.n_micro_time_channels)}
        write_bur_file(
            bur_dir / f"{stem}.bur",
            self.start_stop,
            source.name,
            tttr,
            windows,
            detectors,
        )
        write_analysis_manifest(
            analysis,
            [describe_tttr_source(source, tttr, settings={"detectors": detectors})],
            settings={"detectors": detectors, "simulated": True},
        )
        return analysis


def _sample_micro_times(rng, n, lifetimes, parameters) -> np.ndarray:
    """Draw micro-time channels for photons with given emission lifetimes.

    Generated from first principles — an instrument-response sample plus an
    exponential delay, wrapped onto the period — rather than from the model's own
    pattern machinery, so agreement between the two means something.
    """
    if n == 0:
        return np.zeros(0, dtype=np.uint16)
    response = rng.normal(parameters.irf_centre, parameters.irf_width, size=n)
    delay = rng.exponential(np.asarray(lifetimes, dtype=float))
    arrival = np.mod(response + delay, parameters.period)
    channel = np.floor(arrival / parameters.dt).astype(np.int64)
    return np.clip(channel, 0, parameters.n_micro_time_channels - 1).astype(np.uint16)


def _state_path(rng, rate_matrix, populations, duration):
    """Return the switch times and states of one continuous-time Markov path."""
    n_states = populations.size
    state = int(rng.choice(n_states, p=populations))
    times = [0.0]
    states = [state]
    if rate_matrix is None:
        return np.asarray(times), np.asarray(states)
    exit_rates = rate_matrix.sum(axis=0)
    elapsed = 0.0
    while True:
        rate = float(exit_rates[state])
        if rate <= 0.0:
            break
        elapsed += float(rng.exponential(1.0 / rate))
        if elapsed >= duration:
            break
        column = rate_matrix[:, state] / rate
        state = int(rng.choice(n_states, p=column))
        times.append(elapsed)
        states.append(state)
    return np.asarray(times), np.asarray(states)


def simulate_mfd(parameters: SimulationParameters | None = None) -> SimulatedMfd:
    """Generate a simulated smFRET measurement with exchange during the bursts.

    Parameters
    ----------
    parameters : SimulationParameters, optional
        Declared inputs; defaults are a two-state system with no exchange.

    Returns
    -------
    SimulatedMfd
    """
    parameters = parameters or SimulationParameters()
    rng = np.random.default_rng(parameters.seed)
    optics = parameters.optics
    populations = parameters.equilibrium()
    rate_matrix = (
        None if parameters.rate_matrix is None
        else np.asarray(parameters.rate_matrix, dtype=float)
    )

    # Per state, the distance distribution to draw from, and the acceptor
    # probability of a photon *given transfer has been decided* — the corrections
    # are applied per photon rather than per state, so leakage and direct
    # excitation act where they physically do.
    distributions = [
        noncentral_chi_distance_distribution(s.distance, optics.sigma, n_points=201)
        for s in parameters.states
    ]

    macro_all: list[np.ndarray] = []
    micro_all: list[np.ndarray] = []
    channel_all: list[np.ndarray] = []
    start_stop: list[tuple[int, int]] = []
    written = 0
    clock = 0.0
    tick = parameters.macro_time_resolution
    bg_green, bg_red = parameters.background_rates

    def _background(span_seconds, t0):
        """Return time-ordered background photons over a span: dark plus scatter.

        Ordered because the background *rate* is later recovered from inter-photon
        times: photons emitted out of order have negative gaps, and a stream that
        merely gets sorted afterwards has the wrong ones. Getting this wrong does
        not fail — it produces a plausible background rate that is simply not the
        one that was simulated.
        """
        pieces = []
        emitters = (
            ((bg_green / 2.0, GREEN_CHANNEL), (bg_green / 2.0, GREEN_PERP_CHANNEL),
             (bg_red / 2.0, RED_CHANNEL), (bg_red / 2.0, RED_PERP_CHANNEL))
            if parameters.polarized
            else ((bg_green, GREEN_CHANNEL), (bg_red, RED_CHANNEL))
        )
        for rate, channel in emitters:
            n = int(rng.poisson(rate * span_seconds))
            if n == 0:
                continue
            times = t0 + rng.uniform(0.0, span_seconds, size=n)
            n_scatter = int(rng.binomial(n, parameters.scatter_fraction))
            micro = np.empty(n, dtype=np.uint16)
            # Scatter has the response's own timing; dark counts have none at all.
            micro[:n_scatter] = _sample_micro_times(
                rng, n_scatter, np.full(n_scatter, 1e-9), parameters
            )
            micro[n_scatter:] = rng.integers(
                0, parameters.n_micro_time_channels, size=n - n_scatter
            ).astype(np.uint16)
            pieces.append((times, micro, np.full(n, channel, dtype=np.int8)))
        if not pieces:
            return np.zeros(0), np.zeros(0, np.uint16), np.zeros(0, np.int8)
        times = np.concatenate([p[0] for p in pieces])
        order = np.argsort(times, kind="stable")
        return (
            times[order],
            np.concatenate([p[1] for p in pieces])[order],
            np.concatenate([p[2] for p in pieces])[order],
        )

    n_donor_only = int(rng.binomial(parameters.n_bursts, parameters.donor_only))
    is_donor_only = np.zeros(parameters.n_bursts, dtype=bool)
    is_donor_only[:n_donor_only] = True
    rng.shuffle(is_donor_only)

    for burst in range(parameters.n_bursts):
        # The dark stretch before this burst, over the gap actually drawn — using
        # the mean instead would overlap the burst that follows it.
        gap = float(rng.exponential(parameters.inter_burst))
        dark = _background(gap, clock)
        clock += gap

        duration = float(
            rng.lognormal(np.log(parameters.mean_duration) - 0.125, 0.5)
        )
        n_signal = int(
            rng.lognormal(
                np.log(parameters.mean_photons) - 0.5 * parameters.photon_spread**2,
                parameters.photon_spread,
            )
        )
        n_signal = max(n_signal, 1)

        arrival = np.sort(rng.uniform(0.0, duration, size=n_signal))
        if is_donor_only[burst]:
            efficiency = np.zeros(n_signal)
            lifetime = np.full(n_signal, optics.tau_d0)
        else:
            switch_times, switch_states = _state_path(
                rng, rate_matrix, populations, duration
            )
            per_photon_state = switch_states[
                np.searchsorted(switch_times, arrival, side="right") - 1
            ]
            efficiency = np.empty(n_signal)
            lifetime = np.empty(n_signal)
            for index in range(len(parameters.states)):
                mask = per_photon_state == index
                count = int(mask.sum())
                if count == 0:
                    continue
                weights, distances = distributions[index]
                drawn = rng.choice(distances[0], size=count, p=weights[0])
                efficiency[mask] = 1.0 / (1.0 + (drawn / optics.r0) ** 6)
                lifetime[mask] = optics.tau_d0 * (1.0 - efficiency[mask])

        # Which channel each signal photon lands in, correction factors included.
        transferred = rng.random(n_signal) < efficiency
        to_red = transferred.copy()
        # Leakage moves donor photons into the acceptor channel; direct excitation
        # adds acceptor photons that never involved the donor at all.
        donor_photons = ~transferred
        leaks = rng.random(n_signal) < optics.alpha
        to_red |= donor_photons & leaks
        direct = rng.random(n_signal) < (
            optics.delta / (1.0 + optics.delta) if optics.delta > 0 else 0.0
        )
        to_red |= direct

        micro = np.empty(n_signal, dtype=np.uint16)
        # The rotational correlation time each photon's emitter had, for the
        # polarization split below.
        if is_donor_only[burst] or rate_matrix is None and len(parameters.states) == 1:
            rho_photon = np.full(n_signal, float(parameters.states[0].rho))
        elif is_donor_only[burst]:
            rho_photon = np.full(n_signal, float(parameters.states[0].rho))
        else:
            rho_photon = np.empty(n_signal)
            for index, state in enumerate(parameters.states):
                mask = per_photon_state == index
                if mask.any():
                    rho_photon[mask] = float(state.rho)
        donor_like = ~transferred
        micro[donor_like] = _sample_micro_times(
            rng, int(donor_like.sum()), lifetime[donor_like], parameters
        )
        # A sensitized acceptor photon waits for the transfer *and* for the
        # acceptor to emit, so its delay is the sum of two exponentials.
        n_transfer = int(transferred.sum())
        if n_transfer:
            micro[transferred] = _sample_micro_times(
                rng,
                n_transfer,
                lifetime[transferred] + optics.tau_a,
                parameters,
            )
        channel = np.where(to_red, RED_CHANNEL, GREEN_CHANNEL).astype(np.int8)
        if parameters.polarized:
            # Each photon's emission anisotropy at *its own* micro time, which is
            # what makes the anisotropy axis correlate with the lifetime axis —
            # drawing a single steady-state value per burst would produce the right
            # marginal and no correlation at all.
            emitted = micro.astype(float) * parameters.dt - parameters.irf_centre
            r_t = optics.r0_anisotropy * np.exp(
                -np.clip(emitted, 0.0, None) / np.maximum(rho_photon, 1e-9)
            )
            # P(parallel) from the Schaffer/Eggeling amplitudes the analysis inverts.
            vv = 1.0 + (2.0 - 3.0 * optics.l1) * r_t
            vh = (1.0 - (1.0 - 3.0 * optics.l2) * r_t) / max(optics.g_factor, 1e-9)
            parallel = rng.random(n_signal) < vv / (vv + vh)
            channel = np.where(
                to_red,
                np.where(parallel, RED_CHANNEL, RED_PERP_CHANNEL),
                np.where(parallel, GREEN_CHANNEL, GREEN_PERP_CHANNEL),
            ).astype(np.int8)

        in_burst = _background(duration, clock)
        times = [clock + arrival, in_burst[0]]
        micros = [micro, in_burst[1]]
        channels = [channel, in_burst[2]]

        burst_times = np.concatenate(times)
        order = np.argsort(burst_times, kind="stable")
        burst_times = burst_times[order]
        burst_micro = np.concatenate(micros)[order]
        burst_channel = np.concatenate(channels)[order]

        macro_all.append(dark[0])
        micro_all.append(dark[1])
        channel_all.append(dark[2])
        written += dark[0].size

        start_stop.append((written, written + burst_times.size - 1))
        macro_all.append(burst_times)
        micro_all.append(burst_micro)
        channel_all.append(burst_channel)
        written += burst_times.size
        clock += duration

    macro_seconds = np.concatenate(macro_all)
    macro_ticks = np.round(macro_seconds / tick).astype(np.int64)
    # Each block was emitted in order and the blocks are in order, so this only
    # repairs ties created by rounding to the macro-time tick — never a real
    # reordering, which would corrupt the inter-photon times the background rate
    # is estimated from.
    if np.any(np.diff(macro_ticks) < 0):
        raise RuntimeError("simulated photons are out of time order")

    truth = {
        "regime_rate_matrix": None if rate_matrix is None else rate_matrix.tolist(),
        "populations": populations.tolist(),
        "distances": [s.distance for s in parameters.states],
        "donor_only": float(parameters.donor_only),
        "tau_d0": float(optics.tau_d0),
        "tau_a": float(optics.tau_a),
        "alpha": float(optics.alpha),
        "delta": float(optics.delta),
        "gamma": float(optics.gamma),
        "sigma": float(optics.sigma),
        "r0": float(optics.r0),
        "efficiencies": [
            float(
                np.sum(
                    distributions[i][0]
                    * (1.0 / (1.0 + (distributions[i][1] / optics.r0) ** 6))
                )
            )
            for i in range(len(parameters.states))
        ],
        "acceptor_probabilities": [
            float(
                red_probability(
                    float(
                        np.sum(
                            distributions[i][0]
                            * (1.0 / (1.0 + (distributions[i][1] / optics.r0) ** 6))
                        )
                    ),
                    optics,
                )
            )
            for i in range(len(parameters.states))
        ],
        "background_rates": list(parameters.background_rates),
        "n_bursts": int(parameters.n_bursts),
        "n_photons": int(macro_ticks.size),
        "mean_duration": float(parameters.mean_duration),
    }
    return SimulatedMfd(
        macro_times=macro_ticks,
        micro_times=np.concatenate(micro_all).astype(np.uint16),
        channels=np.concatenate(channel_all).astype(np.int8),
        start_stop=start_stop,
        truth=truth,
        parameters=parameters,
    )
