"""Rectangle FRAP: the recovery model, its preprocessing, and the fit.

What distinguishes this from the familiar recovery-curve analysis is that the
model is fitted in **space and time** — the full bleach profile at every frame,
not one averaged number per frame. These tests are built around what that buys:
the diffusion coefficient, the bleach depth, the mobile fraction and the edge
blur come out separately, where a single curve entangles them.
"""

from __future__ import annotations

import numpy as np
import pytest

from chisurf.core.fluorescence.imaging.frap import (
    FrapResult,
    fit_rfrap,
    normalise_frap_stack,
    recovery_curve,
    rfrap_model,
)
from chisurf.core.roi.roi import RectangleROI

PIXEL = 0.2
RECT = (20.0, 20.0, 44.0, 44.0)  # (row0, col0, row1, col1), pixels
TRUTH = dict(
    diffusion_coefficient=0.35,
    bleach_depth=0.6,
    mobile_fraction=0.8,
    edge_width=0.4,
)


def _grid(ny=64, nx=64):
    """Return pixel-centre coordinates relative to the bleach-rectangle centre."""
    cx = (RECT[1] + RECT[3]) / 2.0
    cy = (RECT[0] + RECT[2]) / 2.0
    xs = (np.arange(nx, dtype=float) + 0.5 - cx) * PIXEL
    ys = (np.arange(ny, dtype=float) + 0.5 - cy) * PIXEL
    return np.meshgrid(xs, ys)


def _synthetic(times, **overrides):
    """Return a noiseless stack generated by the model itself."""
    gx, gy = _grid()
    params = {**TRUTH, **overrides}
    side = (RECT[2] - RECT[0]) * PIXEL
    return np.stack([rfrap_model(gx, gy, t, lx=side, ly=side, f0=1.0, **params) for t in times])


# --- the model -------------------------------------------------------------
def test_bleach_is_deepest_at_the_centre_and_recovers_to_the_baseline():
    """Immediately after the bleach the centre is darkest; long after, uniform."""
    big = dict(lx=20.0, ly=20.0, edge_width=0.3, f0=1.0)
    centre_now = float(rfrap_model(0.0, 0.0, 0.0, 1.0, 0.5, **big))
    centre_late = float(rfrap_model(0.0, 0.0, 1e6, 1.0, 0.5, **big))
    outside_now = float(rfrap_model(30.0, 0.0, 0.0, 1.0, 0.5, **big))

    assert centre_now == pytest.approx(0.5, abs=1e-3)
    assert centre_late > 0.99
    assert outside_now == pytest.approx(1.0, abs=1e-3)


def test_an_immobile_population_never_recovers():
    """With a zero mobile fraction the profile is frozen at t = 0."""
    big = dict(lx=10.0, ly=10.0, edge_width=0.4, f0=1.0, mobile_fraction=0.0)
    early = rfrap_model(np.linspace(-8, 8, 33), 0.0, 0.0, 1.0, 0.7, **big)
    late = rfrap_model(np.linspace(-8, 8, 33), 0.0, 1e4, 1.0, 0.7, **big)
    np.testing.assert_allclose(early, late)


def test_partial_mobile_fraction_recovers_partway():
    """Half mobile recovers to halfway between the bleach and the baseline."""
    big = dict(lx=10.0, ly=10.0, edge_width=0.3, f0=1.0)
    bleached = float(rfrap_model(0.0, 0.0, 0.0, 1.0, 0.6, mobile_fraction=1.0, **big))
    late = float(rfrap_model(0.0, 0.0, 1e5, 1.0, 0.6, mobile_fraction=0.5, **big))
    assert late == pytest.approx(bleached + 0.5 * (1.0 - bleached), abs=1e-3)


def test_faster_diffusion_fills_the_bleach_sooner():
    """D orders the recovery: more diffusion, more signal back at a fixed time."""
    big = dict(lx=6.0, ly=6.0, edge_width=0.3, f0=1.0)
    slow = float(rfrap_model(0.0, 0.0, 1.0, 0.1, 0.6, **big))
    fast = float(rfrap_model(0.0, 0.0, 1.0, 2.0, 0.6, **big))
    assert fast > slow


# --- the fit ---------------------------------------------------------------
def test_fit_recovers_every_parameter_from_noiseless_data():
    """The four parameters are separately identifiable from the 2-D profile."""
    times = np.linspace(0.0, 4.0, 15)
    result = fit_rfrap(_synthetic(times), times, RECT, pixel_size=PIXEL)

    assert result.success
    assert result.diffusion_coefficient == pytest.approx(TRUTH["diffusion_coefficient"], rel=1e-4)
    assert result.bleach_depth == pytest.approx(TRUTH["bleach_depth"], rel=1e-4)
    assert result.mobile_fraction == pytest.approx(TRUTH["mobile_fraction"], rel=1e-4)
    assert result.edge_width == pytest.approx(TRUTH["edge_width"], rel=1e-4)


def test_fit_survives_realistic_noise():
    """With 2 % noise the diffusion coefficient is still recovered to a few %."""
    rng = np.random.default_rng(0)
    times = np.linspace(0.0, 4.0, 15)
    stack = _synthetic(times)
    noisy = stack + rng.normal(0.0, 0.02, stack.shape)

    result = fit_rfrap(noisy, times, RECT, pixel_size=PIXEL)
    assert result.success
    assert result.diffusion_coefficient == pytest.approx(TRUTH["diffusion_coefficient"], rel=0.05)
    assert result.mobile_fraction == pytest.approx(TRUTH["mobile_fraction"], rel=0.05)


def test_fit_converges_from_a_poor_starting_guess():
    """A starting D an order of magnitude out still finds the optimum."""
    times = np.linspace(0.0, 4.0, 15)
    result = fit_rfrap(
        _synthetic(times),
        times,
        RECT,
        pixel_size=PIXEL,
        diffusion_coefficient=10.0,
        bleach_depth=0.1,
        edge_width=2.0,
    )
    assert result.diffusion_coefficient == pytest.approx(TRUTH["diffusion_coefficient"], rel=1e-3)


def test_fixing_the_mobile_fraction_holds_it_exactly():
    """A fixed parameter must not drift, so a known-complete recovery stays 1."""
    times = np.linspace(0.0, 4.0, 12)
    stack = _synthetic(times, mobile_fraction=1.0)
    result = fit_rfrap(
        stack,
        times,
        RECT,
        pixel_size=PIXEL,
        mobile_fraction=1.0,
        fit_mobile_fraction=False,
    )
    assert result.mobile_fraction == 1.0
    assert result.diffusion_coefficient == pytest.approx(TRUTH["diffusion_coefficient"], rel=1e-3)


def test_diffusion_is_reported_in_physical_units():
    """D scales with the square of the pixel size, as a length² per time must."""
    times = np.linspace(0.0, 4.0, 12)
    stack = _synthetic(times)
    fine = fit_rfrap(stack, times, RECT, pixel_size=PIXEL)
    coarse = fit_rfrap(stack, times, RECT, pixel_size=2 * PIXEL)
    assert coarse.diffusion_coefficient == pytest.approx(4.0 * fine.diffusion_coefficient, rel=1e-3)


def test_mismatched_times_and_frames_are_rejected():
    """A time axis that does not match the stack fails loudly."""
    times = np.linspace(0.0, 4.0, 15)
    with pytest.raises(ValueError):
        fit_rfrap(_synthetic(times), times[:-1], RECT, pixel_size=PIXEL)


def test_a_degenerate_rectangle_is_rejected():
    """A zero-area bleach region cannot define the model."""
    times = np.linspace(0.0, 1.0, 4)
    with pytest.raises(ValueError, match="degenerate"):
        fit_rfrap(_synthetic(times), times, (10.0, 10.0, 10.0, 20.0), pixel_size=PIXEL)


def test_result_serialises():
    """The result is JSON-friendly for the CLI and RPC paths."""
    import json

    times = np.linspace(0.0, 2.0, 8)
    result = fit_rfrap(_synthetic(times), times, RECT, pixel_size=PIXEL)
    restored = json.loads(json.dumps(result.to_dict()))
    assert restored["success"] is True
    assert restored["diffusion_coefficient"] > 0


# --- preprocessing ---------------------------------------------------------
def test_prebleach_normalisation_flattens_uneven_illumination():
    """Uneven staining divides out, leaving the unbleached field at 1.0.

    Without this the bleach profile would be riding on the illumination
    profile, and the fit would attribute the shading to the bleach.
    """
    yy, xx = np.mgrid[0:32, 0:32]
    shading = 1.0 + 0.5 * (xx / 31.0)  # a 50 % gradient across the field
    stack = np.stack([shading] * 3 + [shading * 0.5] * 3)

    out = normalise_frap_stack(stack, n_prebleach=3, median_size=0)
    np.testing.assert_allclose(out[:3], 1.0, atol=1e-12)
    np.testing.assert_allclose(out[3:], 0.5, atol=1e-12)


def test_background_correction_removes_lamp_drift():
    """A frame-wide intensity drift is divided out before normalisation.

    Left in, a decaying lamp looks exactly like a sample that fails to recover.
    """
    base = np.ones((16, 16))
    drift = [1.0, 0.9, 0.8, 0.7]
    stack = np.stack([base * d for d in drift])
    background = RectangleROI(0, 0, 4, 4)

    out = normalise_frap_stack(stack, n_prebleach=2, background=background, median_size=0)
    np.testing.assert_allclose(out, 1.0, atol=1e-12)


def test_normalisation_rejects_impossible_prebleach_counts():
    """Zero or all-frames pre-bleach leaves nothing to normalise against."""
    stack = np.ones((4, 8, 8))
    for bad in (0, 4, 9):
        with pytest.raises(ValueError):
            normalise_frap_stack(stack, n_prebleach=bad)


def test_the_median_filter_protects_against_reference_noise():
    """Filtering the pre-bleach average keeps its shot noise out of every frame."""
    rng = np.random.default_rng(2)
    truth = np.ones((48, 48))
    stack = np.stack([truth + rng.normal(0, 0.1, truth.shape) for _ in range(6)])

    unfiltered = normalise_frap_stack(stack, n_prebleach=3, median_size=0)
    filtered = normalise_frap_stack(stack, n_prebleach=3, median_size=5)
    # the post-bleach frames should sit at 1.0; less scatter means less noise
    # injected from the reference
    assert filtered[3:].std() < unfiltered[3:].std()


# --- the classic curve -----------------------------------------------------
def test_recovery_curve_rises_after_the_bleach():
    """The averaged curve is the quick visual check, and must show recovery."""
    times = np.linspace(0.0, 4.0, 15)
    stack = _synthetic(times)
    roi = RectangleROI(RECT[1], RECT[0], RECT[3], RECT[2])

    t, mean = recovery_curve(stack, roi, times)
    assert t.shape == mean.shape == times.shape
    assert mean[-1] > mean[0], "the bleached region must fill back in"
    assert mean[0] < 1.0, "it must start below the normalised baseline"


def test_recovery_curve_accepts_a_bare_mask():
    """A boolean mask works as well as a ROI object."""
    times = np.linspace(0.0, 2.0, 6)
    stack = _synthetic(times)
    mask = np.zeros(stack.shape[1:], dtype=bool)
    mask[24:40, 24:40] = True
    _, mean = recovery_curve(stack, mask, times)
    assert mean[-1] > mean[0]


def test_half_time_needs_a_fit_to_be_meaningful():
    """The reported half-time follows from the fitted D and the bleach size."""
    times = np.linspace(0.0, 4.0, 12)
    result = fit_rfrap(_synthetic(times), times, RECT, pixel_size=PIXEL)
    side = (RECT[2] - RECT[0]) * PIXEL
    assert result.half_time == pytest.approx(
        side**2 / (16.0 * result.diffusion_coefficient), rel=1e-9
    )
    # a result built by hand has no bleach geometry, so it declines to guess
    assert np.isnan(FrapResult(1.0, 0.5, 1.0, 0.4).half_time)
