"""The legacy per-entity field lists of the MMFDB Admin forms (Qt-free).

Entities whose dictionary category is sparse (a sample's foreign keys, a probe's
optical columns) are still described by these lists; everything else is derived
from the mmCIF dictionary by :mod:`.entity_schema`. Shared by the Qt
``MMFDBDetailWidget``/``EntityDock`` and the native emtk admin.
"""

from __future__ import annotations

# Legacy hardcoded schemas — kept for backward compatibility only.
# New code should use entity_schema.field_specs_for_category() instead.
SCHEMAS = {
    "user": [
        {"name": "user_id", "label": "User ID", "type": "str", "required": True},
        {
            "name": "user_uuid",
            "label": "UUID",
            "type": "str",
            "readonly": True,
            "placeholder": "Auto-generated if left empty",
        },
        {"name": "display_name", "label": "Display Name", "type": "str", "required": True},
        {"name": "email", "label": "Email", "type": "str"},
        {
            "name": "role",
            "label": "Role",
            "type": "choice",
            "choices": ["user", "admin", "pi", "postdoc", "phd", "student"],
        },
        {"name": "affiliation", "label": "Affiliation", "type": "str"},
        {"name": "department", "label": "Department", "type": "str"},
        {"name": "phone", "label": "Phone", "type": "str"},
        {"name": "website", "label": "Website", "type": "str"},
        {"name": "address", "label": "Address", "type": "text"},
        {"name": "is_admin", "label": "Is Admin", "type": "bool"},
        {"name": "allow_passwordless_login", "label": "Allow Passwordless Login", "type": "bool"},
        {"name": "active_branch_uuid", "label": "Active Branch UUID", "type": "str"},
        {"name": "created_at", "label": "Created At", "type": "str", "readonly": True},
        {"name": "updated_at", "label": "Updated At", "type": "str", "readonly": True},
        {"name": "details", "label": "Details", "type": "text"},
    ],
    "device": [
        {"name": "device_id", "label": "Device ID", "type": "str", "required": True},
        {"name": "name", "label": "Name", "type": "str", "required": True},
        {"name": "device_type", "label": "Device Type", "type": "str"},
        {"name": "model", "label": "Model", "type": "str"},
        {"name": "serial_number", "label": "Serial Number", "type": "str"},
        {"name": "location", "label": "Location", "type": "str"},
        {"name": "owner", "label": "Owner", "type": "str"},
        {"name": "details", "label": "Details", "type": "text"},
        {"name": "created_at", "label": "Created At", "type": "str", "readonly": True},
        {"name": "updated_at", "label": "Updated At", "type": "str", "readonly": True},
    ],
    "sample": [
        {"name": "sample_id", "label": "Sample ID", "type": "str", "required": True},
        {
            "name": "sample_uuid",
            "label": "UUID",
            "type": "str",
            "readonly": True,
            "placeholder": "Auto-generated if left empty",
        },
        {"name": "description", "label": "Description", "type": "str"},
        {"name": "num_of_probes", "label": "Number of Probes", "type": "int"},
        {
            "name": "solvent_phase",
            "label": "Solvent Phase",
            "type": "choice",
            "choices": ["liquid", "vitrified", "other"],
        },
        {"name": "sample_condition_id", "label": "Condition ID", "type": "str"},
        {"name": "entity_assembly_id", "label": "Entity Assembly ID", "type": "str"},
        {"name": "project_id", "label": "Project ID", "type": "str"},
        {"name": "measured_by_user_id", "label": "Measured By (User)", "type": "str"},
        {"name": "measured_by_device_id", "label": "Measured By (Device)", "type": "str"},
        {"name": "measured_at", "label": "Measured At", "type": "str"},
        {"name": "details", "label": "Details", "type": "text"},
        {"name": "created_at", "label": "Created At", "type": "str", "readonly": True},
        {"name": "updated_at", "label": "Updated At", "type": "str", "readonly": True},
    ],
    "experiment": [
        {"name": "experiment_id", "label": "Experiment ID", "type": "str", "required": True},
        {"name": "type_id", "label": "Type ID", "type": "int"},
        {"name": "sample_id", "label": "Sample ID", "type": "str"},
        {"name": "project_id", "label": "Project ID", "type": "str"},
        {"name": "measured_by_user_id", "label": "Measured By (User)", "type": "str"},
        {"name": "measured_by_device_id", "label": "Measured By (Device)", "type": "str"},
        {"name": "started_at", "label": "Started At", "type": "str"},
        {"name": "ended_at", "label": "Ended At", "type": "str"},
        {"name": "status", "label": "Status", "type": "str"},
        {"name": "setup_definition_id", "label": "Setup ID", "type": "str"},
        {"name": "details", "label": "Details", "type": "text"},
        {"name": "created_at", "label": "Created At", "type": "str", "readonly": True},
        {"name": "updated_at", "label": "Updated At", "type": "str", "readonly": True},
    ],
    "experiment_type": [
        {"name": "type_id", "label": "Type ID", "type": "int", "readonly": True},
        {"name": "name", "label": "Name", "type": "str", "required": True},
        {"name": "category", "label": "Category", "type": "str"},
        {"name": "description", "label": "Description", "type": "str"},
        {"name": "details", "label": "Details", "type": "text"},
        {"name": "created_at", "label": "Created At", "type": "str", "readonly": True},
        {"name": "updated_at", "label": "Updated At", "type": "str", "readonly": True},
    ],
    "branch": [
        {
            "name": "branch_uuid",
            "label": "Branch UUID",
            "type": "str",
            "readonly": True,
            "placeholder": "Auto-generated UUID",
        },
        {"name": "name", "label": "Branch Name", "type": "str", "required": True},
        {"name": "parent_branch_uuid", "label": "Parent Branch UUID", "type": "str"},
        {"name": "head_operation_id", "label": "Head Operation ID", "type": "str"},
        {"name": "description", "label": "Description", "type": "text"},
    ],
    "probe": [
        {"name": "probe_id", "label": "Probe ID", "type": "int", "readonly": True},
        {"name": "chromophore_name", "label": "Chromophore Name", "type": "str", "required": True},
        {"name": "reactive_probe_flag", "label": "Reactive Probe Flag", "type": "str"},
        {"name": "reactive_probe_name", "label": "Reactive Probe Name", "type": "str"},
        {"name": "probe_origin", "label": "Probe Origin", "type": "str"},
        {"name": "probe_link_type", "label": "Probe Link Type", "type": "str"},
        {"name": "fluorophore_type", "label": "Fluorophore Type", "type": "str"},
        {"name": "description", "label": "Description", "type": "text"},
        {"name": "category", "label": "Category", "type": "str"},
        {"name": "is_curated", "label": "Is Curated", "type": "bool"},
        {"name": "quality_flag", "label": "Quality Flag", "type": "int"},
        {"name": "abs_max", "label": "Absorbance Max (nm)", "type": "float"},
        {"name": "em_max", "label": "Emission Max (nm)", "type": "float"},
        {"name": "qy", "label": "Quantum Yield", "type": "float"},
        {"name": "ext_coeff", "label": "Extinction Coefficient", "type": "float"},
        {"name": "created_at", "label": "Created At", "type": "str", "readonly": True},
        {"name": "updated_at", "label": "Updated At", "type": "str", "readonly": True},
    ],
    "setup": [
        {"name": "setup_id", "label": "Setup ID", "type": "str", "required": True},
        {"name": "name", "label": "Name", "type": "str", "required": True},
        {"name": "instrument_type", "label": "Instrument Type", "type": "str"},
        {
            "name": "laser_wavelengths",
            "label": "Laser Wavelengths",
            "type": "str",
            "placeholder": "[485, 640]",
        },
        {
            "name": "detector_channels",
            "label": "Detector Channels",
            "type": "str",
            "placeholder": '{"ch1": ...}',
        },
        {"name": "details", "label": "Details", "type": "text"},
        {"name": "created_by_user_id", "label": "Owner", "type": "str", "readonly": True},
        {"name": "is_public", "label": "Public", "type": "bool"},
        {"name": "created_at", "label": "Created At", "type": "str", "readonly": True},
        {"name": "updated_at", "label": "Updated At", "type": "str", "readonly": True},
    ],
    "project": [
        {"name": "project_id", "label": "Version ID", "type": "str", "readonly": True},
        {"name": "name", "label": "Name", "type": "str", "readonly": True},
        {"name": "description", "label": "Notes", "type": "text", "readonly": True},
        {"name": "created_at", "label": "Created At", "type": "str", "readonly": True},
        {"name": "updated_at", "label": "Updated At", "type": "str", "readonly": True},
    ],
    "raw_data": [
        {"name": "raw_data_id", "label": "Raw Data ID", "type": "str", "readonly": True},
        {"name": "experiment_id", "label": "Experiment ID", "type": "str", "readonly": True},
        {"name": "data_type", "label": "Data Type", "type": "str", "readonly": True},
        {"name": "storage_mode", "label": "Storage Mode", "type": "str", "readonly": True},
        {"name": "location", "label": "File Path/URL/Folder", "type": "str", "readonly": True},
        {
            "name": "validation_status",
            "label": "Validation Status",
            "type": "str",
            "readonly": True,
        },
        {"name": "checksum", "label": "Checksum (SHA-256)", "type": "str", "readonly": True},
        {"name": "details", "label": "Details/JSON", "type": "text", "readonly": True},
    ],
    "processing_run": [
        {"name": "processing_id", "label": "Processing ID", "type": "str", "readonly": True},
        {"name": "experiment_id", "label": "Experiment ID", "type": "str", "readonly": True},
        {"name": "type", "label": "Type", "type": "str", "readonly": True},
        {"name": "status", "label": "Status", "type": "str", "readonly": True},
        {"name": "settings", "label": "Settings/JSON", "type": "text", "readonly": True},
    ],
    "processed_product": [
        {"name": "product_id", "label": "Product ID", "type": "str", "readonly": True},
        {"name": "processing_id", "label": "Processing Run ID", "type": "str", "readonly": True},
        {"name": "product_type", "label": "Product Type", "type": "str", "readonly": True},
        {"name": "storage_mode", "label": "Storage Mode", "type": "str", "readonly": True},
        {"name": "location", "label": "File Path/URL/Folder", "type": "str", "readonly": True},
        {
            "name": "validation_status",
            "label": "Validation Status",
            "type": "str",
            "readonly": True,
        },
        {"name": "checksum", "label": "Checksum (SHA-256)", "type": "str", "readonly": True},
        {"name": "experiment_id", "label": "Experiment ID", "type": "str", "readonly": True},
    ],
    "object": [
        {"name": "object_uuid", "label": "Object UUID", "type": "str", "readonly": True},
        {"name": "content_md5", "label": "MD5", "type": "str", "readonly": True},
        {
            "name": "original_filename",
            "label": "Original Filename",
            "type": "str",
            "readonly": True,
        },
        {"name": "size_bytes", "label": "Size Bytes", "type": "int", "readonly": True},
        {"name": "mime_type", "label": "MIME Type", "type": "str", "readonly": True},
        {"name": "refcount", "label": "Refcount", "type": "int", "readonly": True},
        {"name": "storage_path", "label": "Storage Path", "type": "str", "readonly": True},
        {"name": "created_at", "label": "Created At", "type": "str", "readonly": True},
        {"name": "created_by", "label": "Created By", "type": "str", "readonly": True},
    ],
    "analysis": [
        {"name": "analysis_id", "label": "Analysis ID", "type": "str", "readonly": True},
        {"name": "experiment_id", "label": "Experiment ID", "type": "str", "readonly": True},
        {"name": "type", "label": "Type", "type": "str", "readonly": True},
        {"name": "model_name", "label": "Model Name", "type": "str", "readonly": True},
        {"name": "settings", "label": "Settings/JSON", "type": "text", "readonly": True},
    ],
    "condition": [
        {"name": "condition_id", "label": "Condition ID", "type": "str", "required": True},
        {"name": "ph", "label": "pH", "type": "float"},
        {"name": "temperature", "label": "Temperature [K]", "type": "float"},
        {"name": "ionic_strength", "label": "Ionic Strength [M]", "type": "float"},
        {"name": "buffer_composition", "label": "Buffer", "type": "str"},
        {"name": "details", "label": "Details", "type": "text"},
    ],
}
