r"""Hidden Markov models with Gaussian emissions, fitted by Baum-Welch.

A hidden Markov model describes a sequence of observations
:math:`x_1 \dots x_T` as generated by an unobserved Markov chain of discrete
states :math:`z_1 \dots z_T`. It is parameterised by an initial-state
distribution :math:`\pi_i = P(z_1 = i)`, a transition matrix
:math:`A_{ij} = P(z_{t+1} = j \mid z_t = i)` and, here, one multivariate normal
emission density per state,

.. math::

    P(x_t \mid z_t = i) = \mathcal{N}(x_t; \mu_i, \Sigma_i).

ChiSurf uses this for binned single-molecule traces: each time bin carries the
photon counts of one or more detection channels, and the states are the
conformational/photophysical states the molecule dwells in. The state path
recovered by :meth:`GaussianHMM.predict` gives dwell times and a transition
matrix; :meth:`GaussianHMM.bic` selects how many states the data supports.

Everything here is maximum-likelihood: parameters are estimated by the
Baum-Welch (EM) algorithm, with optional conjugate priors that act as
regularisers rather than as a full Bayesian treatment. The variational-Bayes
counterpart used for empirical-Bayes FRET analysis lives in the ebFRET plugin
(``chisurf/plugins/burst/burst_ebfret/core/hmm.py``); the photon-by-photon
variant is H2MM.

The forward-backward recursions run in log space, so long traces do not
underflow, and the time-stepping loops are the photon library's compiled
lattice.

Where the analysis lives
------------------------
This module is the *estimator*: fit, score, decode, sample, AIC/BIC. Its
surface deliberately uses the vocabulary of the general HMM literature
(``n_components``, ``covariance_type``, ``transmat_``, ``predict``).

It is **not** where an analysis should be assembled. Relabelling states by
brightness, defining a dwell time, converting transitions to rates and choosing
a state count are decisions that must not differ between two tools reporting
"state 1", so they live once in ``chisurf.plugins.core.hmm.core``, and the GUI
tool, the ``csc hmm`` CLI, the ``hmm.fit``/``hmm.scan`` RPC methods and the
intensity-trace tool all go through it. Call that, not this, unless you are
writing a new estimator-level feature.

Why this is written out rather than imported
--------------------------------------------
It replaced an external HMM package, and is 1.1x to 18x faster per E-step and
2x to 10x faster end to end at an equal or better optimum (the numbers, and the
script that produces them, are in ``docs/development/benchmarks.md`` and
``test/benchmarks/benchmark_hmm.py``). Three decisions account for that, and
each is a thing to preserve rather than an accident:

1. **One fused backward sweep** (:func:`_backward_posteriors_xi`). The backward
   lattice, the state posteriors and the expected transition counts all need
   the same quantity; computing and exponentiating it once, in one reverse
   pass, beats the textbook arrangement of three passes, and keeps two rows of
   the backward lattice alive instead of the whole ``(T, K)`` array.
2. **Data-driven initialisation** (:meth:`GaussianHMM._init`). Every parameter
   starts from one k-means clustering read as a hard-assignment state path.
   The usual random draw ignores the data, including its time ordering.
3. **SQUAREM acceleration** (:meth:`GaussianHMM._fit_squarem`), on by default.
   It reaches the same fixed point in a fraction of the maps wherever EM
   crawls, and steps aside when it stops paying.

Invariants a change must not break
----------------------------------
Each of these was a real defect first, so they are cheap to reintroduce:

* **Log space is load-bearing, and so are its infinities.** The compiled
  lattice guards against ``-inf``; fast-math licenses the compiler to assume no
  operand is infinite and deletes those guards. The library therefore builds
  that translation unit without it, and an all-``-inf`` frame is a test rather
  than a hope.
* **A frame that no state can explain gets a uniform posterior.** Its
  ``log_gamma`` row is all ``-inf``, and subtracting its own maximum yields
  ``nan``, which then spreads through the M-step into every later iteration.
  The ``-inf`` log-likelihood still reports the problem upstream.
* **A state with no posterior mass keeps its parameters.** Fitting more states
  than the data supports is a normal thing for a user to do; it must degrade,
  not produce ``nan`` means from ``0/0``.
* **Structural zeros are honoured; accidental ones are never created.** A zero
  in :attr:`~GaussianHMM.transmat_` is preserved by the M-step -- that is how a
  left-to-right chain stays a left-to-right chain -- so neither the
  initialisation nor SQUAREM's projection is allowed to introduce one, or a
  state becomes permanently unreachable.

Examples
--------
>>> import numpy as np
>>> from chisurf.core.math.hmm import GaussianHMM
>>> model = GaussianHMM(n_components=2, covariance_type="full", random_state=0)
>>> rng = np.random.default_rng(0)
>>> x = np.concatenate([rng.normal(0, 1, 200), rng.normal(10, 1, 200)])[:, None]
>>> states = model.fit(x).predict(x)
>>> np.round(np.sort(model.means_.ravel())).tolist()
[0.0, 10.0]

References
----------
.. [1] L. R. Rabiner, "A tutorial on hidden Markov models and selected
       applications in speech recognition", Proc. IEEE 77, 257-286 (1989).
.. [2] X. Huang, A. Acero, H.-W. Hon, "Spoken Language Processing",
       Prentice Hall (2001), pp. 443-445 (MAP re-estimation formulas).
"""

from __future__ import annotations

import logging
import sys
from collections import deque
from collections.abc import Iterator, Sequence

import numpy as np
from scipy import linalg

__all__ = ["COVARIANCE_TYPES", "ConvergenceMonitor", "GaussianHMM"]

logger = logging.getLogger(__name__)

#: Emission covariance parameterisations understood by :class:`GaussianHMM`.
COVARIANCE_TYPES = ("spherical", "diag", "full", "tied")

#: A SQUAREM cycle costs three EM maps. It is counted as wasted when it gains
#: less than this multiple of the cycle's own first EM step -- EM gains shrink
#: as the fixed point nears, so plain maps could not have done better either.
SQUAREM_MIN_GAIN_FACTOR = 1.0

#: Number of consecutive wasted cycles after which acceleration is abandoned and
#: the remaining budget is spent on plain EM. Kept high: acceleration routinely
#: spends a few modest cycles before a large jump.
SQUAREM_PATIENCE = 4


# ---------------------------------------------------------------------------
# the lattice
# ---------------------------------------------------------------------------
#
# The forward, backward, posterior/xi and Viterbi recursions are the photon
# library's. They used to be compiled here with numba -- five kernels and a
# hand-picked ``fastmath`` set, because the stock one deleted the ``-inf``
# guards the log domain depends on. That constraint did not go away; it moved,
# and is pinned there by a translation unit built without fast-math and a test
# on an all-``-inf`` frame.
#
# The wrappers below exist so the recursions keep their names and their call
# signatures: ``fwd``, ``bwd``, ``posteriors`` and ``state_sequence`` are
# buffers the caller allocates and this module reuses across EM iterations, and
# ``xi_sum`` is *accumulated* into across every sequence of a fit. The library
# takes them in place and honours both, which is why the delegation is a
# forward and not a rewrite of the E-step.


def _require_lattice():
    """Return the photon library's HMM lattice functions, or say why not.

    Returns
    -------
    tuple of callable
        ``(forward, backward, backward_posteriors_xi, viterbi, logsumexp)``.

    Raises
    ------
    RuntimeError
        If the library is missing or predates the lattice.
    """
    try:
        import tttrlib
    except ImportError as exc:  # pragma: no cover - tttrlib is a hard dependency
        raise RuntimeError(
            "the hidden-Markov lattice is provided by tttrlib, which could not be imported"
        ) from exc
    try:
        return (
            tttrlib.hmm_forward_log,
            tttrlib.hmm_backward_log,
            tttrlib.hmm_backward_posteriors_xi,
            tttrlib.hmm_viterbi_log,
            tttrlib.hmm_logsumexp,
        )
    except AttributeError as exc:
        raise RuntimeError(
            "tttrlib does not expose hmm_forward_log / hmm_backward_log / "
            "hmm_backward_posteriors_xi / hmm_viterbi_log / hmm_logsumexp; "
            "rebuild it (the log-domain lattice carries the forward-backward "
            "recursions)"
        ) from exc


def _logsumexp(values: np.ndarray) -> float:
    """Return ``log(sum(exp(values)))`` computed without overflow.

    An all ``-inf`` input returns ``-inf`` rather than ``nan``; a structurally
    constrained model produces whole ``-inf`` columns, so that is a value and
    not an error.
    """
    _, _, _, _, logsumexp = _require_lattice()
    return float(logsumexp(np.ascontiguousarray(values, dtype=np.float64)))


def _forward_log(
    log_startprob: np.ndarray,
    log_transmat: np.ndarray,
    log_frameprob: np.ndarray,
    fwd: np.ndarray,
) -> float:
    r"""Fill ``fwd`` with the log forward lattice and return the log-likelihood.

    ``fwd[t, i]`` is :math:`\log P(x_1 \dots x_t, z_t = i)`.
    """
    forward, _, _, _, _ = _require_lattice()
    return float(forward(log_startprob, log_transmat, log_frameprob, fwd))


def _backward_log(
    log_transmat: np.ndarray,
    log_frameprob: np.ndarray,
    bwd: np.ndarray,
) -> None:
    r"""Fill ``bwd`` with the log backward lattice.

    ``bwd[t, i]`` is :math:`\log P(x_{t+1} \dots x_T \mid z_t = i)`. Kept as a
    standalone recursion for testing; the E-step uses
    :func:`_backward_posteriors_xi`, which folds this into a single sweep.
    """
    _, backward, _, _, _ = _require_lattice()
    backward(log_transmat, log_frameprob, bwd)


def _backward_posteriors_xi(
    log_transmat: np.ndarray,
    log_frameprob: np.ndarray,
    fwd: np.ndarray,
    log_prob: float,
    posteriors: np.ndarray,
    xi_sum: np.ndarray,
) -> None:
    r"""Sweep backwards once, filling ``posteriors`` and accumulating ``xi_sum``.

    Backward lattice, state posteriors and expected transition counts all need
    the same quantity :math:`\log a_{ij} + \log b_j(x_{t+1}) + \beta_{t+1}(j)`,
    so the library computes and exponentiates it once rather than running three
    passes over the lattice.

    Two behaviours the E-step depends on: ``xi_sum`` is **added to**, never
    cleared, because every sequence of a fit accumulates into the same matrix;
    and a frame no state can explain gets a uniform posterior rather than
    ``nan``, while an impossible *sequence* contributes no transition counts at
    all.
    """
    _, _, backward_posteriors_xi, _, _ = _require_lattice()
    backward_posteriors_xi(log_transmat, log_frameprob, fwd, float(log_prob), posteriors, xi_sum)


def _viterbi(
    log_startprob: np.ndarray,
    log_transmat: np.ndarray,
    log_frameprob: np.ndarray,
    state_sequence: np.ndarray,
) -> float:
    """Fill ``state_sequence`` with the most probable path and return its log-probability.

    ``state_sequence`` must be ``int64``. Where no path is possible the
    log-probability is ``-inf`` and the returned labels are arbitrary: every
    candidate scores ``-inf``, so only the tie-break distinguishes them.
    """
    _, _, _, viterbi, _ = _require_lattice()
    return float(viterbi(log_startprob, log_transmat, log_frameprob, state_sequence))


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------


def _normalized(a: np.ndarray, axis: int | None = None) -> np.ndarray:
    """Return ``a`` scaled so that it sums to one along ``axis``.

    Sums of zero are left as zero rows rather than producing ``nan``.
    """
    a = np.asarray(a, dtype=float)
    total = a.sum(axis=axis, keepdims=axis is not None)
    total = np.where(total == 0, 1.0, total)
    return a / total


def _check_random_state(seed) -> np.random.Generator:
    """Turn ``seed`` (``None``, an int, or a generator) into a :class:`numpy.random.Generator`."""
    if seed is None or isinstance(seed, (int, np.integer)):
        return np.random.default_rng(seed)
    if isinstance(seed, np.random.Generator):
        return seed
    if isinstance(seed, np.random.RandomState):
        return np.random.default_rng(seed.randint(0, 2**32 - 1, dtype=np.int64))
    raise ValueError(f"{seed!r} cannot be used to seed a random number generator")


def _split_sequences(X: np.ndarray, lengths: Sequence[int] | None) -> Iterator[np.ndarray]:
    """Yield the individual sequences packed row-wise into ``X``."""
    if lengths is None:
        yield X
        return
    ends = np.cumsum(np.asarray(lengths, dtype=int))
    if ends[-1] != len(X):
        raise ValueError(f"lengths sum to {ends[-1]} but X has {len(X)} samples")
    starts = np.concatenate([[0], ends[:-1]])
    for start, end in zip(starts, ends):
        yield X[start:end]


#: Log emission density for every state -- moved to :mod:`chisurf.core.ml` so
#: the mixture estimators and the HMM share one implementation.
from chisurf.core.ml._gaussian import _log_gaussian_density  # noqa: E402

#: k-means++ seeding / Lloyd / the ``_kmeans`` driver -- moved to
#: :mod:`chisurf.core.ml.cluster` so the HMM and the KMeans estimator share one
#: implementation.
from chisurf.core.ml.cluster import _kmeans  # noqa: E402


def _project_simplexes(theta: np.ndarray, reference: np.ndarray, n_components: int) -> np.ndarray:
    """Return ``theta`` with its probability blocks projected back onto the simplex.

    Clipping alone would turn an overshot probability into a hard zero, and a
    zero is permanent: the M-step keeps it, so that a state a constrained model
    is allowed to reach could silently become unreachable. Anything positive in
    ``reference`` therefore keeps a floor. The remaining blocks -- means, and
    covariances in the unconstrained space of :func:`_covars_to_free` -- are
    feasible for any real value and pass through.
    """
    theta = theta.copy()
    n_probabilities = n_components + n_components * n_components
    blocks = theta[:n_probabilities]
    np.clip(blocks, 0.0, None, out=blocks)
    floor = np.finfo(float).eps / n_components
    np.copyto(blocks, floor, where=(blocks <= 0) & (reference[:n_probabilities] > 0))
    # The start distribution and every transition row share the same treatment.
    rows = blocks.reshape(n_components + 1, n_components)
    # A block that the extrapolation emptied carries no information; spread it.
    rows[rows.sum(axis=1) == 0] = 1.0 / n_components
    theta[:n_probabilities] = _normalized(rows, axis=1).ravel()
    return theta


def _covars_to_free(covars: np.ndarray, covariance_type: str) -> np.ndarray:
    """Map covariances to an unconstrained vector for SQUAREM extrapolation.

    Variances become log-variances and matrices become their lower Cholesky
    factor with a log-diagonal, so that *any* real vector maps back to a valid
    positive-definite covariance.
    """
    if covariance_type in ("spherical", "diag"):
        return np.log(np.maximum(covars, np.finfo(float).tiny)).ravel()
    matrices = covars if covariance_type == "full" else covars[None]
    try:
        chol = np.linalg.cholesky(matrices)
    except np.linalg.LinAlgError:
        # A state that captured almost no samples can lose definiteness; a
        # ridge keeps the extrapolation going instead of aborting the fit.
        n_features = matrices.shape[-1]
        ridge = 1e-6 * np.trace(matrices, axis1=1, axis2=2).max() / n_features
        logger.debug("Ridging a non positive-definite covariance by %g", ridge)
        chol = np.linalg.cholesky(matrices + ridge * np.eye(n_features))
    diagonal = np.arange(matrices.shape[-1])
    chol[:, diagonal, diagonal] = np.log(chol[:, diagonal, diagonal])
    return chol.ravel()


def _covars_from_free(
    free: np.ndarray, covariance_type: str, n_components: int, n_features: int
) -> np.ndarray:
    """Invert :func:`_covars_to_free`."""
    if covariance_type == "spherical":
        return np.exp(free)
    if covariance_type == "diag":
        return np.exp(free).reshape(n_components, n_features)
    n_matrices = n_components if covariance_type == "full" else 1
    chol = np.tril(free.reshape(n_matrices, n_features, n_features))
    diagonal = np.arange(n_features)
    chol[:, diagonal, diagonal] = np.exp(chol[:, diagonal, diagonal])
    covars = chol @ chol.transpose(0, 2, 1)
    return covars if covariance_type == "full" else covars[0]


class ConvergenceMonitor:
    """Track the EM log-likelihood and decide when Baum-Welch has converged.

    Parameters
    ----------
    tol : float
        Convergence threshold on the log-likelihood gain between two
        consecutive iterations.
    n_iter : int
        Maximum number of iterations.
    verbose : bool
        Whether to print a per-iteration report to :data:`sys.stderr`.

    Attributes
    ----------
    history : collections.deque
        Log-likelihood of every iteration performed so far.
    iter : int
        Number of iterations performed.
    """

    _template = "{iter:>10d} {log_prob:>16.8f} {delta:>+16.8f}"

    def __init__(self, tol: float, n_iter: int, verbose: bool = False):
        self.tol = tol
        self.n_iter = n_iter
        self.verbose = verbose
        self.history: deque[float] = deque(maxlen=2)
        self.iter = 0

    def __repr__(self) -> str:
        """Return a reproducible representation including the log-likelihood history."""
        return (
            f"{type(self).__name__}(tol={self.tol}, n_iter={self.n_iter}, "
            f"verbose={self.verbose}, history={list(self.history)}, iter={self.iter})"
        )

    def reset(self) -> None:
        """Forget the history of a previous fit."""
        self.iter = 0
        self.history.clear()

    @staticmethod
    def _gain(current: float, previous: float) -> float:
        """Return the log-likelihood gain between two iterations.

        Plain subtraction is wrong at the one place it matters: a model that
        assigns zero probability to the data scores ``-inf`` twice in a row,
        and ``-inf - (-inf)`` is ``nan``. Every comparison against ``nan`` is
        false, so the run neither converges nor warns -- it silently spends
        the whole iteration budget. Two equal scores are no gain, which is
        what "converged" means, whether or not they are finite.
        """
        if current == previous:
            return 0.0
        return current - previous

    def report(self, log_prob: float) -> None:
        """Record the log-likelihood of the iteration that just finished."""
        if self.verbose:
            delta = self._gain(log_prob, self.history[-1]) if self.history else np.nan
            print(
                self._template.format(iter=self.iter + 1, log_prob=log_prob, delta=delta),
                file=sys.stderr,
            )
        # A non-finite score is not a convergence result: the model explains
        # none of the data. Say so rather than returning a converged-looking
        # fit whose score, aic and bic are all -inf.
        if not np.isfinite(log_prob):
            logger.warning(
                "HMM log-likelihood is %s: the model assigns zero probability "
                "to the data (a structural zero or an emptied start "
                "distribution makes every sequence impossible).",
                log_prob,
            )
        # EM cannot decrease the likelihood; allow only for rounding noise.
        precision = np.finfo(float).eps ** 0.5
        if self.history and self._gain(log_prob, self.history[-1]) < -precision:
            logger.warning(
                "HMM is not converging: log-likelihood dropped from %s to %s",
                self.history[-1],
                log_prob,
            )
        self.history.append(log_prob)
        self.iter += 1

    @property
    def converged(self) -> bool:
        """Whether the iteration limit or the tolerance has been reached."""
        return self.iter == self.n_iter or (
            len(self.history) == 2 and self._gain(self.history[1], self.history[0]) < self.tol
        )


# ---------------------------------------------------------------------------
# model
# ---------------------------------------------------------------------------


class GaussianHMM:
    """Hidden Markov model with multivariate normal emissions.

    Parameters
    ----------
    n_components : int
        Number of hidden states.
    covariance_type : str
        Shape of the emission covariances, one of :data:`COVARIANCE_TYPES`:
        ``"spherical"`` (one variance per state), ``"diag"`` (one variance per
        state and feature), ``"full"`` (an unrestricted matrix per state) or
        ``"tied"`` (one matrix shared by all states).
    min_covar : float
        Ridge added to the empirical covariance when initialising, so that the
        first E-step cannot see a singular matrix.
    startprob_prior, transmat_prior : float or numpy.ndarray
        Dirichlet prior parameters for :attr:`startprob_` and the rows of
        :attr:`transmat_`. A value of one is the uninformative default.
    means_prior, means_weight : float or numpy.ndarray
        Normal prior on the state means; ``means_weight`` is the number of
        pseudo-observations placed at ``means_prior``. Zero disables the prior.
    covars_prior, covars_weight : float or numpy.ndarray
        Inverse-Wishart (or inverse-Gamma, for the diagonal parameterisations)
        prior on the covariances. The default keeps a small floor on the
        variance of a state that captured very few samples.
    algorithm : str
        Decoder used by :meth:`decode` and :meth:`predict`: ``"viterbi"`` for
        the most probable *path*, ``"map"`` for the sequence of individually
        most probable states.
    random_state : int, numpy.random.Generator or None
        Seed for the initial transition/start probabilities and for the k-means
        seeding of the means.
    n_iter : int
        Maximum number of EM maps (with ``accelerate``, a SQUAREM cycle spends
        three of them).
    tol : float
        Convergence threshold on the log-likelihood gain per iteration.
    accelerate : bool
        Accelerate EM with SQUAREM extrapolation (see :meth:`_fit_squarem`).
        The fixed point is the one plain EM converges to; it is simply reached
        in fewer maps. Turn it off to reproduce a textbook Baum-Welch run.
    verbose : bool
        Print the per-iteration log-likelihood to :data:`sys.stderr`.
    params, init_params : str
        Which parameters are re-estimated during :meth:`fit` (``params``) and
        which are initialised before it (``init_params``): ``"s"`` start
        probabilities, ``"t"`` transition matrix, ``"m"`` means, ``"c"``
        covariances. Drop a letter from ``init_params`` to fit from a value you
        set yourself, and from ``params`` to hold that value fixed.

    Attributes
    ----------
    startprob_ : numpy.ndarray
        Initial state distribution, shape ``(n_components, )``.
    transmat_ : numpy.ndarray
        Row-stochastic transition matrix, shape ``(n_components, n_components)``.
        ``transmat_[i, j]`` is the probability of moving from state ``i`` to ``j``.
    means_ : numpy.ndarray
        Emission means, shape ``(n_components, n_features)``.
    covars_ : numpy.ndarray
        Emission covariances in the compact layout of :attr:`covariance_type`:
        ``(n_components, )`` spherical, ``(n_components, n_features)`` diagonal,
        ``(n_components, n_features, n_features)`` full, and
        ``(n_features, n_features)`` tied. :attr:`covars_full_` always gives
        full matrices.
    monitor_ : ConvergenceMonitor
        Convergence state of the last :meth:`fit`.
    n_features : int
        Dimensionality of the emissions, set by the first :meth:`fit`.

    Notes
    -----
    Fitting is the Baum-Welch algorithm [1]_: the E-step runs forward-backward
    in log space to obtain the state posteriors, and the M-step is the MAP
    re-estimation of Huang et al. [2]_ under the priors above.

    EM finds a **local** optimum, which has three practical consequences:

    * The initialisation decides which one. It is derived from the data (see
      :meth:`_init`), not drawn at random, so results are stable; ``random_state``
      seeds only the k-means restarts, and fixing it makes a fit reproducible.
    * More states always fit better. Compare :meth:`bic` (or :meth:`aic`) across
      ``n_components`` and take the minimum; the likelihood alone cannot choose.
    * Overlapping states make EM crawl -- small gains per step while the optimum
      is still far off. That is what ``accelerate`` is for, and it is why a
      likelihood must always be reported next to a timing: a run that stops
      sooner at a worse optimum has not won.

    A caller that wants states, dwell times or rates out of a *measurement*
    should use ``chisurf.plugins.core.hmm.core`` rather than this class
    directly; see the module docstring.

    Examples
    --------
    Fit three states to a two-channel binned trace and read the kinetics off
    the result:

    >>> import numpy as np
    >>> from chisurf.core.math.hmm import GaussianHMM
    >>> rng = np.random.default_rng(0)
    >>> x = np.repeat([[5.0, 50.0], [30.0, 30.0], [55.0, 5.0]], 400, axis=0)
    >>> x = x + rng.normal(0, 2.0, x.shape)
    >>> model = GaussianHMM(n_components=3, covariance_type="full", random_state=0)
    >>> states = model.fit(x).predict(x)
    >>> np.round(np.sort(model.means_[:, 0]))
    array([ 5., 30., 55.])
    """

    def __init__(
        self,
        n_components: int = 1,
        covariance_type: str = "diag",
        min_covar: float = 1e-3,
        startprob_prior: float = 1.0,
        transmat_prior: float = 1.0,
        means_prior: float = 0.0,
        means_weight: float = 0.0,
        covars_prior: float = 1e-2,
        covars_weight: float = 1.0,
        algorithm: str = "viterbi",
        random_state=None,
        n_iter: int = 10,
        tol: float = 1e-2,
        verbose: bool = False,
        params: str = "stmc",
        init_params: str = "stmc",
        accelerate: bool = True,
    ):
        if covariance_type not in COVARIANCE_TYPES:
            raise ValueError(f"covariance_type must be one of {COVARIANCE_TYPES}")
        if algorithm not in ("viterbi", "map"):
            raise ValueError("algorithm must be 'viterbi' or 'map'")
        self.n_components = n_components
        self.covariance_type = covariance_type
        self.min_covar = min_covar
        self.startprob_prior = startprob_prior
        self.transmat_prior = transmat_prior
        self.means_prior = means_prior
        self.means_weight = means_weight
        self.covars_prior = covars_prior
        self.covars_weight = covars_weight
        self.algorithm = algorithm
        self.random_state = random_state
        self.n_iter = n_iter
        self.tol = tol
        self.verbose = verbose
        self.params = params
        self.init_params = init_params
        self.accelerate = accelerate
        self.monitor_ = ConvergenceMonitor(tol, n_iter, verbose)
        #: Set by the first call that sees data; guards later shape mismatches.
        self.n_features: int | None = None

    def __repr__(self) -> str:
        """Return the constructor call reproducing this model's configuration."""
        return (
            f"{type(self).__name__}(n_components={self.n_components}, "
            f"covariance_type={self.covariance_type!r}, n_iter={self.n_iter}, "
            f"tol={self.tol})"
        )

    # -- properties ---------------------------------------------------------

    @property
    def covars_full_(self) -> np.ndarray:
        """Emission covariances as full matrices, shape ``(n_components, nf, nf)``."""
        covars = np.asarray(self.covars_)
        if self.covariance_type == "full":
            return covars
        if self.covariance_type == "diag":
            return np.stack([np.diag(c) for c in covars])
        if self.covariance_type == "tied":
            return np.tile(covars, (self.n_components, 1, 1))
        eye = np.eye(self.n_features)[None, :, :]
        return eye * covars.reshape(-1, 1, 1)

    @property
    def n_parameters(self) -> int:
        """Number of free scalar parameters, as counted by :meth:`aic` and :meth:`bic`."""
        nc, nf = self.n_components, self.n_features
        n_covars = {
            "spherical": nc,
            "diag": nc * nf,
            "full": nc * nf * (nf + 1) // 2,
            "tied": nf * (nf + 1) // 2,
        }[self.covariance_type]
        per_param = {"s": nc - 1, "t": nc * (nc - 1), "m": nc * nf, "c": n_covars}
        return sum(per_param[p] for p in self.params if p in per_param)

    # -- fitting ------------------------------------------------------------

    def fit(self, X: np.ndarray, lengths: Sequence[int] | None = None) -> GaussianHMM:
        """Estimate the model parameters from one or more observation sequences.

        Parameters
        ----------
        X : numpy.ndarray
            Samples, shape ``(n_samples, n_features)``. Several sequences are
            passed stacked row-wise and split by ``lengths``.
        lengths : sequence of int, optional
            Length of each sequence in ``X``; they must sum to ``len(X)``. The
            default treats ``X`` as a single sequence.

        Returns
        -------
        GaussianHMM
            This model, fitted.
        """
        X = self._check_input(X)
        self._init(X, lengths)
        self.monitor_.reset()
        if self.accelerate:
            self._fit_squarem(X, lengths)
        else:
            self._fit_em(X, lengths)
        if (self.transmat_.sum(axis=1) == 0).any():
            logger.warning(
                "Some rows of transmat_ sum to zero: no transition out of those "
                "states was ever observed."
            )
        return self

    def _fit_em(
        self, X: np.ndarray, lengths: Sequence[int] | None, n_maps: int | None = None
    ) -> None:
        """Run plain Baum-Welch for ``n_maps`` maps or until the monitor converges."""
        for _ in range(self.n_iter if n_maps is None else n_maps):
            stats, log_prob = self._do_estep(X, lengths)
            # The M-step runs before the convergence check so that n_iter=1
            # still updates the parameters once.
            self._do_mstep(stats)
            self.monitor_.report(log_prob)
            if self.monitor_.converged:
                break

    def _fit_squarem(self, X: np.ndarray, lengths: Sequence[int] | None) -> None:
        r"""Run Baum-Welch accelerated by SQUAREM, scheme S3.

        EM is a fixed-point iteration :math:`\theta \to F(\theta)` that
        crawls when the states overlap. SQUAREM [3]_ takes two ordinary maps
        per cycle, forms :math:`r = F(\theta) - \theta` and
        :math:`v = F(F(\theta)) - 2 F(\theta) + \theta`, and jumps to
        :math:`\theta - 2 \alpha r + \alpha^2 v` with the steplength
        :math:`\alpha = -\lVert r \rVert / \lVert v \rVert`. The
        extrapolated point is projected back onto the feasible set (stochastic
        rows, positive-definite covariances) and kept only if a further EM map
        from it does not lower the likelihood -- so the fixed point is the same
        as plain EM's, reached in fewer maps. The same scheme accelerates the
        photon-by-photon H2MM optimiser.

        Two details are what make it safe to leave on by default:

        * **The covariances are extrapolated in an unconstrained space.**
          A linear step on a covariance matrix can leave the positive-definite
          cone; :func:`_covars_to_free` maps variances to log-variances and
          matrices to a Cholesky factor with a log-diagonal, so *any* real
          vector maps back to a valid covariance and the projection has only the
          probability simplexes left to enforce.
        * **It gives up when it stops earning its keep.** A cycle costs three
          maps, so on an easy target -- states resolved, EM converging in a
          handful of steps -- acceleration is pure overhead. After
          :data:`SQUAREM_PATIENCE` consecutive cycles that gain less than
          :data:`SQUAREM_MIN_GAIN_FACTOR` times the cycle's own first EM step,
          the remaining budget is spent on plain EM instead. EM gains shrink
          monotonically near a fixed point, which is what makes that first step
          a fair yardstick for the two that followed it.

        References
        ----------
        .. [3] R. Varadhan, C. Roland, "Simple and globally convergent methods
               for accelerating the convergence of any EM algorithm",
               Scand. J. Stat. 35, 335-353 (2008).
        """
        theta = self._get_parameters()
        n_maps = 0
        n_wasted_cycles = 0
        previous_cycle: tuple[float, float] | None = None
        while n_maps < self.n_iter:
            log_prob_0, theta_1 = self._em_map(theta, X, lengths)
            n_maps += 1

            # Judge the cycle that just ended: it spent three maps, and EM gains
            # shrink as the fixed point nears, so a cycle that gains less than
            # its own first EM step did strictly worse than plain EM. Only a
            # long run of those is taken as evidence that extrapolation has
            # nothing left to give on this problem.
            if previous_cycle is not None:
                entry_log_prob, first_gain = previous_cycle
                gain = log_prob_0 - entry_log_prob
                if 0 < first_gain and gain < SQUAREM_MIN_GAIN_FACTOR * first_gain:
                    n_wasted_cycles += 1
                else:
                    n_wasted_cycles = 0
                if n_wasted_cycles >= SQUAREM_PATIENCE:
                    logger.debug(
                        "SQUAREM stopped paying off after %d maps; finishing with plain EM.",
                        n_maps,
                    )
                    self.monitor_.report(log_prob_0)
                    if not self.monitor_.converged:
                        self._fit_em(X, lengths, self.n_iter - n_maps)
                    return

            if n_maps >= self.n_iter:
                self._set_parameters(theta_1)
                self.monitor_.report(log_prob_0)
                break

            r = theta_1 - theta
            log_prob_1, theta_2 = self._em_map(theta_1, X, lengths)
            n_maps += 1
            previous_cycle = (log_prob_0, log_prob_1 - log_prob_0)
            v = (theta_2 - theta_1) - r
            r_norm, v_norm = np.linalg.norm(r), np.linalg.norm(v)

            accepted, log_prob = theta_2, log_prob_1
            if min(r_norm, v_norm) > 1e-12 and n_maps < self.n_iter:
                # alpha is negative; -1 is the plain-EM step, so never take a
                # shorter one than that.
                alpha = min(-r_norm / v_norm, -1.0)
                candidate = _project_simplexes(
                    theta - 2 * alpha * r + alpha**2 * v, theta, self.n_components
                )
                try:
                    log_prob_2, theta_3 = self._em_map(candidate, X, lengths)
                    n_maps += 1
                except (ValueError, np.linalg.LinAlgError, linalg.LinAlgError):
                    # An extrapolation that left the feasible set is simply not
                    # taken; the plain-EM point below is always available.
                    log_prob_2 = -np.inf
                if np.isfinite(log_prob_2) and log_prob_2 >= log_prob_1:
                    accepted, log_prob = theta_3, log_prob_2

            theta = accepted
            self._set_parameters(theta)
            self.monitor_.report(log_prob)
            if self.monitor_.converged:
                break

    def _em_map(
        self, theta: np.ndarray, X: np.ndarray, lengths: Sequence[int] | None
    ) -> tuple[float, np.ndarray]:
        """Apply one EM map to ``theta``, returning its log-likelihood and the image."""
        self._set_parameters(theta)
        stats, log_prob = self._do_estep(X, lengths)
        self._do_mstep(stats)
        return log_prob, self._get_parameters()

    def _get_parameters(self) -> np.ndarray:
        """Pack the parameters into one vector, covariances in unconstrained space."""
        return np.concatenate(
            [
                self.startprob_.ravel(),
                self.transmat_.ravel(),
                self.means_.ravel(),
                _covars_to_free(self.covars_, self.covariance_type),
            ]
        )

    def _set_parameters(self, theta: np.ndarray) -> None:
        """Unpack a vector produced by :meth:`_get_parameters` into the model."""
        nc, nf = self.n_components, self.n_features
        self.startprob_ = theta[:nc].copy()
        self.transmat_ = theta[nc : nc + nc * nc].reshape(nc, nc).copy()
        offset = nc + nc * nc
        self.means_ = theta[offset : offset + nc * nf].reshape(nc, nf).copy()
        self.covars_ = _covars_from_free(theta[offset + nc * nf :], self.covariance_type, nc, nf)

    def score(self, X: np.ndarray, lengths: Sequence[int] | None = None) -> float:
        r"""Return the log-likelihood of ``X`` under the model.

        Parameters
        ----------
        X : numpy.ndarray
            Samples, shape ``(n_samples, n_features)``.
        lengths : sequence of int, optional
            Length of each sequence in ``X``.

        Returns
        -------
        float
            :math:`\log P(X \mid \theta)`, summed over the sequences.
        """
        X = self._check_input(X)
        log_prob = 0.0
        for sequence in _split_sequences(X, lengths):
            log_frameprob = self._compute_log_likelihood(sequence)
            fwd = np.empty_like(log_frameprob)
            log_prob += _forward_log(self._log_startprob, self._log_transmat, log_frameprob, fwd)
        return log_prob

    def score_samples(
        self, X: np.ndarray, lengths: Sequence[int] | None = None
    ) -> tuple[float, np.ndarray]:
        r"""Return the log-likelihood of ``X`` and the per-sample state posteriors.

        Parameters
        ----------
        X : numpy.ndarray
            Samples, shape ``(n_samples, n_features)``.
        lengths : sequence of int, optional
            Length of each sequence in ``X``.

        Returns
        -------
        log_prob : float
            Log-likelihood of ``X``.
        posteriors : numpy.ndarray
            :math:`P(z_t = i \mid X)`, shape ``(n_samples, n_components)``.
        """
        X = self._check_input(X)
        log_prob = 0.0
        posteriors = []
        for sequence in _split_sequences(X, lengths):
            sub_log_prob, sub_posteriors = self._forward_backward(sequence)
            log_prob += sub_log_prob
            posteriors.append(sub_posteriors)
        return log_prob, np.concatenate(posteriors)

    def predict_proba(self, X: np.ndarray, lengths: Sequence[int] | None = None) -> np.ndarray:
        """Return the posterior state probabilities of every sample.

        Parameters
        ----------
        X : numpy.ndarray
            Samples, shape ``(n_samples, n_features)``.
        lengths : sequence of int, optional
            Length of each sequence in ``X``.

        Returns
        -------
        numpy.ndarray
            Posteriors, shape ``(n_samples, n_components)``.
        """
        return self.score_samples(X, lengths)[1]

    def decode(
        self,
        X: np.ndarray,
        lengths: Sequence[int] | None = None,
        algorithm: str | None = None,
    ) -> tuple[float, np.ndarray]:
        """Infer the hidden state sequence of ``X``.

        Parameters
        ----------
        X : numpy.ndarray
            Samples, shape ``(n_samples, n_features)``.
        lengths : sequence of int, optional
            Length of each sequence in ``X``.
        algorithm : str, optional
            Override :attr:`algorithm` for this call.

        Returns
        -------
        log_prob : float
            Log-probability of the returned path (``"viterbi"``) or of the data
            (``"map"``).
        state_sequence : numpy.ndarray
            State index per sample, shape ``(n_samples, )``.
        """
        algorithm = algorithm or self.algorithm
        if algorithm not in ("viterbi", "map"):
            raise ValueError("algorithm must be 'viterbi' or 'map'")
        X = self._check_input(X)
        log_prob = 0.0
        states = []
        for sequence in _split_sequences(X, lengths):
            log_frameprob = self._compute_log_likelihood(sequence)
            if algorithm == "viterbi":
                sub_states = np.empty(len(sequence), dtype=np.int64)
                log_prob += _viterbi(
                    self._log_startprob, self._log_transmat, log_frameprob, sub_states
                )
            else:
                sub_log_prob, posteriors = self._forward_backward(sequence)
                log_prob += sub_log_prob
                sub_states = posteriors.argmax(axis=1)
            states.append(sub_states)
        return log_prob, np.concatenate(states)

    def predict(self, X: np.ndarray, lengths: Sequence[int] | None = None) -> np.ndarray:
        """Return the inferred state sequence of ``X``, shape ``(n_samples, )``."""
        return self.decode(X, lengths)[1]

    def sample(
        self, n_samples: int = 1, random_state=None, currstate: int | None = None
    ) -> tuple[np.ndarray, np.ndarray]:
        """Draw a sequence of observations and states from the model.

        Parameters
        ----------
        n_samples : int
            Number of samples to draw.
        random_state : int, numpy.random.Generator or None
            Seed; defaults to :attr:`random_state`.
        currstate : int, optional
            State to start from; drawn from :attr:`startprob_` by default.

        Returns
        -------
        X : numpy.ndarray
            Samples, shape ``(n_samples, n_features)``.
        state_sequence : numpy.ndarray
            The generating states, shape ``(n_samples, )``.
        """
        rng = _check_random_state(random_state if random_state is not None else self.random_state)
        covars = self.covars_full_
        states = np.empty(n_samples, dtype=int)
        states[0] = (
            rng.choice(self.n_components, p=self.startprob_) if currstate is None else currstate
        )
        for t in range(1, n_samples):
            states[t] = rng.choice(self.n_components, p=self.transmat_[states[t - 1]])
        X = np.stack([rng.multivariate_normal(self.means_[s], covars[s]) for s in states])
        return X, states

    def aic(self, X: np.ndarray, lengths: Sequence[int] | None = None) -> float:
        """Return the Akaike information criterion, ``-2 logL + 2 k`` (lower is better)."""
        return -2 * self.score(X, lengths) + 2 * self.n_parameters

    def bic(self, X: np.ndarray, lengths: Sequence[int] | None = None) -> float:
        """Return the Bayesian information criterion, ``-2 logL + k log n`` (lower is better)."""
        return -2 * self.score(X, lengths) + self.n_parameters * np.log(len(X))

    def get_stationary_distribution(self) -> np.ndarray:
        """Return the stationary distribution of :attr:`transmat_`.

        Returns
        -------
        numpy.ndarray
            The normalised left eigenvector of the transition matrix belonging
            to eigenvalue one, shape ``(n_components, )``.
        """
        eigvals, eigvecs = linalg.eig(self.transmat_.T)
        eigvec = np.real_if_close(eigvecs[:, np.argmax(eigvals)])
        return eigvec / eigvec.sum()

    # -- internals ----------------------------------------------------------

    def _check_input(self, X: np.ndarray) -> np.ndarray:
        """Validate ``X`` and return it as a 2-D float array."""
        X = np.asarray(X, dtype=float)
        if X.ndim == 1:
            X = X[:, None]
        if X.ndim != 2:
            raise ValueError(f"X must be 2-dimensional, got shape {X.shape}")
        if not np.isfinite(X).all():
            raise ValueError("X must not contain NaN or infinite values")
        n_features = X.shape[1]
        if getattr(self, "n_features", None) is None:
            self.n_features = n_features
        elif self.n_features != n_features:
            raise ValueError(
                f"X has {n_features} features but the model was fitted with {self.n_features}"
            )
        return X

    def _needs_init(self, code: str, name: str) -> bool:
        """Whether parameter ``name``, selected by ``code``, must be initialised."""
        return code in self.init_params or not hasattr(self, name)

    def _init(self, X: np.ndarray, lengths: Sequence[int] | None = None) -> None:
        """Initialise the parameters selected by :attr:`init_params` from ``X``.

        Every parameter is derived from one k-means clustering, read as a first,
        hard-assignment guess at the state path: the centres are the means, the
        per-cluster scatter is the covariance, and the label sequence supplies
        the transition counts and the state occupancies.

        That is a far better starting point for a *time series* than the usual
        random draw, which ignores the data entirely -- and it is not only a
        speed argument. The textbook initialisation draws the transition rows
        from a sparse Dirichlet, whose entries can underflow to exactly zero;
        the M-step then preserves those zeros (see :meth:`_do_mstep`), and a
        state that can never be entered again is a state EM cannot use. On a
        four-state trace with two well-separated levels that was observed to
        collapse two of them onto one wide blob and crawl for 141 iterations to
        a worse optimum, where this initialisation converges in seven to the
        right one.

        Deriving the covariances per cluster rather than from the pooled data
        matters for the same reason: a state that starts with the *global*
        variance claims samples belonging to its neighbours in the first E-step.

        Parameters
        ----------
        X : numpy.ndarray
            Samples, shape ``(n_samples, n_features)``.
        lengths : sequence of int, optional
            Sequence boundaries, so no transition is counted across the seam
            between two traces.
        """
        rng = _check_random_state(self.random_state)
        uniform = 1.0 / self.n_components
        needs = {
            code: self._needs_init(code, name)
            for code, name in (
                ("s", "startprob_"),
                ("t", "transmat_"),
                ("m", "means_"),
                ("c", "covars_"),
            )
        }

        centers, labels = (None, None)
        if any(needs.values()):
            centers, labels, _, _ = _kmeans(X, self.n_components, rng)

        if needs["m"]:
            self.means_ = centers
        if needs["s"]:
            # Occupancy of each cluster, smoothed so that no state starts out
            # unreachable.
            counts = np.bincount(labels, minlength=self.n_components) + 1.0
            self.startprob_ = counts / counts.sum()
        if needs["t"]:
            # Transitions between consecutive labels, counted within sequences.
            counts = np.full((self.n_components, self.n_components), uniform)
            for sequence in _split_sequences(labels[:, None], lengths):
                path = sequence.ravel()
                if len(path) > 1:
                    np.add.at(counts, (path[:-1], path[1:]), 1.0)
            self.transmat_ = counts / counts.sum(axis=1, keepdims=True)
        if needs["c"]:
            self.covars_ = self._initial_covariances(X, labels)

        n_fit_scalars = self.n_parameters
        if X.size < n_fit_scalars:
            logger.warning(
                "Fitting %d free parameters to %d data points gives a degenerate solution.",
                n_fit_scalars,
                X.size,
            )
        self._check_parameters()

    def _initial_covariances(self, X: np.ndarray, labels: np.ndarray) -> np.ndarray:
        """Return the per-cluster covariances in the layout of :attr:`covariance_type`.

        A cluster too small to define a covariance falls back to the covariance
        of the whole data set, which is the widest sensible guess.
        """
        ridge = self.min_covar * np.eye(self.n_features)
        pooled = np.atleast_2d(np.cov(X.T)) + ridge
        matrices = np.empty((self.n_components, self.n_features, self.n_features))
        for c in range(self.n_components):
            members = X[labels == c]
            matrices[c] = (
                np.atleast_2d(np.cov(members.T)) + ridge
                if len(members) > self.n_features
                else pooled
            )
        if self.covariance_type == "full":
            return matrices
        if self.covariance_type == "tied":
            return pooled
        variances = np.diagonal(matrices, axis1=1, axis2=2)
        return variances.mean(axis=1) if self.covariance_type == "spherical" else variances.copy()

    def _check_parameters(self) -> None:
        """Validate the current parameters, as an E-step is about to consume them."""
        self.startprob_ = np.asarray(self.startprob_, dtype=float)
        if self.startprob_.shape != (self.n_components,):
            raise ValueError("startprob_ must have shape (n_components, )")
        if not np.isclose(self.startprob_.sum(), 1):
            raise ValueError(f"startprob_ must sum to 1 (got {self.startprob_.sum():.4f})")
        self.transmat_ = np.asarray(self.transmat_, dtype=float)
        if self.transmat_.shape != (self.n_components, self.n_components):
            raise ValueError("transmat_ must have shape (n_components, n_components)")
        if not np.allclose(self.transmat_.sum(axis=1), 1):
            raise ValueError(f"transmat_ rows must sum to 1 (got {self.transmat_.sum(axis=1)})")
        self.means_ = np.asarray(self.means_, dtype=float)
        if self.means_.shape != (self.n_components, self.n_features):
            raise ValueError("means_ must have shape (n_components, n_features)")
        self.covars_ = np.asarray(self.covars_, dtype=float)
        expected = {
            "spherical": (self.n_components,),
            "diag": (self.n_components, self.n_features),
            "full": (self.n_components, self.n_features, self.n_features),
            "tied": (self.n_features, self.n_features),
        }[self.covariance_type]
        if self.covars_.shape != expected:
            raise ValueError(
                f"covars_ must have shape {expected} for covariance_type "
                f"{self.covariance_type!r}, got {self.covars_.shape}"
            )

    @property
    def _log_startprob(self) -> np.ndarray:
        """Element-wise logarithm of :attr:`startprob_`, with zeros mapped to ``-inf``."""
        with np.errstate(divide="ignore"):
            return np.log(self.startprob_)

    @property
    def _log_transmat(self) -> np.ndarray:
        """Element-wise logarithm of :attr:`transmat_`, with zeros mapped to ``-inf``."""
        with np.errstate(divide="ignore"):
            return np.log(self.transmat_)

    def _compute_log_likelihood(self, X: np.ndarray) -> np.ndarray:
        """Return the per-sample, per-state log emission densities of ``X``."""
        return _log_gaussian_density(X, self.means_, self.covars_, self.covariance_type)

    def _forward_backward(
        self, X: np.ndarray, xi_sum: np.ndarray | None = None
    ) -> tuple[float, np.ndarray]:
        """Run forward-backward on one sequence.

        Parameters
        ----------
        X : numpy.ndarray
            One observation sequence, shape ``(n_samples, n_features)``.
        xi_sum : numpy.ndarray, optional
            ``(n_components, n_components)`` accumulator that the expected
            transition counts are *added* to. Omit it when only the posteriors
            are wanted, as in decoding.

        Returns
        -------
        log_prob : float
            Log-likelihood of the sequence.
        posteriors : numpy.ndarray
            State posteriors, shape ``(n_samples, n_components)``.
        """
        log_frameprob = self._compute_log_likelihood(X)
        fwd = np.empty_like(log_frameprob)
        posteriors = np.empty_like(log_frameprob)
        log_prob = _forward_log(self._log_startprob, self._log_transmat, log_frameprob, fwd)
        if xi_sum is None:
            xi_sum = np.zeros((self.n_components, self.n_components))
        _backward_posteriors_xi(
            self._log_transmat, log_frameprob, fwd, log_prob, posteriors, xi_sum
        )
        return log_prob, posteriors

    def _do_estep(self, X: np.ndarray, lengths: Sequence[int] | None) -> tuple[dict, float]:
        """Accumulate the sufficient statistics of all sequences and their log-likelihood."""
        nc, nf = self.n_components, self.n_features
        stats = {
            "nobs": 0,
            "start": np.zeros(nc),
            "trans": np.zeros((nc, nc)),
            "post": np.zeros(nc),
            "obs": np.zeros((nc, nf)),
            "obs**2": np.zeros((nc, nf)),
            "obs*obs.T": np.zeros((nc, nf, nf)),
        }
        total_log_prob = 0.0
        for sequence in _split_sequences(X, lengths):
            # A single-sample sequence contains no transition to count; the
            # kernel simply adds nothing to the accumulator.
            log_prob, posteriors = self._forward_backward(sequence, stats["trans"])
            total_log_prob += log_prob
            stats["nobs"] += 1
            stats["start"] += posteriors[0]
            stats["post"] += posteriors.sum(axis=0)
            stats["obs"] += posteriors.T @ sequence
            if self.covariance_type in ("spherical", "diag"):
                stats["obs**2"] += posteriors.T @ sequence**2
            else:
                # One BLAS product per state rather than a single einsum: the
                # einsum path is not blocked and costs an order of magnitude more.
                for c in range(nc):
                    stats["obs*obs.T"][c] += (sequence * posteriors[:, c, None]).T @ sequence
        return stats, total_log_prob

    def _do_mstep(self, stats: dict) -> None:
        """Re-estimate the parameters selected by :attr:`params` from ``stats``.

        The updates are the MAP estimates of Huang et al. [2]_ under the
        Dirichlet/normal/inverse-Wishart priors of the constructor. A prior
        below one can make a numerator negative; those terms are clipped to
        zero, which is the maximiser under the simplex constraint.

        Two rules here have consequences elsewhere in the module:

        * **A parameter that is exactly zero stays zero.** That is what lets a
          caller express a structural constraint -- a left-to-right chain, an
          absorbing state -- by zeroing entries of :attr:`transmat_` before
          fitting. It also means a zero introduced *by accident* is permanent,
          which is why :meth:`_init` does not draw transitions at random and why
          :func:`_project_simplexes` restores a floor under anything the
          extrapolation clipped to zero.
        * **A state that collected no posterior mass keeps its emission.**
          Asking for more states than the data supports is ordinary use; the
          undefined ``0/0`` update must degrade to "this state is unused", not
          to ``nan`` means that spread through the next E-step and take the
          whole fit with them.
        """
        if "s" in self.params:
            startprob = np.maximum(self.startprob_prior - 1 + stats["start"], 0)
            startprob = np.where(self.startprob_ == 0, 0, startprob)
            # A prior carrying no pseudo-counts clips every term to zero, and
            # `_normalized` leaves the emptied block alone rather than dividing
            # 0/0 -- correct as far as it goes, but an all-zero start
            # distribution is not a distribution: it makes every sequence
            # impossible, and the -inf lattice that follows is
            # indistinguishable from a genuinely constrained model. A block
            # with no information keeps the one it had, the same rule
            # `_project_simplexes` applies on the accelerated path.
            if startprob.sum() > 0:
                self.startprob_ = _normalized(startprob)
        if "t" in self.params:
            transmat = np.maximum(self.transmat_prior - 1 + stats["trans"], 0)
            transmat = np.where(self.transmat_ == 0, 0, transmat)
            # Same rule, per row: a state the data never visited keeps its
            # transitions, exactly as it keeps its emission below. Zeroing the
            # row instead would silently turn an unvisited state into a dead
            # end that no later iteration can leave.
            emptied = transmat.sum(axis=1) == 0
            if emptied.any():
                transmat[emptied] = self.transmat_[emptied]
            self.transmat_ = _normalized(transmat, axis=1)

        # A state can lose all of its posterior mass -- with n_components above
        # what the data supports, that is the normal outcome. Its emission
        # parameters are then undefined (0/0); freeze them instead of letting a
        # nan spread through the next E-step and kill the whole fit.
        alive = stats["post"] > 0
        if not alive.all():
            logger.info(
                "%d of %d states carry no posterior mass; their emission "
                "parameters are held fixed.",
                (~alive).sum(),
                self.n_components,
            )
        denom = stats["post"][:, None]
        if "m" in self.params:
            means = (self.means_weight * self.means_prior + stats["obs"]) / np.maximum(
                self.means_weight + denom, np.finfo(float).tiny
            )
            self.means_ = np.where(alive[:, None], means, self.means_)
        if "c" not in self.params:
            return

        meandiff = self.means_ - self.means_prior
        if self.covariance_type in ("spherical", "diag"):
            c_n = (
                self.means_weight * meandiff**2
                + stats["obs**2"]
                - 2 * self.means_ * stats["obs"]
                + self.means_**2 * denom
            )
            c_d = max(self.covars_weight - 1, 0) + denom
            covars = (self.covars_prior + c_n) / np.maximum(c_d, 1e-5)
            if self.covariance_type == "spherical":
                self.covars_ = np.where(alive, covars.mean(axis=1), self.covars_)
            else:
                self.covars_ = np.where(alive[:, None], covars, self.covars_)
        else:
            c_n = np.empty((self.n_components, self.n_features, self.n_features))
            for c in range(self.n_components):
                obsmean = np.outer(stats["obs"][c], self.means_[c])
                c_n[c] = (
                    self.means_weight * np.outer(meandiff[c], meandiff[c])
                    + stats["obs*obs.T"][c]
                    - obsmean
                    - obsmean.T
                    + np.outer(self.means_[c], self.means_[c]) * stats["post"][c]
                )
            cvweight = max(self.covars_weight - self.n_features, 0)
            if self.covariance_type == "tied":
                self.covars_ = (self.covars_prior + c_n.sum(axis=0)) / max(
                    cvweight + stats["post"].sum(), np.finfo(float).tiny
                )
            else:
                covars = (self.covars_prior + c_n) / np.maximum(
                    cvweight + stats["post"][:, None, None], np.finfo(float).tiny
                )
                self.covars_ = np.where(alive[:, None, None], covars, self.covars_)
