"""Hidden Markov models with Gaussian emissions, fitted by Baum-Welch.

A hidden Markov model describes a sequence of observations
:math:`x_1 \\dots x_T` as generated by an unobserved Markov chain of discrete
states :math:`z_1 \\dots z_T`. It is parameterised by an initial-state
distribution :math:`\\pi_i = P(z_1 = i)`, a transition matrix
:math:`A_{ij} = P(z_{t+1} = j \\mid z_t = i)` and, here, one multivariate normal
emission density per state,

.. math::

    P(x_t \\mid z_t = i) = \\mathcal{N}(x_t; \\mu_i, \\Sigma_i).

ChiSurf uses this for binned single-molecule traces: each time bin carries the
photon counts of one or more detection channels, and the states are the
conformational/photophysical states the molecule dwells in. The state path
recovered by :meth:`GaussianHMM.predict` gives dwell times and a transition
matrix; :meth:`GaussianHMM.bic` selects how many states the data supports.

Everything here is maximum-likelihood: parameters are estimated by the
Baum-Welch (EM) algorithm, with optional conjugate priors that act as
regularisers rather than as a full Bayesian treatment. The variational-Bayes
counterpart used for empirical-Bayes FRET analysis lives in the ebFRET plugin
(``chisurf/plugins/burst/burst_ebfret/core/vbem.py``); the photon-by-photon
variant is H2MM.

The forward-backward recursions run in log space, so long traces do not
underflow, and the time-stepping loops are compiled with numba.

Examples
--------
>>> import numpy as np
>>> from chisurf.core.math.hmm import GaussianHMM
>>> model = GaussianHMM(n_components=2, covariance_type="full", random_state=0)
>>> rng = np.random.default_rng(0)
>>> x = np.concatenate([rng.normal(0, 1, 200), rng.normal(10, 1, 200)])[:, None]
>>> states = model.fit(x).predict(x)
>>> sorted(np.round(model.means_.ravel()))
[0.0, 10.0]

References
----------
.. [1] L. R. Rabiner, "A tutorial on hidden Markov models and selected
       applications in speech recognition", Proc. IEEE 77, 257-286 (1989).
.. [2] X. Huang, A. Acero, H.-W. Hon, "Spoken Language Processing",
       Prentice Hall (2001), pp. 443-445 (MAP re-estimation formulas).
"""

from __future__ import annotations

import logging
import sys
from collections import deque
from typing import Iterator, Sequence

import numba as nb
import numpy as np
from scipy import linalg

__all__ = ["COVARIANCE_TYPES", "ConvergenceMonitor", "GaussianHMM"]

logger = logging.getLogger(__name__)

#: Emission covariance parameterisations understood by :class:`GaussianHMM`.
COVARIANCE_TYPES = ("spherical", "diag", "full", "tied")

#: A SQUAREM cycle costs three EM maps. It is counted as wasted when it gains
#: less than this multiple of the cycle's own first EM step -- EM gains shrink
#: as the fixed point nears, so plain maps could not have done better either.
SQUAREM_MIN_GAIN_FACTOR = 1.0

#: Number of consecutive wasted cycles after which acceleration is abandoned and
#: the remaining budget is spent on plain EM. Kept high: acceleration routinely
#: spends a few modest cycles before a large jump.
SQUAREM_PATIENCE = 4


# ---------------------------------------------------------------------------
# compiled kernels
# ---------------------------------------------------------------------------


@nb.jit(nopython=True, nogil=True, fastmath=True)
def _logsumexp(values: np.ndarray) -> float:
    """Return ``log(sum(exp(values)))`` computed without overflow."""
    vmax = -np.inf
    for i in range(values.shape[0]):
        if values[i] > vmax:
            vmax = values[i]
    if vmax == -np.inf:
        return -np.inf
    acc = 0.0
    for i in range(values.shape[0]):
        acc += np.exp(values[i] - vmax)
    return np.log(acc) + vmax


@nb.jit(nopython=True, nogil=True, fastmath=True)
def _forward_log(
    log_startprob: np.ndarray,
    log_transmat: np.ndarray,
    log_frameprob: np.ndarray,
    fwd: np.ndarray,
) -> float:
    """Fill ``fwd`` with the log forward lattice and return the log-likelihood.

    ``fwd[t, i]`` is :math:`\\log P(x_1 \\dots x_t, z_t = i)`.
    """
    n_samples, n_components = log_frameprob.shape
    work = np.empty(n_components)
    for j in range(n_components):
        fwd[0, j] = log_startprob[j] + log_frameprob[0, j]
    for t in range(1, n_samples):
        for j in range(n_components):
            for i in range(n_components):
                work[i] = fwd[t - 1, i] + log_transmat[i, j]
            fwd[t, j] = _logsumexp(work) + log_frameprob[t, j]
    return _logsumexp(fwd[n_samples - 1])


@nb.jit(nopython=True, nogil=True, fastmath=True)
def _backward_log(
    log_transmat: np.ndarray,
    log_frameprob: np.ndarray,
    bwd: np.ndarray,
) -> None:
    """Fill ``bwd`` with the log backward lattice.

    ``bwd[t, i]`` is :math:`\\log P(x_{t+1} \\dots x_T \\mid z_t = i)`. Kept as a
    standalone recursion for testing; the E-step uses
    :func:`_backward_posteriors_xi`, which folds this into a single sweep.
    """
    n_samples, n_components = log_frameprob.shape
    work = np.empty(n_components)
    for i in range(n_components):
        bwd[n_samples - 1, i] = 0.0
    for t in range(n_samples - 2, -1, -1):
        for i in range(n_components):
            for j in range(n_components):
                work[j] = log_transmat[i, j] + log_frameprob[t + 1, j] + bwd[t + 1, j]
            bwd[t, i] = _logsumexp(work)


@nb.jit(nopython=True, nogil=True, fastmath=True)
def _backward_posteriors_xi(
    log_transmat: np.ndarray,
    log_frameprob: np.ndarray,
    fwd: np.ndarray,
    log_prob: float,
    posteriors: np.ndarray,
    xi_sum: np.ndarray,
) -> None:
    """Sweep backwards once, filling ``posteriors`` and accumulating ``xi_sum``.

    Backward lattice, state posteriors and expected transition counts all need
    the same quantity :math:`\\log a_{ij} + \\log b_j(x_{t+1}) + \\beta_{t+1}(j)`.
    Computing it once and exponentiating it once -- rather than running three
    passes over the lattice -- is what makes the E-step here cheaper than the
    textbook arrangement, and it keeps only two rows of the backward lattice
    alive instead of the whole ``(n_samples, n_components)`` array.

    A frame that no state can explain gets a uniform posterior; its ``-inf``
    entries would otherwise turn into ``nan`` on normalisation.
    """
    n_samples, n_components = log_frameprob.shape
    bwd_next = np.zeros(n_components)
    bwd_current = np.empty(n_components)
    work = np.empty(n_components)
    uniform = 1.0 / n_components

    total = 0.0
    for j in range(n_components):
        posteriors[n_samples - 1, j] = np.exp(fwd[n_samples - 1, j] - log_prob)
        total += posteriors[n_samples - 1, j]
    for j in range(n_components):
        posteriors[n_samples - 1, j] = (
            posteriors[n_samples - 1, j] / total if total > 0.0 else uniform
        )

    for t in range(n_samples - 2, -1, -1):
        for i in range(n_components):
            maximum = -np.inf
            for j in range(n_components):
                value = log_transmat[i, j] + log_frameprob[t + 1, j] + bwd_next[j]
                work[j] = value
                if value > maximum:
                    maximum = value
            if maximum == -np.inf:
                bwd_current[i] = -np.inf
                continue
            # exp(work - maximum) serves both the log-sum-exp below and the
            # transition counts, which differ from it by a constant factor.
            accumulated = 0.0
            scale = np.exp(maximum + fwd[t, i] - log_prob)
            for j in range(n_components):
                shifted = np.exp(work[j] - maximum)
                accumulated += shifted
                xi_sum[i, j] += shifted * scale
            bwd_current[i] = np.log(accumulated) + maximum

        total = 0.0
        for j in range(n_components):
            posteriors[t, j] = np.exp(fwd[t, j] + bwd_current[j] - log_prob)
            total += posteriors[t, j]
        for j in range(n_components):
            posteriors[t, j] = posteriors[t, j] / total if total > 0.0 else uniform

        for j in range(n_components):
            bwd_next[j] = bwd_current[j]


@nb.jit(nopython=True, nogil=True, fastmath=True)
def _viterbi(
    log_startprob: np.ndarray,
    log_transmat: np.ndarray,
    log_frameprob: np.ndarray,
    state_sequence: np.ndarray,
) -> float:
    """Fill ``state_sequence`` with the most probable path and return its log-probability."""
    n_samples, n_components = log_frameprob.shape
    delta = np.empty((n_samples, n_components))
    psi = np.zeros((n_samples, n_components), dtype=np.int64)
    for j in range(n_components):
        delta[0, j] = log_startprob[j] + log_frameprob[0, j]
    for t in range(1, n_samples):
        for j in range(n_components):
            best = -np.inf
            best_i = 0
            for i in range(n_components):
                score = delta[t - 1, i] + log_transmat[i, j]
                if score > best:
                    best = score
                    best_i = i
            delta[t, j] = best + log_frameprob[t, j]
            psi[t, j] = best_i
    best = -np.inf
    best_i = 0
    for j in range(n_components):
        if delta[n_samples - 1, j] > best:
            best = delta[n_samples - 1, j]
            best_i = j
    state_sequence[n_samples - 1] = best_i
    for t in range(n_samples - 2, -1, -1):
        state_sequence[t] = psi[t + 1, state_sequence[t + 1]]
    return best


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------


def _normalized(a: np.ndarray, axis: int | None = None) -> np.ndarray:
    """Return ``a`` scaled so that it sums to one along ``axis``.

    Sums of zero are left as zero rows rather than producing ``nan``.
    """
    a = np.asarray(a, dtype=float)
    total = a.sum(axis=axis, keepdims=axis is not None)
    total = np.where(total == 0, 1.0, total)
    return a / total


def _check_random_state(seed) -> np.random.Generator:
    """Turn ``seed`` (``None``, an int, or a generator) into a :class:`numpy.random.Generator`."""
    if seed is None or isinstance(seed, (int, np.integer)):
        return np.random.default_rng(seed)
    if isinstance(seed, np.random.Generator):
        return seed
    if isinstance(seed, np.random.RandomState):
        return np.random.default_rng(seed.randint(0, 2**32 - 1))
    raise ValueError(f"{seed!r} cannot be used to seed a random number generator")


def _split_sequences(X: np.ndarray, lengths: Sequence[int] | None) -> Iterator[np.ndarray]:
    """Yield the individual sequences packed row-wise into ``X``."""
    if lengths is None:
        yield X
        return
    ends = np.cumsum(np.asarray(lengths, dtype=int))
    if ends[-1] != len(X):
        raise ValueError(f"lengths sum to {ends[-1]} but X has {len(X)} samples")
    starts = np.concatenate([[0], ends[:-1]])
    for start, end in zip(starts, ends):
        yield X[start:end]


def _log_gaussian_density(
    X: np.ndarray,
    means: np.ndarray,
    covars: np.ndarray,
    covariance_type: str,
    min_covar: float = 1e-7,
) -> np.ndarray:
    """Evaluate the log emission density of every state at every sample.

    Parameters
    ----------
    X : numpy.ndarray
        Samples, shape ``(n_samples, n_features)``.
    means : numpy.ndarray
        State means, shape ``(n_components, n_features)``.
    covars : numpy.ndarray
        Covariances in the compact layout of ``covariance_type`` (see
        :attr:`GaussianHMM.covars_`).
    covariance_type : str
        One of :data:`COVARIANCE_TYPES`.
    min_covar : float
        Ridge added to a full covariance that is not positive definite, as a
        last attempt before giving up.

    Returns
    -------
    numpy.ndarray
        Log densities, shape ``(n_samples, n_components)``.
    """
    n_components, n_features = means.shape
    if covariance_type == "spherical":
        covars = np.repeat(np.asarray(covars)[:, None], n_features, axis=1)
        covariance_type = "diag"
    if covariance_type == "diag":
        # Guard the degenerate covariance case against 0 * log 0 = nan.
        covars = np.maximum(covars, np.finfo(float).tiny)
        with np.errstate(over="ignore"):
            return -0.5 * (
                n_features * np.log(2 * np.pi)
                + np.log(covars).sum(axis=-1)
                + ((X[:, None, :] - means) ** 2 / covars).sum(axis=-1)
            )
    if covariance_type == "tied":
        covars = np.broadcast_to(covars, (n_components, n_features, n_features))
    log_prob = np.empty((len(X), n_components))
    for c, (mu, cv) in enumerate(zip(means, covars)):
        try:
            cv_chol = linalg.cholesky(cv, lower=True)
        except linalg.LinAlgError:
            # A state that captured too few samples can go singular; nudge it.
            try:
                cv_chol = linalg.cholesky(cv + min_covar * np.eye(n_features), lower=True)
            except linalg.LinAlgError as err:
                raise ValueError("covariances must be symmetric positive-definite") from err
        cv_log_det = 2 * np.sum(np.log(np.diagonal(cv_chol)))
        cv_sol = linalg.solve_triangular(cv_chol, (X - mu).T, lower=True).T
        log_prob[:, c] = -0.5 * (
            n_features * np.log(2 * np.pi) + (cv_sol**2).sum(axis=1) + cv_log_det
        )
    return log_prob


@nb.jit(nopython=True, nogil=True, fastmath=True)
def _squared_distances(X: np.ndarray, center: np.ndarray, out: np.ndarray) -> None:
    """Fill ``out`` with the squared distance from every row of ``X`` to ``center``."""
    n_samples, n_features = X.shape
    for t in range(n_samples):
        acc = 0.0
        for j in range(n_features):
            diff = X[t, j] - center[j]
            acc += diff * diff
        out[t] = acc


@nb.jit(nopython=True, nogil=True, fastmath=True)
def _kmeanspp_seed(X: np.ndarray, n_clusters: int, uniforms: np.ndarray) -> np.ndarray:
    """Choose ``n_clusters`` initial centres with the greedy k-means++ rule.

    Each further centre is sampled from the data with a probability
    proportional to its squared distance from the closest centre chosen so far.
    Several candidates are drawn per centre and the one that lowers the total
    squared distance the most is kept -- the greedy variant, which is markedly
    less likely to strand a centre than taking the first draw. ``uniforms``
    supplies the pre-drawn variates, so the caller keeps control of the random
    stream.
    """
    n_samples, n_features = X.shape
    n_trials = uniforms.shape[0] // n_clusters
    centers = np.empty((n_clusters, n_features))
    index = min(int(uniforms[0] * n_samples), n_samples - 1)
    centers[0] = X[index]
    closest = np.empty(n_samples)
    _squared_distances(X, centers[0], closest)
    candidate = np.empty(n_samples)
    for c in range(1, n_clusters):
        total = 0.0
        for t in range(n_samples):
            total += closest[t]
        best_potential = np.inf
        best_index = -1
        for trial in range(n_trials):
            uniform = uniforms[c * n_trials + trial]
            if total <= 0.0:
                index = min(int(uniform * n_samples), n_samples - 1)
            else:
                target = uniform * total
                acc = 0.0
                index = n_samples - 1
                for t in range(n_samples):
                    acc += closest[t]
                    if acc >= target:
                        index = t
                        break
            _squared_distances(X, X[index], candidate)
            potential = 0.0
            for t in range(n_samples):
                potential += min(candidate[t], closest[t])
            if potential < best_potential:
                best_potential = potential
                best_index = index
        centers[c] = X[best_index]
        _squared_distances(X, centers[c], candidate)
        for t in range(n_samples):
            if candidate[t] < closest[t]:
                closest[t] = candidate[t]
    return centers


@nb.jit(nopython=True, nogil=True, fastmath=True)
def _kmeans_lloyd(
    X: np.ndarray, centers: np.ndarray, labels: np.ndarray, max_iter: int, tol: float
) -> float:
    """Run Lloyd's algorithm in place on ``centers``/``labels``, returning the inertia.

    Assignment and centroid accumulation share one pass over the samples, so no
    ``(n_samples, n_clusters)`` distance matrix is ever materialised.
    """
    n_samples, n_features = X.shape
    n_clusters = centers.shape[0]
    labels[:] = -1
    sums = np.empty((n_clusters, n_features))
    counts = np.empty(n_clusters)
    inertia = 0.0
    for _ in range(max_iter):
        sums[:, :] = 0.0
        counts[:] = 0.0
        inertia = 0.0
        n_changed = 0
        worst_distance = -1.0
        worst_index = 0
        for t in range(n_samples):
            best = np.inf
            best_c = 0
            for c in range(n_clusters):
                acc = 0.0
                for j in range(n_features):
                    diff = X[t, j] - centers[c, j]
                    acc += diff * diff
                if acc < best:
                    best = acc
                    best_c = c
            if labels[t] != best_c:
                labels[t] = best_c
                n_changed += 1
            inertia += best
            counts[best_c] += 1.0
            for j in range(n_features):
                sums[best_c, j] += X[t, j]
            if best > worst_distance:
                worst_distance = best
                worst_index = t
        shift = 0.0
        for c in range(n_clusters):
            if counts[c] > 0.0:
                for j in range(n_features):
                    updated = sums[c, j] / counts[c]
                    diff = updated - centers[c, j]
                    shift += diff * diff
                    centers[c, j] = updated
            else:
                # Re-seed an emptied cluster on the worst-explained sample.
                for j in range(n_features):
                    centers[c, j] = X[worst_index, j]
                shift += tol + 1.0
        if n_changed == 0 or shift <= tol * tol:
            break
    return inertia


def _kmeans(
    X: np.ndarray,
    n_clusters: int,
    random_state: np.random.Generator,
    n_init: int = 10,
    max_iter: int = 300,
    tol: float = 1e-4,
) -> tuple[np.ndarray, np.ndarray]:
    """Cluster ``X`` with k-means++ seeded Lloyd iterations.

    Used to place the initial state means *and* -- through the labels it
    returns -- the initial transitions and covariances. The EM iterations take
    over from there, so a plain implementation is enough, and it keeps this
    module free of a machine-learning dependency.

    Parameters
    ----------
    X : numpy.ndarray
        Samples, shape ``(n_samples, n_features)``.
    n_clusters : int
        Number of centres to place.
    random_state : numpy.random.Generator
        Source of randomness for the seeding.
    n_init : int
        Number of restarts; the run with the lowest inertia wins.
    max_iter : int
        Maximum Lloyd iterations per restart.
    tol : float
        Stop a restart once the centres move less than this (Frobenius norm).

    Returns
    -------
    centers : numpy.ndarray
        Cluster centres, shape ``(n_clusters, n_features)``.
    labels : numpy.ndarray
        Index of the closest centre per sample, shape ``(n_samples, )``.
    """
    X = np.ascontiguousarray(X, dtype=float)
    n_samples = len(X)
    if n_samples <= n_clusters:
        centers = np.repeat(X.mean(axis=0)[None, :], n_clusters, axis=0)
        centers[:n_samples] = X
        return centers, np.arange(n_samples) % n_clusters

    # Candidates per centre for the greedy seeding, as in the reference
    # implementations: enough to matter, few enough to stay cheap.
    n_trials = 2 + int(np.log(n_clusters))
    labels = np.empty(n_samples, dtype=np.int64)
    best, best_inertia = None, np.inf
    for _ in range(n_init):
        centers = _kmeanspp_seed(
            X, n_clusters, random_state.random(n_clusters * n_trials)
        )
        inertia = _kmeans_lloyd(X, centers, labels, max_iter, tol)
        if inertia < best_inertia:
            best, best_inertia = (centers, labels.copy()), inertia
    return best


def _project_simplexes(
    theta: np.ndarray, reference: np.ndarray, n_components: int
) -> np.ndarray:
    """Return ``theta`` with its probability blocks projected back onto the simplex.

    Clipping alone would turn an overshot probability into a hard zero, and a
    zero is permanent: the M-step keeps it, so that a state a constrained model
    is allowed to reach could silently become unreachable. Anything positive in
    ``reference`` therefore keeps a floor. The remaining blocks -- means, and
    covariances in the unconstrained space of :func:`_covars_to_free` -- are
    feasible for any real value and pass through.
    """
    theta = theta.copy()
    n_probabilities = n_components + n_components * n_components
    blocks = theta[:n_probabilities]
    np.clip(blocks, 0.0, None, out=blocks)
    floor = np.finfo(float).eps / n_components
    np.copyto(blocks, floor, where=(blocks <= 0) & (reference[:n_probabilities] > 0))
    # The start distribution and every transition row share the same treatment.
    rows = blocks.reshape(n_components + 1, n_components)
    # A block that the extrapolation emptied carries no information; spread it.
    rows[rows.sum(axis=1) == 0] = 1.0 / n_components
    theta[:n_probabilities] = _normalized(rows, axis=1).ravel()
    return theta


def _covars_to_free(covars: np.ndarray, covariance_type: str) -> np.ndarray:
    """Map covariances to an unconstrained vector for SQUAREM extrapolation.

    Variances become log-variances and matrices become their lower Cholesky
    factor with a log-diagonal, so that *any* real vector maps back to a valid
    positive-definite covariance.
    """
    if covariance_type in ("spherical", "diag"):
        return np.log(np.maximum(covars, np.finfo(float).tiny)).ravel()
    matrices = covars if covariance_type == "full" else covars[None]
    try:
        chol = np.linalg.cholesky(matrices)
    except np.linalg.LinAlgError:
        # A state that captured almost no samples can lose definiteness; a
        # ridge keeps the extrapolation going instead of aborting the fit.
        n_features = matrices.shape[-1]
        ridge = 1e-6 * np.trace(matrices, axis1=1, axis2=2).max() / n_features
        logger.debug("Ridging a non positive-definite covariance by %g", ridge)
        chol = np.linalg.cholesky(matrices + ridge * np.eye(n_features))
    diagonal = np.arange(matrices.shape[-1])
    chol[:, diagonal, diagonal] = np.log(chol[:, diagonal, diagonal])
    return chol.ravel()


def _covars_from_free(
    free: np.ndarray, covariance_type: str, n_components: int, n_features: int
) -> np.ndarray:
    """Invert :func:`_covars_to_free`."""
    if covariance_type == "spherical":
        return np.exp(free)
    if covariance_type == "diag":
        return np.exp(free).reshape(n_components, n_features)
    n_matrices = n_components if covariance_type == "full" else 1
    chol = np.tril(free.reshape(n_matrices, n_features, n_features))
    diagonal = np.arange(n_features)
    chol[:, diagonal, diagonal] = np.exp(chol[:, diagonal, diagonal])
    covars = chol @ chol.transpose(0, 2, 1)
    return covars if covariance_type == "full" else covars[0]


class ConvergenceMonitor:
    """Track the EM log-likelihood and decide when Baum-Welch has converged.

    Parameters
    ----------
    tol : float
        Convergence threshold on the log-likelihood gain between two
        consecutive iterations.
    n_iter : int
        Maximum number of iterations.
    verbose : bool
        Whether to print a per-iteration report to :data:`sys.stderr`.

    Attributes
    ----------
    history : collections.deque
        Log-likelihood of every iteration performed so far.
    iter : int
        Number of iterations performed.
    """

    _template = "{iter:>10d} {log_prob:>16.8f} {delta:>+16.8f}"

    def __init__(self, tol: float, n_iter: int, verbose: bool = False):
        self.tol = tol
        self.n_iter = n_iter
        self.verbose = verbose
        self.history: deque[float] = deque(maxlen=2)
        self.iter = 0

    def __repr__(self) -> str:
        """Return a reproducible representation including the log-likelihood history."""
        return (
            f"{type(self).__name__}(tol={self.tol}, n_iter={self.n_iter}, "
            f"verbose={self.verbose}, history={list(self.history)}, iter={self.iter})"
        )

    def reset(self) -> None:
        """Forget the history of a previous fit."""
        self.iter = 0
        self.history.clear()

    def report(self, log_prob: float) -> None:
        """Record the log-likelihood of the iteration that just finished."""
        if self.verbose:
            delta = log_prob - self.history[-1] if self.history else np.nan
            print(
                self._template.format(iter=self.iter + 1, log_prob=log_prob, delta=delta),
                file=sys.stderr,
            )
        # EM cannot decrease the likelihood; allow only for rounding noise.
        precision = np.finfo(float).eps ** 0.5
        if self.history and (log_prob - self.history[-1]) < -precision:
            logger.warning(
                "HMM is not converging: log-likelihood dropped from %s to %s",
                self.history[-1],
                log_prob,
            )
        self.history.append(log_prob)
        self.iter += 1

    @property
    def converged(self) -> bool:
        """Whether the iteration limit or the tolerance has been reached."""
        return self.iter == self.n_iter or (
            len(self.history) == 2 and self.history[1] - self.history[0] < self.tol
        )


# ---------------------------------------------------------------------------
# model
# ---------------------------------------------------------------------------


class GaussianHMM:
    """Hidden Markov model with multivariate normal emissions.

    Parameters
    ----------
    n_components : int
        Number of hidden states.
    covariance_type : str
        Shape of the emission covariances, one of :data:`COVARIANCE_TYPES`:
        ``"spherical"`` (one variance per state), ``"diag"`` (one variance per
        state and feature), ``"full"`` (an unrestricted matrix per state) or
        ``"tied"`` (one matrix shared by all states).
    min_covar : float
        Ridge added to the empirical covariance when initialising, so that the
        first E-step cannot see a singular matrix.
    startprob_prior, transmat_prior : float or numpy.ndarray
        Dirichlet prior parameters for :attr:`startprob_` and the rows of
        :attr:`transmat_`. A value of one is the uninformative default.
    means_prior, means_weight : float or numpy.ndarray
        Normal prior on the state means; ``means_weight`` is the number of
        pseudo-observations placed at ``means_prior``. Zero disables the prior.
    covars_prior, covars_weight : float or numpy.ndarray
        Inverse-Wishart (or inverse-Gamma, for the diagonal parameterisations)
        prior on the covariances. The default keeps a small floor on the
        variance of a state that captured very few samples.
    algorithm : str
        Decoder used by :meth:`decode` and :meth:`predict`: ``"viterbi"`` for
        the most probable *path*, ``"map"`` for the sequence of individually
        most probable states.
    random_state : int, numpy.random.Generator or None
        Seed for the initial transition/start probabilities and for the k-means
        seeding of the means.
    n_iter : int
        Maximum number of EM maps (with ``accelerate``, a SQUAREM cycle spends
        three of them).
    tol : float
        Convergence threshold on the log-likelihood gain per iteration.
    accelerate : bool
        Accelerate EM with SQUAREM extrapolation (see :meth:`_fit_squarem`).
        The fixed point is the one plain EM converges to; it is simply reached
        in fewer maps. Turn it off to reproduce a textbook Baum-Welch run.
    verbose : bool
        Print the per-iteration log-likelihood to :data:`sys.stderr`.
    params, init_params : str
        Which parameters are re-estimated during :meth:`fit` (``params``) and
        which are initialised before it (``init_params``): ``"s"`` start
        probabilities, ``"t"`` transition matrix, ``"m"`` means, ``"c"``
        covariances. Drop a letter from ``init_params`` to fit from a value you
        set yourself, and from ``params`` to hold that value fixed.

    Attributes
    ----------
    startprob_ : numpy.ndarray
        Initial state distribution, shape ``(n_components, )``.
    transmat_ : numpy.ndarray
        Row-stochastic transition matrix, shape ``(n_components, n_components)``.
        ``transmat_[i, j]`` is the probability of moving from state ``i`` to ``j``.
    means_ : numpy.ndarray
        Emission means, shape ``(n_components, n_features)``.
    covars_ : numpy.ndarray
        Emission covariances in the compact layout of :attr:`covariance_type`:
        ``(n_components, )`` spherical, ``(n_components, n_features)`` diagonal,
        ``(n_components, n_features, n_features)`` full, and
        ``(n_features, n_features)`` tied. :attr:`covars_full_` always gives
        full matrices.
    monitor_ : ConvergenceMonitor
        Convergence state of the last :meth:`fit`.
    n_features : int
        Dimensionality of the emissions, set by the first :meth:`fit`.

    Notes
    -----
    Fitting is the Baum-Welch algorithm [1]_: the E-step runs forward-backward
    in log space to obtain the state posteriors, and the M-step is the MAP
    re-estimation of Huang et al. [2]_ under the priors above. EM finds a local
    optimum, so the initialisation matters -- pass a fixed ``random_state`` for
    reproducible results, and compare :meth:`bic` across ``n_components``
    rather than trusting the likelihood alone, which always prefers more states.
    """

    def __init__(
        self,
        n_components: int = 1,
        covariance_type: str = "diag",
        min_covar: float = 1e-3,
        startprob_prior: float = 1.0,
        transmat_prior: float = 1.0,
        means_prior: float = 0.0,
        means_weight: float = 0.0,
        covars_prior: float = 1e-2,
        covars_weight: float = 1.0,
        algorithm: str = "viterbi",
        random_state=None,
        n_iter: int = 10,
        tol: float = 1e-2,
        verbose: bool = False,
        params: str = "stmc",
        init_params: str = "stmc",
        accelerate: bool = True,
    ):
        if covariance_type not in COVARIANCE_TYPES:
            raise ValueError(f"covariance_type must be one of {COVARIANCE_TYPES}")
        if algorithm not in ("viterbi", "map"):
            raise ValueError("algorithm must be 'viterbi' or 'map'")
        self.n_components = n_components
        self.covariance_type = covariance_type
        self.min_covar = min_covar
        self.startprob_prior = startprob_prior
        self.transmat_prior = transmat_prior
        self.means_prior = means_prior
        self.means_weight = means_weight
        self.covars_prior = covars_prior
        self.covars_weight = covars_weight
        self.algorithm = algorithm
        self.random_state = random_state
        self.n_iter = n_iter
        self.tol = tol
        self.verbose = verbose
        self.params = params
        self.init_params = init_params
        self.accelerate = accelerate
        self.monitor_ = ConvergenceMonitor(tol, n_iter, verbose)
        #: Set by the first call that sees data; guards later shape mismatches.
        self.n_features: int | None = None

    def __repr__(self) -> str:
        """Return the constructor call reproducing this model's configuration."""
        return (
            f"{type(self).__name__}(n_components={self.n_components}, "
            f"covariance_type={self.covariance_type!r}, n_iter={self.n_iter}, "
            f"tol={self.tol})"
        )

    # -- properties ---------------------------------------------------------

    @property
    def covars_full_(self) -> np.ndarray:
        """Emission covariances as full matrices, shape ``(n_components, nf, nf)``."""
        covars = np.asarray(self.covars_)
        if self.covariance_type == "full":
            return covars
        if self.covariance_type == "diag":
            return np.stack([np.diag(c) for c in covars])
        if self.covariance_type == "tied":
            return np.tile(covars, (self.n_components, 1, 1))
        eye = np.eye(self.n_features)[None, :, :]
        return eye * covars.reshape(-1, 1, 1)

    @property
    def n_parameters(self) -> int:
        """Number of free scalar parameters, as counted by :meth:`aic` and :meth:`bic`."""
        nc, nf = self.n_components, self.n_features
        n_covars = {
            "spherical": nc,
            "diag": nc * nf,
            "full": nc * nf * (nf + 1) // 2,
            "tied": nf * (nf + 1) // 2,
        }[self.covariance_type]
        per_param = {"s": nc - 1, "t": nc * (nc - 1), "m": nc * nf, "c": n_covars}
        return sum(per_param[p] for p in self.params if p in per_param)

    # -- fitting ------------------------------------------------------------

    def fit(self, X: np.ndarray, lengths: Sequence[int] | None = None) -> "GaussianHMM":
        """Estimate the model parameters from one or more observation sequences.

        Parameters
        ----------
        X : numpy.ndarray
            Samples, shape ``(n_samples, n_features)``. Several sequences are
            passed stacked row-wise and split by ``lengths``.
        lengths : sequence of int, optional
            Length of each sequence in ``X``; they must sum to ``len(X)``. The
            default treats ``X`` as a single sequence.

        Returns
        -------
        GaussianHMM
            This model, fitted.
        """
        X = self._check_input(X)
        self._init(X, lengths)
        self.monitor_.reset()
        if self.accelerate:
            self._fit_squarem(X, lengths)
        else:
            self._fit_em(X, lengths)
        if (self.transmat_.sum(axis=1) == 0).any():
            logger.warning(
                "Some rows of transmat_ sum to zero: no transition out of those "
                "states was ever observed."
            )
        return self

    def _fit_em(
        self, X: np.ndarray, lengths: Sequence[int] | None, n_maps: int | None = None
    ) -> None:
        """Run plain Baum-Welch for ``n_maps`` maps or until the monitor converges."""
        for _ in range(self.n_iter if n_maps is None else n_maps):
            stats, log_prob = self._do_estep(X, lengths)
            # The M-step runs before the convergence check so that n_iter=1
            # still updates the parameters once.
            self._do_mstep(stats)
            self.monitor_.report(log_prob)
            if self.monitor_.converged:
                break

    def _fit_squarem(self, X: np.ndarray, lengths: Sequence[int] | None) -> None:
        """Run Baum-Welch accelerated by SQUAREM, scheme S3.

        EM is a fixed-point iteration :math:`\\theta \\to F(\\theta)` that
        crawls when the states overlap. SQUAREM [3]_ takes two ordinary maps
        per cycle, forms :math:`r = F(\\theta) - \\theta` and
        :math:`v = F(F(\\theta)) - 2 F(\\theta) + \\theta`, and jumps to
        :math:`\\theta - 2 \\alpha r + \\alpha^2 v` with the steplength
        :math:`\\alpha = -\\lVert r \\rVert / \\lVert v \\rVert`. The
        extrapolated point is projected back onto the feasible set (stochastic
        rows, positive-definite covariances) and kept only if a further EM map
        from it does not lower the likelihood -- so the fixed point is the same
        as plain EM's, reached in fewer maps. The same scheme accelerates the
        photon-by-photon H2MM optimiser.

        References
        ----------
        .. [3] R. Varadhan, C. Roland, "Simple and globally convergent methods
               for accelerating the convergence of any EM algorithm",
               Scand. J. Stat. 35, 335-353 (2008).
        """
        theta = self._get_parameters()
        n_maps = 0
        n_wasted_cycles = 0
        previous_cycle: tuple[float, float] | None = None
        while n_maps < self.n_iter:
            log_prob_0, theta_1 = self._em_map(theta, X, lengths)
            n_maps += 1

            # Judge the cycle that just ended: it spent three maps, and EM gains
            # shrink as the fixed point nears, so a cycle that gains less than
            # its own first EM step did strictly worse than plain EM. Only a
            # long run of those is taken as evidence that extrapolation has
            # nothing left to give on this problem.
            if previous_cycle is not None:
                entry_log_prob, first_gain = previous_cycle
                gain = log_prob_0 - entry_log_prob
                if 0 < first_gain and gain < SQUAREM_MIN_GAIN_FACTOR * first_gain:
                    n_wasted_cycles += 1
                else:
                    n_wasted_cycles = 0
                if n_wasted_cycles >= SQUAREM_PATIENCE:
                    logger.debug(
                        "SQUAREM stopped paying off after %d maps; finishing with plain EM.",
                        n_maps,
                    )
                    self.monitor_.report(log_prob_0)
                    if not self.monitor_.converged:
                        self._fit_em(X, lengths, self.n_iter - n_maps)
                    return

            if n_maps >= self.n_iter:
                self._set_parameters(theta_1)
                self.monitor_.report(log_prob_0)
                break

            r = theta_1 - theta
            log_prob_1, theta_2 = self._em_map(theta_1, X, lengths)
            n_maps += 1
            previous_cycle = (log_prob_0, log_prob_1 - log_prob_0)
            v = (theta_2 - theta_1) - r
            r_norm, v_norm = np.linalg.norm(r), np.linalg.norm(v)

            accepted, log_prob = theta_2, log_prob_1
            if min(r_norm, v_norm) > 1e-12 and n_maps < self.n_iter:
                # alpha is negative; -1 is the plain-EM step, so never take a
                # shorter one than that.
                alpha = min(-r_norm / v_norm, -1.0)
                candidate = _project_simplexes(
                    theta - 2 * alpha * r + alpha**2 * v, theta, self.n_components
                )
                try:
                    log_prob_2, theta_3 = self._em_map(candidate, X, lengths)
                    n_maps += 1
                except (ValueError, np.linalg.LinAlgError, linalg.LinAlgError):
                    # An extrapolation that left the feasible set is simply not
                    # taken; the plain-EM point below is always available.
                    log_prob_2 = -np.inf
                if np.isfinite(log_prob_2) and log_prob_2 >= log_prob_1:
                    accepted, log_prob = theta_3, log_prob_2

            theta = accepted
            self._set_parameters(theta)
            self.monitor_.report(log_prob)
            if self.monitor_.converged:
                break

    def _em_map(
        self, theta: np.ndarray, X: np.ndarray, lengths: Sequence[int] | None
    ) -> tuple[float, np.ndarray]:
        """Apply one EM map to ``theta``, returning its log-likelihood and the image."""
        self._set_parameters(theta)
        stats, log_prob = self._do_estep(X, lengths)
        self._do_mstep(stats)
        return log_prob, self._get_parameters()

    def _get_parameters(self) -> np.ndarray:
        """Pack the parameters into one vector, covariances in unconstrained space."""
        return np.concatenate(
            [
                self.startprob_.ravel(),
                self.transmat_.ravel(),
                self.means_.ravel(),
                _covars_to_free(self.covars_, self.covariance_type),
            ]
        )

    def _set_parameters(self, theta: np.ndarray) -> None:
        """Unpack a vector produced by :meth:`_get_parameters` into the model."""
        nc, nf = self.n_components, self.n_features
        self.startprob_ = theta[:nc].copy()
        self.transmat_ = theta[nc : nc + nc * nc].reshape(nc, nc).copy()
        offset = nc + nc * nc
        self.means_ = theta[offset : offset + nc * nf].reshape(nc, nf).copy()
        self.covars_ = _covars_from_free(
            theta[offset + nc * nf :], self.covariance_type, nc, nf
        )

    def score(self, X: np.ndarray, lengths: Sequence[int] | None = None) -> float:
        """Return the log-likelihood of ``X`` under the model.

        Parameters
        ----------
        X : numpy.ndarray
            Samples, shape ``(n_samples, n_features)``.
        lengths : sequence of int, optional
            Length of each sequence in ``X``.

        Returns
        -------
        float
            :math:`\\log P(X \\mid \\theta)`, summed over the sequences.
        """
        X = self._check_input(X)
        log_prob = 0.0
        for sequence in _split_sequences(X, lengths):
            log_frameprob = self._compute_log_likelihood(sequence)
            fwd = np.empty_like(log_frameprob)
            log_prob += _forward_log(
                self._log_startprob, self._log_transmat, log_frameprob, fwd
            )
        return log_prob

    def score_samples(
        self, X: np.ndarray, lengths: Sequence[int] | None = None
    ) -> tuple[float, np.ndarray]:
        """Return the log-likelihood of ``X`` and the per-sample state posteriors.

        Parameters
        ----------
        X : numpy.ndarray
            Samples, shape ``(n_samples, n_features)``.
        lengths : sequence of int, optional
            Length of each sequence in ``X``.

        Returns
        -------
        log_prob : float
            Log-likelihood of ``X``.
        posteriors : numpy.ndarray
            :math:`P(z_t = i \\mid X)`, shape ``(n_samples, n_components)``.
        """
        X = self._check_input(X)
        log_prob = 0.0
        posteriors = []
        for sequence in _split_sequences(X, lengths):
            sub_log_prob, sub_posteriors = self._forward_backward(sequence)
            log_prob += sub_log_prob
            posteriors.append(sub_posteriors)
        return log_prob, np.concatenate(posteriors)

    def predict_proba(
        self, X: np.ndarray, lengths: Sequence[int] | None = None
    ) -> np.ndarray:
        """Return the posterior state probabilities of every sample.

        Parameters
        ----------
        X : numpy.ndarray
            Samples, shape ``(n_samples, n_features)``.
        lengths : sequence of int, optional
            Length of each sequence in ``X``.

        Returns
        -------
        numpy.ndarray
            Posteriors, shape ``(n_samples, n_components)``.
        """
        return self.score_samples(X, lengths)[1]

    def decode(
        self,
        X: np.ndarray,
        lengths: Sequence[int] | None = None,
        algorithm: str | None = None,
    ) -> tuple[float, np.ndarray]:
        """Infer the hidden state sequence of ``X``.

        Parameters
        ----------
        X : numpy.ndarray
            Samples, shape ``(n_samples, n_features)``.
        lengths : sequence of int, optional
            Length of each sequence in ``X``.
        algorithm : str, optional
            Override :attr:`algorithm` for this call.

        Returns
        -------
        log_prob : float
            Log-probability of the returned path (``"viterbi"``) or of the data
            (``"map"``).
        state_sequence : numpy.ndarray
            State index per sample, shape ``(n_samples, )``.
        """
        algorithm = algorithm or self.algorithm
        if algorithm not in ("viterbi", "map"):
            raise ValueError("algorithm must be 'viterbi' or 'map'")
        X = self._check_input(X)
        log_prob = 0.0
        states = []
        for sequence in _split_sequences(X, lengths):
            log_frameprob = self._compute_log_likelihood(sequence)
            if algorithm == "viterbi":
                sub_states = np.empty(len(sequence), dtype=np.int64)
                log_prob += _viterbi(
                    self._log_startprob, self._log_transmat, log_frameprob, sub_states
                )
            else:
                sub_log_prob, posteriors = self._forward_backward(sequence)
                log_prob += sub_log_prob
                sub_states = posteriors.argmax(axis=1)
            states.append(sub_states)
        return log_prob, np.concatenate(states)

    def predict(self, X: np.ndarray, lengths: Sequence[int] | None = None) -> np.ndarray:
        """Return the inferred state sequence of ``X``, shape ``(n_samples, )``."""
        return self.decode(X, lengths)[1]

    def sample(
        self, n_samples: int = 1, random_state=None, currstate: int | None = None
    ) -> tuple[np.ndarray, np.ndarray]:
        """Draw a sequence of observations and states from the model.

        Parameters
        ----------
        n_samples : int
            Number of samples to draw.
        random_state : int, numpy.random.Generator or None
            Seed; defaults to :attr:`random_state`.
        currstate : int, optional
            State to start from; drawn from :attr:`startprob_` by default.

        Returns
        -------
        X : numpy.ndarray
            Samples, shape ``(n_samples, n_features)``.
        state_sequence : numpy.ndarray
            The generating states, shape ``(n_samples, )``.
        """
        rng = _check_random_state(random_state if random_state is not None else self.random_state)
        covars = self.covars_full_
        states = np.empty(n_samples, dtype=int)
        states[0] = rng.choice(self.n_components, p=self.startprob_) if currstate is None \
            else currstate
        for t in range(1, n_samples):
            states[t] = rng.choice(self.n_components, p=self.transmat_[states[t - 1]])
        X = np.stack(
            [rng.multivariate_normal(self.means_[s], covars[s]) for s in states]
        )
        return X, states

    def aic(self, X: np.ndarray, lengths: Sequence[int] | None = None) -> float:
        """Return the Akaike information criterion, ``-2 logL + 2 k`` (lower is better)."""
        return -2 * self.score(X, lengths) + 2 * self.n_parameters

    def bic(self, X: np.ndarray, lengths: Sequence[int] | None = None) -> float:
        """Return the Bayesian information criterion, ``-2 logL + k log n`` (lower is better)."""
        return -2 * self.score(X, lengths) + self.n_parameters * np.log(len(X))

    def get_stationary_distribution(self) -> np.ndarray:
        """Return the stationary distribution of :attr:`transmat_`.

        Returns
        -------
        numpy.ndarray
            The normalised left eigenvector of the transition matrix belonging
            to eigenvalue one, shape ``(n_components, )``.
        """
        eigvals, eigvecs = linalg.eig(self.transmat_.T)
        eigvec = np.real_if_close(eigvecs[:, np.argmax(eigvals)])
        return eigvec / eigvec.sum()

    # -- internals ----------------------------------------------------------

    def _check_input(self, X: np.ndarray) -> np.ndarray:
        """Validate ``X`` and return it as a 2-D float array."""
        X = np.asarray(X, dtype=float)
        if X.ndim == 1:
            X = X[:, None]
        if X.ndim != 2:
            raise ValueError(f"X must be 2-dimensional, got shape {X.shape}")
        if not np.isfinite(X).all():
            raise ValueError("X must not contain NaN or infinite values")
        n_features = X.shape[1]
        if getattr(self, "n_features", None) is None:
            self.n_features = n_features
        elif self.n_features != n_features:
            raise ValueError(
                f"X has {n_features} features but the model was fitted with {self.n_features}"
            )
        return X

    def _needs_init(self, code: str, name: str) -> bool:
        """Whether parameter ``name``, selected by ``code``, must be initialised."""
        return code in self.init_params or not hasattr(self, name)

    def _init(self, X: np.ndarray, lengths: Sequence[int] | None = None) -> None:
        """Initialise the parameters selected by :attr:`init_params` from ``X``.

        Every parameter is derived from one k-means clustering, read as a first,
        hard-assignment guess at the state path: the centres are the means, the
        per-cluster scatter is the covariance, and the label sequence supplies
        the transition counts and the state occupancies. That is a far better
        starting point for a *time series* than the usual random draw, which
        ignores the data entirely -- it converges in fewer EM steps, and it
        cannot hand EM a transition of exactly zero, which the M-step would then
        preserve forever and so make a state permanently unreachable.
        """
        rng = _check_random_state(self.random_state)
        uniform = 1.0 / self.n_components
        needs = {code: self._needs_init(code, name) for code, name in
                 (("s", "startprob_"), ("t", "transmat_"), ("m", "means_"), ("c", "covars_"))}

        centers, labels = (None, None)
        if any(needs.values()):
            centers, labels = _kmeans(X, self.n_components, rng)

        if needs["m"]:
            self.means_ = centers
        if needs["s"]:
            # Occupancy of each cluster, smoothed so that no state starts out
            # unreachable.
            counts = np.bincount(labels, minlength=self.n_components) + 1.0
            self.startprob_ = counts / counts.sum()
        if needs["t"]:
            # Transitions between consecutive labels, counted within sequences.
            counts = np.full((self.n_components, self.n_components), uniform)
            for sequence in _split_sequences(labels[:, None], lengths):
                path = sequence.ravel()
                if len(path) > 1:
                    np.add.at(counts, (path[:-1], path[1:]), 1.0)
            self.transmat_ = counts / counts.sum(axis=1, keepdims=True)
        if needs["c"]:
            self.covars_ = self._initial_covariances(X, labels)

        n_fit_scalars = self.n_parameters
        if X.size < n_fit_scalars:
            logger.warning(
                "Fitting %d free parameters to %d data points gives a degenerate solution.",
                n_fit_scalars,
                X.size,
            )
        self._check_parameters()

    def _initial_covariances(self, X: np.ndarray, labels: np.ndarray) -> np.ndarray:
        """Return the per-cluster covariances in the layout of :attr:`covariance_type`.

        A cluster too small to define a covariance falls back to the covariance
        of the whole data set, which is the widest sensible guess.
        """
        ridge = self.min_covar * np.eye(self.n_features)
        pooled = np.atleast_2d(np.cov(X.T)) + ridge
        matrices = np.empty((self.n_components, self.n_features, self.n_features))
        for c in range(self.n_components):
            members = X[labels == c]
            matrices[c] = np.atleast_2d(np.cov(members.T)) + ridge if len(members) > \
                self.n_features else pooled
        if self.covariance_type == "full":
            return matrices
        if self.covariance_type == "tied":
            return pooled
        variances = np.diagonal(matrices, axis1=1, axis2=2)
        return variances.mean(axis=1) if self.covariance_type == "spherical" else variances.copy()

    def _check_parameters(self) -> None:
        """Validate the current parameters, as an E-step is about to consume them."""
        self.startprob_ = np.asarray(self.startprob_, dtype=float)
        if self.startprob_.shape != (self.n_components,):
            raise ValueError("startprob_ must have shape (n_components, )")
        if not np.isclose(self.startprob_.sum(), 1):
            raise ValueError(f"startprob_ must sum to 1 (got {self.startprob_.sum():.4f})")
        self.transmat_ = np.asarray(self.transmat_, dtype=float)
        if self.transmat_.shape != (self.n_components, self.n_components):
            raise ValueError("transmat_ must have shape (n_components, n_components)")
        if not np.allclose(self.transmat_.sum(axis=1), 1):
            raise ValueError(
                f"transmat_ rows must sum to 1 (got {self.transmat_.sum(axis=1)})"
            )
        self.means_ = np.asarray(self.means_, dtype=float)
        if self.means_.shape != (self.n_components, self.n_features):
            raise ValueError("means_ must have shape (n_components, n_features)")
        self.covars_ = np.asarray(self.covars_, dtype=float)
        expected = {
            "spherical": (self.n_components,),
            "diag": (self.n_components, self.n_features),
            "full": (self.n_components, self.n_features, self.n_features),
            "tied": (self.n_features, self.n_features),
        }[self.covariance_type]
        if self.covars_.shape != expected:
            raise ValueError(
                f"covars_ must have shape {expected} for covariance_type "
                f"{self.covariance_type!r}, got {self.covars_.shape}"
            )

    @property
    def _log_startprob(self) -> np.ndarray:
        """Element-wise logarithm of :attr:`startprob_`, with zeros mapped to ``-inf``."""
        with np.errstate(divide="ignore"):
            return np.log(self.startprob_)

    @property
    def _log_transmat(self) -> np.ndarray:
        """Element-wise logarithm of :attr:`transmat_`, with zeros mapped to ``-inf``."""
        with np.errstate(divide="ignore"):
            return np.log(self.transmat_)

    def _compute_log_likelihood(self, X: np.ndarray) -> np.ndarray:
        """Return the per-sample, per-state log emission densities of ``X``."""
        return _log_gaussian_density(X, self.means_, self.covars_, self.covariance_type)

    def _forward_backward(
        self, X: np.ndarray, xi_sum: np.ndarray | None = None
    ) -> tuple[float, np.ndarray]:
        """Run forward-backward on one sequence.

        Parameters
        ----------
        X : numpy.ndarray
            One observation sequence, shape ``(n_samples, n_features)``.
        xi_sum : numpy.ndarray, optional
            ``(n_components, n_components)`` accumulator that the expected
            transition counts are *added* to. Omit it when only the posteriors
            are wanted, as in decoding.

        Returns
        -------
        log_prob : float
            Log-likelihood of the sequence.
        posteriors : numpy.ndarray
            State posteriors, shape ``(n_samples, n_components)``.
        """
        log_frameprob = self._compute_log_likelihood(X)
        fwd = np.empty_like(log_frameprob)
        posteriors = np.empty_like(log_frameprob)
        log_prob = _forward_log(self._log_startprob, self._log_transmat, log_frameprob, fwd)
        if xi_sum is None:
            xi_sum = np.zeros((self.n_components, self.n_components))
        _backward_posteriors_xi(
            self._log_transmat, log_frameprob, fwd, log_prob, posteriors, xi_sum
        )
        return log_prob, posteriors

    def _do_estep(
        self, X: np.ndarray, lengths: Sequence[int] | None
    ) -> tuple[dict, float]:
        """Accumulate the sufficient statistics of all sequences and their log-likelihood."""
        nc, nf = self.n_components, self.n_features
        stats = {
            "nobs": 0,
            "start": np.zeros(nc),
            "trans": np.zeros((nc, nc)),
            "post": np.zeros(nc),
            "obs": np.zeros((nc, nf)),
            "obs**2": np.zeros((nc, nf)),
            "obs*obs.T": np.zeros((nc, nf, nf)),
        }
        total_log_prob = 0.0
        for sequence in _split_sequences(X, lengths):
            # A single-sample sequence contains no transition to count; the
            # kernel simply adds nothing to the accumulator.
            log_prob, posteriors = self._forward_backward(sequence, stats["trans"])
            total_log_prob += log_prob
            stats["nobs"] += 1
            stats["start"] += posteriors[0]
            stats["post"] += posteriors.sum(axis=0)
            stats["obs"] += posteriors.T @ sequence
            if self.covariance_type in ("spherical", "diag"):
                stats["obs**2"] += posteriors.T @ sequence**2
            else:
                # One BLAS product per state rather than a single einsum: the
                # einsum path is not blocked and costs an order of magnitude more.
                for c in range(nc):
                    stats["obs*obs.T"][c] += (sequence * posteriors[:, c, None]).T @ sequence
        return stats, total_log_prob

    def _do_mstep(self, stats: dict) -> None:
        """Re-estimate the parameters selected by :attr:`params` from ``stats``.

        The updates are the MAP estimates of Huang et al. [2]_ under the
        Dirichlet/normal/inverse-Wishart priors of the constructor. A prior
        below one can make a numerator negative; those terms are clipped to
        zero, which is the maximiser under the simplex constraint. Parameters
        that are exactly zero are kept at zero so that a structurally
        constrained model (a left-to-right chain, say) stays constrained.
        """
        if "s" in self.params:
            startprob = np.maximum(self.startprob_prior - 1 + stats["start"], 0)
            self.startprob_ = _normalized(np.where(self.startprob_ == 0, 0, startprob))
        if "t" in self.params:
            transmat = np.maximum(self.transmat_prior - 1 + stats["trans"], 0)
            self.transmat_ = _normalized(np.where(self.transmat_ == 0, 0, transmat), axis=1)

        # A state can lose all of its posterior mass -- with n_components above
        # what the data supports, that is the normal outcome. Its emission
        # parameters are then undefined (0/0); freeze them instead of letting a
        # nan spread through the next E-step and kill the whole fit.
        alive = stats["post"] > 0
        if not alive.all():
            logger.info(
                "%d of %d states carry no posterior mass; their emission "
                "parameters are held fixed.",
                (~alive).sum(),
                self.n_components,
            )
        denom = stats["post"][:, None]
        if "m" in self.params:
            means = (self.means_weight * self.means_prior + stats["obs"]) / np.maximum(
                self.means_weight + denom, np.finfo(float).tiny
            )
            self.means_ = np.where(alive[:, None], means, self.means_)
        if "c" not in self.params:
            return

        meandiff = self.means_ - self.means_prior
        if self.covariance_type in ("spherical", "diag"):
            c_n = (
                self.means_weight * meandiff**2
                + stats["obs**2"]
                - 2 * self.means_ * stats["obs"]
                + self.means_**2 * denom
            )
            c_d = max(self.covars_weight - 1, 0) + denom
            covars = (self.covars_prior + c_n) / np.maximum(c_d, 1e-5)
            if self.covariance_type == "spherical":
                self.covars_ = np.where(alive, covars.mean(axis=1), self.covars_)
            else:
                self.covars_ = np.where(alive[:, None], covars, self.covars_)
        else:
            c_n = np.empty((self.n_components, self.n_features, self.n_features))
            for c in range(self.n_components):
                obsmean = np.outer(stats["obs"][c], self.means_[c])
                c_n[c] = (
                    self.means_weight * np.outer(meandiff[c], meandiff[c])
                    + stats["obs*obs.T"][c]
                    - obsmean
                    - obsmean.T
                    + np.outer(self.means_[c], self.means_[c]) * stats["post"][c]
                )
            cvweight = max(self.covars_weight - self.n_features, 0)
            if self.covariance_type == "tied":
                self.covars_ = (self.covars_prior + c_n.sum(axis=0)) / max(
                    cvweight + stats["post"].sum(), np.finfo(float).tiny
                )
            else:
                covars = (self.covars_prior + c_n) / np.maximum(
                    cvweight + stats["post"][:, None, None], np.finfo(float).tiny
                )
                self.covars_ = np.where(alive[:, None, None], covars, self.covars_)
