"""ALEX labels and control help for every bundled ChiSurf UI locale."""

from emtk.i18n import add_translations

# English | German | French | Spanish | Portuguese | Russian.
ROWS = """Database|Datenbank|Base de données|Base de datos|Banco de dados|База данных
Queue TTTR data from the session database.|TTTR-Daten aus der Sitzungsdatenbank einreihen.|Ajouter les données TTTR de la base de session.|Añadir datos TTTR de la base de la sesión.|Adicionar dados TTTR do banco da sessão.|Добавить данные TTTR из базы сеанса.
Conversion|Konvertierung|Conversion|Conversión|Conversão|Преобразование
Batch|Stapelverarbeitung|Traitement par lot|Procesamiento por lotes|Processamento em lote|Пакетная обработка
ALEX micro-time histogram|ALEX-Mikrozeit-Histogramm|Histogramme des microtemps ALEX|Histograma de microtiempo ALEX|Histograma de microtempo ALEX|Гистограмма микровремени ALEX
Open…|Öffnen…|Ouvrir…|Abrir…|Abrir…|Открыть…
Save as…|Speichern unter…|Enregistrer sous…|Guardar como…|Guardar como…|Сохранить как…
Guide|Anleitung|Guide|Guía|Guia|Руководство
Help|Hilfe|Aide|Ayuda|Ajuda|Справка
Input file|Eingabedatei|Fichier source|Archivo de entrada|Arquivo de entrada|Входной файл
Load|Laden|Charger|Cargar|Carregar|Загрузить
Input format|Eingabeformat|Format source|Formato de entrada|Formato de entrada|Входной формат
Output format|Ausgabeformat|Format de sortie|Formato de salida|Formato de saída|Выходной формат
Period|Periode|Période|Período|Período|Период
Shift|Verschiebung|Décalage|Desplazamiento|Deslocamento|Сдвиг
events|Ereignisse|événements|eventos|eventos|событий
Add files…|Dateien hinzufügen…|Ajouter des fichiers…|Añadir archivos…|Adicionar arquivos…|Добавить файлы…
Folder…|Ordner…|Dossier…|Carpeta…|Pasta…|Папка…
Clear|Leeren|Vider|Vaciar|Limpar|Очистить
Run batch|Stapel starten|Exécuter le lot|Ejecutar lote|Executar lote|Запустить пакет
Mode|Modus|Mode|Modo|Modo|Режим
Convert each|Einzeln konvertieren|Convertir chaque fichier|Convertir cada archivo|Converter cada arquivo|Преобразовать каждый
Merge into one|In eine Datei zusammenführen|Fusionner en un fichier|Combinar en uno|Combinar em um|Объединить в один
Output folder|Ausgabeordner|Dossier de sortie|Carpeta de salida|Pasta de saída|Выходная папка
Browse…|Durchsuchen…|Parcourir…|Examinar…|Procurar…|Обзор…
Remove|Entfernen|Retirer|Quitar|Remover|Удалить
Micro-time bin|Mikrozeit-Bin|Canal de microtemps|Intervalo de microtiempo|Intervalo de microtempo|Канал микровремени
Counts|Zählungen|Comptages|Recuentos|Contagens|Отсчёты
ALEX phase|ALEX-Phase|Phase ALEX|Fase ALEX|Fase ALEX|Фаза ALEX
Working…|Verarbeitung…|Traitement…|Procesando…|Processando…|Обработка…
Loading…|Laden…|Chargement…|Cargando…|Carregando…|Загрузка…
Loaded|Geladen|Chargé|Cargado|Carregado|Загружено
Written files|Geschriebene Dateien|Fichiers écrits|Archivos escritos|Arquivos gravados|Записанные файлы
TTTR files|TTTR-Dateien|Fichiers TTTR|Archivos TTTR|Arquivos TTTR|Файлы TTTR
Please choose an existing TTTR file.|Bitte eine vorhandene TTTR-Datei wählen.|Choisissez un fichier TTTR existant.|Elija un archivo TTTR existente.|Escolha um arquivo TTTR existente.|Выберите существующий файл TTTR.
Choose a different output file to preserve the source.|Andere Ausgabedatei wählen, um die Quelle zu erhalten.|Choisissez un autre fichier de sortie pour préserver la source.|Elija otro archivo de salida para conservar el original.|Escolha outro arquivo de saída para preservar a origem.|Выберите другой выходной файл, чтобы сохранить исходный.
Load a file to preview ALEX phase.|Datei laden, um die ALEX-Phase anzuzeigen.|Chargez un fichier pour afficher la phase ALEX.|Cargue un archivo para ver la fase ALEX.|Carregue um arquivo para ver a fase ALEX.|Загрузите файл для просмотра фазы ALEX.
Load a TTTR file and preview its folded ALEX phase.|TTTR-Datei laden und die gefaltete ALEX-Phase anzeigen.|Charger un fichier TTTR et afficher sa phase ALEX repliée.|Cargar un archivo TTTR y ver su fase ALEX plegada.|Carregar um arquivo TTTR e ver sua fase ALEX dobrada.|Загрузить файл TTTR и просмотреть свёрнутую фазу ALEX.
Write converted photon data without changing the input.|Konvertierte Photonendaten schreiben, ohne die Eingabe zu ändern.|Écrire les photons convertis sans modifier la source.|Escribir fotones convertidos sin modificar la entrada.|Gravar fótons convertidos sem alterar a entrada.|Записать преобразованные фотоны без изменения исходного файла.
Walk through loading, timing and conversion.|Anleitung für Laden, Zeitparameter und Konvertierung.|Guide du chargement, des paramètres temporels et de la conversion.|Guía de carga, tiempos y conversión.|Guia de carregamento, tempos e conversão.|Руководство по загрузке, времени и преобразованию.
Read ALEX conversion and batch workflow help.|Hilfe zur ALEX-Konvertierung und Stapelverarbeitung lesen.|Lire l’aide sur la conversion ALEX et les lots.|Leer ayuda de conversión ALEX y lotes.|Ler ajuda de conversão ALEX e lotes.|Прочитать справку о преобразовании ALEX и пакетах.
Enter a TTTR path, then press Load; dropping a file also loads it.|TTTR-Pfad eingeben, dann Laden drücken; Dateien können auch abgelegt werden.|Saisir un chemin TTTR puis Charger ; déposer un fichier le charge aussi.|Introduzca una ruta TTTR y pulse Cargar; también puede soltar un archivo.|Digite um caminho TTTR e pressione Carregar; também pode soltar um arquivo.|Введите путь TTTR и нажмите Загрузить; можно также перетащить файл.
Read the file entered above.|Die oben eingetragene Datei lesen.|Lire le fichier indiqué ci-dessus.|Leer el archivo indicado arriba.|Ler o arquivo indicado acima.|Прочитать указанный выше файл.
Auto detects the container; choose a format to override detection.|Auto erkennt den Container; ein gewähltes Format überschreibt die Erkennung.|Auto détecte le conteneur ; choisir un format impose ce choix.|Auto detecta el contenedor; elija un formato para forzarlo.|Auto detecta o contêiner; escolha um formato para forçá-lo.|Auto определяет контейнер; выберите формат для явного задания.
Select the file container used for single and batch output.|Dateicontainer für Einzel- und Stapelausgabe wählen.|Choisir le conteneur des sorties individuelles et par lot.|Elegir el contenedor para salidas individuales y por lotes.|Escolher o contêiner para saídas individuais e em lote.|Выберите контейнер для одиночного и пакетного вывода.
Alternation period in macro-time units; maps phase to micro-time.|Alternationsperiode in Makrozeit-Einheiten; bildet die Phase auf Mikrozeit ab.|Période d’alternance en unités de macrotemps ; transforme la phase en microtemps.|Período de alternancia en unidades de macrotiempo; transforma fase en microtiempo.|Período de alternância em unidades de macrotempo; transforma fase em microtempo.|Период чередования в единицах макровремени; переводит фазу в микровремя.
Phase offset applied before folding macro-time into micro-time.|Phasenverschiebung vor der Faltung von Makrozeit in Mikrozeit.|Décalage de phase avant le repliement du macrotemps en microtemps.|Desplazamiento de fase antes de plegar macrotiempo en microtiempo.|Deslocamento de fase antes de dobrar macrotempo em microtempo.|Сдвиг фазы перед свёрткой макровремени в микровремя.
Queue TTTR files; duplicate paths are ignored.|TTTR-Dateien einreihen; doppelte Pfade werden ignoriert.|Ajouter des fichiers TTTR ; les doublons sont ignorés.|Añadir archivos TTTR; se ignoran rutas duplicadas.|Adicionar arquivos TTTR; caminhos duplicados são ignorados.|Добавить файлы TTTR; повторные пути игнорируются.
Queue supported TTTR files recursively from a folder.|Unterstützte TTTR-Dateien rekursiv aus einem Ordner einreihen.|Ajouter les fichiers TTTR compatibles d’un dossier et ses sous-dossiers.|Añadir archivos TTTR compatibles de una carpeta y subcarpetas.|Adicionar arquivos TTTR compatíveis de uma pasta e subpastas.|Добавить поддерживаемые файлы TTTR из папки и подпапок.
Empty the queue without deleting files.|Warteschlange leeren, ohne Dateien zu löschen.|Vider la liste sans supprimer les fichiers.|Vaciar la cola sin borrar archivos.|Limpar a fila sem excluir arquivos.|Очистить очередь без удаления файлов.
Convert each file or merge the queue using the current timing.|Dateien einzeln konvertieren oder mit aktuellen Zeitparametern zusammenführen.|Convertir chaque fichier ou fusionner avec les paramètres temporels actuels.|Convertir cada archivo o combinar con los tiempos actuales.|Converter cada arquivo ou combinar com os tempos atuais.|Преобразовать каждый файл или объединить с текущими параметрами времени.
Choose separate output files or one merged photon stream.|Einzelne Ausgabedateien oder einen vereinten Photonenstrom wählen.|Choisir des sorties séparées ou un flux de photons fusionné.|Elegir archivos separados o un flujo de fotones combinado.|Escolher arquivos separados ou um fluxo de fótons combinado.|Выберите отдельные файлы или объединённый поток фотонов.
Convert requires a folder; merge defaults to the first input folder.|Konvertierung erfordert einen Ordner; Zusammenführung nutzt standardmäßig den ersten Eingabeordner.|La conversion exige un dossier ; la fusion utilise par défaut celui de la première source.|Convertir requiere carpeta; combinar usa por defecto la de la primera entrada.|Converter exige pasta; combinar usa por padrão a da primeira entrada.|Преобразование требует папку; объединение по умолчанию использует папку первого файла.
Choose the output directory.|Ausgabeordner wählen.|Choisir le dossier de sortie.|Elegir carpeta de salida.|Escolher pasta de saída.|Выберите выходную папку.
Remove this file from the queue; keep it on disk.|Diese Datei aus der Warteschlange entfernen, auf der Festplatte behalten.|Retirer ce fichier de la liste sans le supprimer du disque.|Quitar este archivo de la cola sin borrarlo del disco.|Remover este arquivo da fila sem excluí-lo do disco.|Удалить файл из очереди, сохранив его на диске.
Please load a TTTR file first.|Bitte zuerst eine TTTR-Datei laden.|Chargez d’abord un fichier TTTR.|Cargue primero un archivo TTTR.|Carregue primeiro um arquivo TTTR.|Сначала загрузите файл TTTR.
Add .sm (or other TTTR) files to the batch list first.|Zuerst .sm- oder andere TTTR-Dateien einreihen.|Ajoutez d’abord des fichiers .sm ou TTTR.|Añada primero archivos .sm u otros TTTR.|Adicione primeiro arquivos .sm ou outros TTTR.|Сначала добавьте файлы .sm или другие TTTR.
Choose an output folder for the converted files.|Ausgabeordner für konvertierte Dateien wählen.|Choisissez un dossier pour les fichiers convertis.|Elija carpeta para los archivos convertidos.|Escolha pasta para os arquivos convertidos.|Выберите папку для преобразованных файлов.
Change <b>Shift</b> (or <b>Period</b>) and watch the histogram.|<b>Verschiebung</b> (oder <b>Periode</b>) ändern und das Histogramm beobachten.|Modifiez le <b>Décalage</b> (ou la <b>Période</b>) et observez l’histogramme.|Cambie el <b>Desplazamiento</b> (o el <b>Período</b>) y observe el histograma.|Altere o <b>Deslocamento</b> (ou o <b>Período</b>) e observe o histograma.|Измените <b>Сдвиг</b> (или <b>Период</b>) и наблюдайте за гистограммой.
Choose a TTTR file and preview its folded ALEX phase.|TTTR-Datei wählen und ihre gefaltete ALEX-Phase anzeigen.|Choisir un fichier TTTR et afficher sa phase ALEX repliée.|Elegir un archivo TTTR y ver su fase ALEX plegada.|Escolher um arquivo TTTR e ver sua fase ALEX dobrada.|Выбрать файл TTTR и просмотреть свёрнутую фазу ALEX.
Choose the output folder.|Ausgabeordner wählen.|Choisir le dossier de sortie.|Elegir la carpeta de salida.|Escolher a pasta de saída.|Выбрать выходную папку.
Container format written when saving (differs from input: transcode).|Beim Speichern geschriebenes Containerformat (anders als die Eingabe: Umwandlung).|Format de conteneur écrit à l’enregistrement (différent de la source : transcodage).|Formato de contenedor escrito al guardar (distinto de la entrada: transcodificación).|Formato de contêiner gravado ao salvar (diferente da entrada: transcodificação).|Формат контейнера при сохранении (отличается от входного: перекодирование).
Convert each file or merge the queue using the current period, shift and formats.|Jede Datei einzeln konvertieren oder die Warteschlange mit aktueller Periode, Verschiebung und aktuellen Formaten zusammenführen.|Convertir chaque fichier ou fusionner la liste avec la période, le décalage et les formats actuels.|Convertir cada archivo o combinar la cola con el período, desplazamiento y formatos actuales.|Converter cada arquivo ou combinar a fila com o período, deslocamento e formatos atuais.|Преобразовать каждый файл или объединить очередь с текущими периодом, сдвигом и форматами.
Convert each, or merge|Einzeln konvertieren oder zusammenführen|Convertir chaque fichier ou fusionner|Convertir cada archivo o combinar|Converter cada arquivo ou combinar|Преобразовать каждый или объединить
Convert requires a folder; merge defaults to the folder of the first input.|Konvertieren erfordert einen Ordner; Zusammenführen nutzt standardmäßig den Ordner der ersten Eingabe.|La conversion exige un dossier ; la fusion utilise par défaut celui de la première source.|Convertir requiere una carpeta; combinar usa por defecto la de la primera entrada.|Converter exige uma pasta; combinar usa por padrão a da primeira entrada.|Преобразование требует папку; объединение по умолчанию использует папку первого файла.
Load a photon file|Photonendatei laden|Charger un fichier de photons|Cargar un archivo de fotones|Carregar um arquivo de fótons|Загрузка файла фотонов
Number of photon events of the loaded file.|Anzahl der Photonenereignisse der geladenen Datei.|Nombre d’événements de photons du fichier chargé.|Número de eventos de fotones del archivo cargado.|Número de eventos de fótons do arquivo carregado.|Число фотонных событий загруженного файла.
Path of the TTTR file to convert. Press Enter (or click elsewhere) to load it; a file dropped on the window loads too.|Pfad der zu konvertierenden TTTR-Datei. Eingabetaste (oder Klick woanders) lädt sie; eine auf das Fenster gezogene Datei wird ebenfalls geladen.|Chemin du fichier TTTR à convertir. Entrée (ou un clic ailleurs) le charge ; un fichier déposé sur la fenêtre est aussi chargé.|Ruta del archivo TTTR a convertir. Intro (o un clic en otro lugar) lo carga; un archivo soltado en la ventana también se carga.|Caminho do arquivo TTTR a converter. Enter (ou um clique em outro lugar) o carrega; um arquivo solto na janela também é carregado.|Путь к конвертируемому файлу TTTR. Enter (или щелчок в другом месте) загружает его; файл, перетащенный в окно, тоже загружается.
Phase shift of the ALEX period before the macro-time to micro-time mapping.|Phasenverschiebung der ALEX-Periode vor der Abbildung von Makrozeit auf Mikrozeit.|Décalage de phase de la période ALEX avant la conversion du macrotemps en microtemps.|Desplazamiento de fase del período ALEX antes de convertir macrotiempo en microtiempo.|Deslocamento de fase do período ALEX antes de converter macrotempo em microtempo.|Сдвиг фазы периода ALEX перед переводом макровремени в микровремя.
Press <b>Add files…</b> (Cancel in the dialog to skip).|<b>Dateien hinzufügen…</b> drücken (im Dialog Abbrechen, um zu überspringen).|Appuyez sur <b>Ajouter des fichiers…</b> (Annuler dans la boîte pour passer).|Pulse <b>Añadir archivos…</b> (Cancelar en el diálogo para omitir).|Pressione <b>Adicionar arquivos…</b> (Cancelar na caixa para pular).|Нажмите <b>Добавить файлы…</b> (Отмена в диалоге, чтобы пропустить).
Press <b>Open…</b> and choose a file.|<b>Öffnen…</b> drücken und eine Datei wählen.|Appuyez sur <b>Ouvrir…</b> et choisissez un fichier.|Pulse <b>Abrir…</b> y elija un archivo.|Pressione <b>Abrir…</b> e escolha um arquivo.|Нажмите <b>Открыть…</b> и выберите файл.
Press <b>Save as…</b> (Cancel in the dialog to skip writing).|<b>Speichern unter…</b> drücken (im Dialog Abbrechen, um nichts zu schreiben).|Appuyez sur <b>Enregistrer sous…</b> (Annuler dans la boîte pour ne rien écrire).|Pulse <b>Guardar como…</b> (Cancelar en el diálogo para no escribir).|Pressione <b>Guardar como…</b> (Cancelar na caixa para não gravar).|Нажмите <b>Сохранить как…</b> (Отмена в диалоге, чтобы ничего не записывать).
Queue files for a batch|Dateien für einen Stapel einreihen|Mettre des fichiers en lot|Poner archivos en cola para un lote|Colocar arquivos na fila de um lote|Очередь файлов для пакета
Queue the supported TTTR files of a folder, scanned recursively.|Unterstützte TTTR-Dateien eines Ordners rekursiv einreihen.|Ajouter les fichiers TTTR compatibles d’un dossier, sous-dossiers compris.|Añadir los archivos TTTR compatibles de una carpeta, con subcarpetas.|Adicionar os arquivos TTTR compatíveis de uma pasta, com subpastas.|Добавить поддерживаемые файлы TTTR папки, включая вложенные.
Read the file named above.|Die oben genannte Datei lesen.|Lire le fichier indiqué ci-dessus.|Leer el archivo indicado arriba.|Ler o arquivo indicado acima.|Прочитать указанный выше файл.
Remove the selected file from the queue; the file stays on disk. Grey until a row is selected.|Die gewählte Datei aus der Warteschlange entfernen; sie bleibt auf der Festplatte. Grau, bis eine Zeile gewählt ist.|Retirer le fichier sélectionné de la liste ; il reste sur le disque. Grisé tant qu’aucune ligne n’est sélectionnée.|Quitar el archivo seleccionado de la cola; sigue en el disco. Gris hasta elegir una fila.|Remover o arquivo selecionado da fila; ele permanece no disco. Cinza até selecionar uma linha.|Удалить выбранный файл из очереди; на диске он остаётся. Неактивно, пока не выбрана строка.
Set the period and the shift|Periode und Verschiebung einstellen|Régler la période et le décalage|Ajustar el período y el desplazamiento|Ajustar o período e o deslocamento|Задайте период и сдвиг
The file name; hover a row for the full path.|Der Dateiname; die Zeile anzeigen lassen für den vollständigen Pfad.|Le nom du fichier ; survolez une ligne pour le chemin complet.|El nombre del archivo; pase el puntero por una fila para ver la ruta completa.|O nome do arquivo; passe o ponteiro sobre uma linha para ver o caminho completo.|Имя файла; наведите курсор на строку, чтобы увидеть полный путь.
The folder the file is in.|Der Ordner der Datei.|Le dossier du fichier.|La carpeta del archivo.|A pasta do arquivo.|Папка файла.
The queued files, in the order they are converted or merged. Click a row to select it, Delete removes it, the wheel scrolls.|Die eingereihten Dateien in der Reihenfolge der Konvertierung oder Zusammenführung. Zeile anklicken zum Wählen, Entf entfernt sie, das Mausrad scrollt.|Les fichiers de la liste, dans l’ordre de conversion ou de fusion. Cliquez une ligne pour la sélectionner, Suppr la retire, la molette fait défiler.|Los archivos en cola, en el orden de conversión o combinación. Pulse una fila para elegirla, Supr la quita, la rueda desplaza.|Os arquivos na fila, na ordem de conversão ou combinação. Clique numa linha para escolhê-la, Delete a remove, a roda rola.|Файлы очереди в порядке преобразования или объединения. Щёлкните строку для выбора, Delete удаляет её, колесо прокручивает.
Write the converted file|Die konvertierte Datei schreiben|Écrire le fichier converti|Escribir el archivo convertido|Gravar o arquivo convertido|Запись преобразованного файла
Write the converted photon data to a new file; the input is never overwritten. Grey until a file is loaded.|Die konvertierten Photonendaten in eine neue Datei schreiben; die Eingabe wird nie überschrieben. Grau, bis eine Datei geladen ist.|Écrire les photons convertis dans un nouveau fichier ; la source n’est jamais écrasée. Grisé tant qu’aucun fichier n’est chargé.|Escribir los fotones convertidos en un archivo nuevo; la entrada nunca se sobrescribe. Gris hasta cargar un archivo.|Gravar os fótons convertidos em um novo arquivo; a entrada nunca é sobrescrita. Cinza até carregar um arquivo.|Записать преобразованные фотоны в новый файл; входной файл не перезаписывается. Неактивно, пока файл не загружен.
No file loaded.|Keine Datei geladen.|Aucun fichier chargé.|Ningún archivo cargado.|Nenhum arquivo carregado.|Файл не загружен.
Formats|Formate|Formats|Formatos|Formatos|Форматы
ALEX modulation|ALEX-Modulation|Modulation ALEX|Modulación ALEX|Modulação ALEX|Модуляция ALEX
File|Datei|Fichier|Archivo|Arquivo|Файл
Folder|Ordner|Dossier|Carpeta|Pasta|Папка
Input|Eingabe|Entrée|Entrada|Entrada|Вход
Output|Ausgabe|Sortie|Salida|Saída|Выход
ALEX alternates two lasers within the macro-time, so the phase of every photon says which laser excited it. Press <b>Open…</b> and choose a TTTR file (a .sm, .ptu, .ht3 ...), or drop one on the window. Its folded ALEX phase appears as a histogram.|ALEX wechselt im Makrozeit-Verlauf zwischen zwei Lasern, die Phase jedes Photons zeigt also, welcher Laser es angeregt hat. <b>Öffnen…</b> drücken und eine TTTR-Datei wählen (.sm, .ptu, .ht3 ...) oder eine auf das Fenster ziehen. Die gefaltete ALEX-Phase erscheint als Histogramm.|L’ALEX alterne deux lasers dans le macrotemps : la phase de chaque photon indique donc quel laser l’a excité. Appuyez sur <b>Ouvrir…</b> et choisissez un fichier TTTR (.sm, .ptu, .ht3 ...) ou déposez-en un sur la fenêtre. Sa phase ALEX repliée s’affiche en histogramme.|ALEX alterna dos láseres dentro del macrotiempo, así que la fase de cada fotón indica qué láser lo excitó. Pulse <b>Abrir…</b> y elija un archivo TTTR (.sm, .ptu, .ht3 ...) o suelte uno en la ventana. Su fase ALEX plegada aparece como histograma.|O ALEX alterna dois lasers no macrotempo, então a fase de cada fóton indica qual laser o excitou. Pressione <b>Abrir…</b> e escolha um arquivo TTTR (.sm, .ptu, .ht3 ...) ou solte um na janela. Sua fase ALEX dobrada aparece como histograma.|ALEX чередует два лазера в макровремени, поэтому фаза каждого фотона показывает, каким лазером он возбуждён. Нажмите <b>Открыть…</b> и выберите файл TTTR (.sm, .ptu, .ht3 ...) или перетащите его в окно. Свёрнутая фаза ALEX появится в виде гистограммы.
<b>Period</b> is the alternation period in macro-time units (not seconds) and <b>Shift</b> moves the phase. Type a value and press Enter, or use the arrows or the mouse wheel over a field: the histogram on the right folds again at once. Set them so that the two excitation windows are separated cleanly and no photons sit on the border between them.|<b>Periode</b> ist die Alternationsperiode in Makrozeit-Einheiten (nicht Sekunden), <b>Verschiebung</b> verschiebt die Phase. Wert eintippen und Eingabetaste drücken oder die Pfeile bzw. das Mausrad über dem Feld nutzen: das Histogramm rechts faltet sich sofort neu. So einstellen, dass die beiden Anregungsfenster sauber getrennt sind und keine Photonen auf der Grenze liegen.|La <b>Période</b> est la période d’alternance en unités de macrotemps (pas en secondes) et le <b>Décalage</b> déplace la phase. Saisissez une valeur et validez, ou utilisez les flèches ou la molette sur un champ : l’histogramme à droite se replie aussitôt. Réglez-les pour séparer nettement les deux fenêtres d’excitation sans photons sur la frontière.|El <b>Período</b> es el período de alternancia en unidades de macrotiempo (no segundos) y el <b>Desplazamiento</b> mueve la fase. Escriba un valor y pulse Intro, o use las flechas o la rueda sobre un campo: el histograma de la derecha se pliega de inmediato. Ajústelos para separar bien las dos ventanas de excitación sin fotones en el borde.|O <b>Período</b> é o período de alternância em unidades de macrotempo (não segundos) e o <b>Deslocamento</b> move a fase. Digite um valor e pressione Enter, ou use as setas ou a roda sobre um campo: o histograma à direita é dobrado de novo na hora. Ajuste-os para separar bem as duas janelas de excitação, sem fótons na fronteira.|<b>Период</b> — период чередования в единицах макровремени (не секундах), <b>Сдвиг</b> смещает фазу. Введите значение и нажмите Enter либо используйте стрелки или колесо над полем: гистограмма справа сразу сворачивается заново. Подберите их так, чтобы два окна возбуждения чётко разделялись и на границе не было фотонов.
<b>Save as…</b> writes a new photon file whose micro-time is the folded ALEX phase, in the output container chosen under <b>Output</b> (Formats). The input file is never overwritten. The button stays grey until a file is loaded.|<b>Speichern unter…</b> schreibt eine neue Photonendatei, deren Mikrozeit die gefaltete ALEX-Phase ist, im unter <b>Ausgabe</b> (Formate) gewählten Container. Die Eingabedatei wird nie überschrieben. Die Schaltfläche bleibt grau, bis eine Datei geladen ist.|<b>Enregistrer sous…</b> écrit un nouveau fichier de photons dont le microtemps est la phase ALEX repliée, dans le conteneur choisi sous <b>Sortie</b> (Formats). Le fichier source n’est jamais écrasé. Le bouton reste grisé tant qu’aucun fichier n’est chargé.|<b>Guardar como…</b> escribe un archivo de fotones nuevo cuyo microtiempo es la fase ALEX plegada, en el contenedor elegido en <b>Salida</b> (Formatos). El archivo de entrada nunca se sobrescribe. El botón sigue gris hasta cargar un archivo.|<b>Guardar como…</b> grava um novo arquivo de fótons cujo microtempo é a fase ALEX dobrada, no contêiner escolhido em <b>Saída</b> (Formatos). O arquivo de entrada nunca é sobrescrito. O botão fica cinza até carregar um arquivo.|<b>Сохранить как…</b> записывает новый файл фотонов, микровремя которого — свёрнутая фаза ALEX, в контейнере, выбранном в <b>Выход</b> (Форматы). Входной файл не перезаписывается. Кнопка неактивна, пока файл не загружен.
For many files, <b>Add files…</b> (or <b>Folder…</b>, or the session database) fills the queue below. The period, shift and formats above apply to every file in it; select a row and press <b>Remove</b> (or Delete) to drop one.|Für viele Dateien füllt <b>Dateien hinzufügen…</b> (oder <b>Ordner…</b> oder die Sitzungsdatenbank) die Warteschlange darunter. Periode, Verschiebung und Formate oben gelten für jede Datei darin; Zeile wählen und <b>Entfernen</b> (oder Entf) drücken, um eine zu streichen.|Pour de nombreux fichiers, <b>Ajouter des fichiers…</b> (ou <b>Dossier…</b>, ou la base de session) remplit la liste ci-dessous. La période, le décalage et les formats ci-dessus s’appliquent à chaque fichier ; sélectionnez une ligne et appuyez sur <b>Retirer</b> (ou Suppr) pour en ôter une.|Para muchos archivos, <b>Añadir archivos…</b> (o <b>Carpeta…</b>, o la base de datos de la sesión) llena la cola de abajo. El período, el desplazamiento y los formatos de arriba valen para cada archivo; elija una fila y pulse <b>Quitar</b> (o Supr) para quitarla.|Para muitos arquivos, <b>Adicionar arquivos…</b> (ou <b>Pasta…</b>, ou o banco da sessão) preenche a fila abaixo. O período, o deslocamento e os formatos acima valem para cada arquivo; escolha uma linha e pressione <b>Remover</b> (ou Delete) para retirá-la.|Для многих файлов <b>Добавить файлы…</b> (или <b>Папка…</b>, или база данных сеанса) заполняет очередь ниже. Период, сдвиг и форматы выше действуют для каждого файла; выберите строку и нажмите <b>Удалить</b> (или Delete), чтобы убрать её.
Choose <b>Convert each</b> (needs an output folder) or <b>Merge into one</b> (successive streams are joined with continuing macro-time before folding), then press <b>Run batch</b>. The written file names appear above the histogram.|<b>Einzeln konvertieren</b> (benötigt einen Ausgabeordner) oder <b>In eine Datei zusammenführen</b> (aufeinanderfolgende Ströme werden mit fortlaufender Makrozeit vor dem Falten verbunden) wählen, dann <b>Stapel starten</b> drücken. Die geschriebenen Dateinamen erscheinen über dem Histogramm.|Choisissez <b>Convertir chaque fichier</b> (dossier de sortie requis) ou <b>Fusionner en un fichier</b> (les flux successifs sont joints avec un macrotemps continu avant le repliement), puis appuyez sur <b>Exécuter le lot</b>. Les noms des fichiers écrits apparaissent au-dessus de l’histogramme.|Elija <b>Convertir cada archivo</b> (requiere carpeta de salida) o <b>Combinar en uno</b> (los flujos sucesivos se unen con macrotiempo continuo antes de plegar) y pulse <b>Ejecutar lote</b>. Los nombres de los archivos escritos aparecen sobre el histograma.|Escolha <b>Converter cada arquivo</b> (exige pasta de saída) ou <b>Combinar em um</b> (fluxos sucessivos são unidos com macrotempo contínuo antes de dobrar) e pressione <b>Executar lote</b>. Os nomes dos arquivos gravados aparecem acima do histograma.|Выберите <b>Преобразовать каждый</b> (нужна выходная папка) или <b>Объединить в один</b> (последовательные потоки соединяются с непрерывным макровременем перед свёрткой), затем нажмите <b>Запустить пакет</b>. Имена записанных файлов появятся над гистограммой.
ALEX alternation period (macro-time units) mapped onto micro-time.|ALEX-Alternationsperiode (Makrozeit-Einheiten), abgebildet auf Mikrozeit.|Période d’alternance ALEX (unités de macrotemps) convertie en microtemps.|Período de alternancia ALEX (unidades de macrotiempo) convertido en microtiempo.|Período de alternância ALEX (unidades de macrotempo) convertido em microtempo.|Период чередования ALEX (единицы макровремени), переводимый в микровремя.
Convert every file to its own ALEX output, or merge them all into one.|Jede Datei in eine eigene ALEX-Ausgabe konvertieren oder alle zu einer zusammenführen.|Convertir chaque fichier en sa propre sortie ALEX, ou tous les fusionner en un seul.|Convertir cada archivo en su propia salida ALEX, o combinarlos todos en uno.|Converter cada arquivo em sua própria saída ALEX, ou combiná-los todos em um.|Преобразовать каждый файл в отдельный вывод ALEX или объединить все в один.
Force the input container type, or Auto to detect it from the file.|Den Eingabe-Containertyp erzwingen, oder Auto zur Erkennung aus der Datei.|Imposer le type de conteneur source, ou Auto pour le détecter d’après le fichier.|Forzar el tipo de contenedor de entrada, o Auto para detectarlo del archivo.|Forçar o tipo de contêiner de entrada, ou Auto para detectá-lo a partir do arquivo.|Задать тип входного контейнера или Auto для определения по файлу."""


def install_translations():
    for index, locale in enumerate(("en", "de", "fr", "es", "pt", "ru")):
        entries = [line.split("|") for line in ROWS.splitlines()]
        add_translations(locale, {row[0]: row[index] for row in entries})


HELP = {
    "de": """# ALEX Creator
Laden Sie eine TTTR-Datei, auch .sm. Wählen Sie Eingabe- und Ausgabeformat sowie Periode und Verschiebung in Makrozeit-Einheiten. Das Histogramm zeigt die gefaltete Mikrozeit-Phase und aktualisiert sich bei Änderungen.
Speichern unter schreibt eine neue Datei; die Quelle bleibt erhalten. Die gemeinsame Konvertierungs-API bestimmt die Regeln für Photonendaten und Metadaten.
Für Stapelverarbeitung Dateien oder Ordner hinzufügen. Konvertieren benötigt einen Ausgabeordner. Zusammenführen versetzt die Makrozeiten in einen monotonen Strom und faltet dann ALEX; ohne Ausgabeordner wird der erste Eingabeordner verwendet. Eine Zeile wählen und Entfernen (oder Entf) drücken entfernt sie aus der Warteschlange. Datenbank lädt TTTR-Datensätze aus der Sitzung.
Eine abgelegte Datei wird geladen; mehrere Dateien oder Ordner werden eingereiht. Formate, Zeitparameter, Pfade und Stapeloptionen werden gespeichert. Eine gespeicherte Eingabe muss explizit geladen werden.""",
    "fr": """# ALEX Creator
Chargez un fichier TTTR, y compris .sm. Choisissez les formats source et sortie, la période et le décalage en unités de macrotemps. L’histogramme affiche la phase de microtemps repliée et se met à jour lors des changements.
Enregistrer sous écrit un nouveau fichier et préserve la source. L’API de conversion commune définit les règles pour les photons et les métadonnées.
Pour les lots, ajoutez des fichiers ou dossiers. Convertir exige un dossier de sortie. Fusionner décale les macrotemps en un flux monotone avant le repliement ALEX ; sans dossier de sortie, celui de la première source est utilisé. Sélectionnez une ligne puis Retirer (ou Suppr) pour l’ôter de la liste. Base de données charge les données TTTR de la session.
Déposer un fichier charge l’aperçu ; plusieurs fichiers ou dossiers remplissent la liste. Les formats, temps, chemins, options de lot sont mémorisés. Le fichier mémorisé doit être chargé explicitement.""",
    "es": """# ALEX Creator
Cargue un archivo TTTR, incluido .sm. Elija formatos de entrada y salida, período y desplazamiento en unidades de macrotiempo. El histograma muestra la fase de microtiempo plegada y se actualiza al cambiar parámetros.
Guardar como escribe un archivo nuevo y conserva el original. La API de conversión compartida define las reglas para fotones y metadatos.
Para lotes, añada archivos o carpetas. Convertir requiere carpeta de salida. Combinar desplaza macrotiempos a un flujo monótono antes de plegar ALEX; sin carpeta usa la de la primera entrada. Elija una fila y pulse Quitar (o Supr) para quitarla de la cola. Base de datos carga datos TTTR de la sesión.
Soltar un archivo carga la vista previa; varios archivos o carpetas se añaden a la cola. Se guardan formatos, tiempos, rutas, opciones de lote. La entrada recordada debe cargarse explícitamente.""",
    "pt": """# ALEX Creator
Carregue um arquivo TTTR, incluindo .sm. Escolha formatos de entrada e saída, período e deslocamento em unidades de macrotempo. O histograma mostra a fase de microtempo dobrada e atualiza ao alterar parâmetros.
Guardar como grava um novo arquivo e preserva a origem. A API de conversão compartilhada define as regras para fótons e metadados.
Para lotes, adicione arquivos ou pastas. Converter exige pasta de saída. Combinar desloca macrotempos para um fluxo monótono antes de dobrar ALEX; sem pasta usa a da primeira entrada. Escolha uma linha e pressione Remover (ou Delete) para retirá-la da fila. Banco de dados carrega dados TTTR da sessão.
Soltar um arquivo carrega a visualização; vários arquivos ou pastas entram na fila. Formatos, tempos, caminhos, opções de lote são salvos. A entrada lembrada deve ser carregada explicitamente.""",
    "ru": """# ALEX Creator
Загрузите файл TTTR, включая .sm. Выберите входной и выходной форматы, период и сдвиг в единицах макровремени. Гистограмма показывает свёрнутую фазу микровремени и обновляется при изменении параметров.
Сохранить как записывает новый файл и сохраняет исходный. Общий API преобразования определяет правила для фотонов и метаданных.
Для пакетов добавьте файлы или папки. Преобразование требует выходную папку. Объединение сдвигает макровремя в монотонный поток перед свёрткой ALEX; без выходной папки используется папка первого файла. Выберите строку и нажмите Удалить (или Delete), чтобы убрать её из очереди. База данных загружает данные TTTR из сеанса.
Перетаскивание одного файла загружает просмотр; несколько файлов или папок добавляются в очередь. Форматы, время, пути, пакетные настройки сохраняются. Сохранённый входной файл следует загрузить явно.""",
}
