"""The display settings are a form, and the toolbar holds only actions.

Which diagnostic layers are drawn, and over which slice of the file, are
settings — they belong in a form beside the other settings, not in the toolbar
that carries Process/Clear/Refresh. The form is generated by AutoForm from
``burst_display.view.json`` and binds to a view-model that proxies to the tool's
own widgets, so moving the control changed no reader of the state.
"""

import pytest

pytest.importorskip("qtpy.QtWidgets", reason="no Qt binding installed")

from qtpy import QtWidgets  # noqa: E402


@pytest.fixture
def tool(qapp):
    from chisurf.plugins.burst.burst_selection import BurstSelectionTool

    widget = BurstSelectionTool()
    yield widget
    widget.close()


def _display_form(tool):
    from chisurf.gui.autoform import AutoForm

    forms = [
        f for f in tool.findChildren(AutoForm)
        if getattr(f.model, "__class__", None).__name__ == "BurstDisplayViewModel"
    ]
    assert len(forms) == 1, "exactly one Display form, built once"
    return forms[0]


def test_the_form_is_built_and_shows_its_four_controls(tool):
    """It renders — an empty collapsed header is the failure this pins."""
    form = _display_form(tool)
    assert form.findChildren(QtWidgets.QCheckBox), "no toggle rendered"
    assert len(form.findChildren(QtWidgets.QSpinBox)) == 2, "photon range missing"
    # A panel that renders nothing collapses to a bare header; a real one is
    # taller than its title bar.
    assert form.sizeHint().height() > 40, form.sizeHint()


def test_the_toolbar_carries_no_display_settings(tool):
    """The toolbar holds actions; a wide settings run pushed them out of view."""
    bars = tool.findChildren(QtWidgets.QToolBar)
    assert bars
    for bar in bars:
        for child in bar.findChildren(QtWidgets.QWidget):
            assert child is not tool.plot_min_spin
            assert child is not tool.plot_max_spin
            assert child is not tool.show_all_photons_check
            assert child is not tool.show_selected_photons_check


def test_the_form_and_the_tool_are_one_state_not_two(tool):
    """The view-model proxies to the tool's widgets, so nothing can drift."""
    vm = tool._display_view_model

    tool.plot_min_spin.setValue(17)
    assert vm.photon_first == 17, "the form reads the tool's widget"

    vm.photon_last = 4242
    assert tool.plot_max_spin.value() == 4242, "and writes it"

    tool.show_all_photons_check.setChecked(False)
    assert vm.show_all_photons is False
    vm.show_selected_photons = False
    assert tool.show_selected_photons_check.isChecked() is False


def test_setting_a_value_through_the_form_redraws_the_plots(tool, monkeypatch):
    """The widgets keep their signal wiring, so the form drives the same update."""
    calls = []
    monkeypatch.setattr(tool, "update_burst_plots", lambda *a, **k: calls.append(1))
    # Reconnect: the connection was made to the bound method captured earlier.
    tool.plot_min_spin.valueChanged.connect(tool.update_burst_plots)

    tool._display_view_model.photon_first = 99
    assert calls, "changing the setting through the form did not refresh anything"


def test_no_control_panel_is_left_floating_over_the_dock_area(tool):
    """A built-but-unplaced panel draws at 640x480 in the corner.

    The diagnostic control panels are built for every plot but only placed when
    that plot is shown; an unplaced one kept the dock area as its parent with no
    layout to size it, and Qt drew a ghost "Burst bins" spin box across the tab
    bar.
    """
    stray = [
        w for w in tool.dock_area.children()
        if isinstance(w, QtWidgets.QWidget)
        and w.isVisible()
        and w.parentWidget() is tool.dock_area
        and w not in getattr(tool.dock_area, "_all_widgets", [])
        and w is not getattr(tool.dock_area, "_root_widget", None)
    ]
    assert not stray, [type(w).__name__ for w in stray]
