"""The simulate -> real pipeline -> fit loop, on photons with known truth.

The 2D-MFD model is checked elsewhere against data generated by chisurf's own
reasoning (``mfd/simulate.py``), which can only show that the code does what its
author meant. Here the photons come from tttrlib's confocal simulator — C++
written for another purpose, with molecules diffusing through a focus and
switching conformation on the simulated clock — and go through the *same* burst
tables, reader and response estimation as a measurement.

These are the gates the benchmark rests on. If the simulator's kinetics or the
folder it writes are wrong, every recovery number downstream is wrong too, and
looks fine.
"""
import numpy as np
import pytest

from chisurf.core.fluorescence.burst.simulate import (
    MFD_STREAMS,
    SmfretParameters,
    simulate_smfret,
)

pytestmark = pytest.mark.skipif(
    not hasattr(pytest.importorskip("tttrlib"), "SimEngine"),
    reason="the installed tttrlib has no SimEngine simulator",
)

#: A small polarized MFD measurement: two states, no corrections, fast to run.
MFD = dict(
    n_photons=60_000, seed=11, alex=False, polarized=True,
    efficiencies=(0.2, 0.8), donor_only=0.0, acceptor_only=0.0,
    gamma=1.0, alpha=0.0, beta=1.0, delta=0.0,
    concentration=1.0, brightness=300.0, background=0.0, rho=1.0,
)


def test_polarized_mode_emits_the_four_mfd_detectors():
    """Green and red, each split parallel/perpendicular, on the pipeline's channels."""
    sim = simulate_smfret(**MFD)
    found = {name: int(np.count_nonzero(sim.stream == ch))
             for name, ch in MFD_STREAMS.items()}
    assert all(count > 0 for count in found.values()), found

    # Equal populations at E=0.2/0.8 with no corrections put the raw proximity
    # ratio at the mean of the two efficiencies.
    green = found["g_par"] + found["g_perp"]
    red = found["r_par"] + found["r_perp"]
    assert red / (green + red) == pytest.approx(0.5, abs=0.05)


def test_the_polarization_split_follows_perrin():
    """The parallel/perpendicular ratio tracks r0/(1 + tau/rho), not a constant."""
    from chisurf.core.fluorescence.anisotropy.integrals import (
        perrin_steady_state_anisotropy,
    )

    for rho in (0.5, 4.0):
        sim = simulate_smfret(**{**MFD, "rho": rho})
        found = {name: int(np.count_nonzero(sim.stream == ch))
                 for name, ch in MFD_STREAMS.items()}
        ratio = found["g_par"] / found["g_perp"]
        # p_par/(1-p_par) = (1+2r)/(1-r) at G=1, l1=l2=0 -> invert for r
        measured = (ratio - 1.0) / (2.0 + ratio)
        tau = float(np.mean(sim.parameters.expected_lifetimes()))
        expected = perrin_steady_state_anisotropy(
            tau, rho, r0=sim.parameters.r0_fundamental
        )
        assert measured == pytest.approx(expected, rel=0.25), (rho, measured, expected)


def test_exchange_reaches_the_photons():
    """A molecule that switches conformation emits photons from both states.

    Guards the two conversions between chisurf's ``K[target, source]`` in Hz and
    the engine's row-major source->target per millisecond. Either mistake leaves a
    simulation that runs and is silently static, or a thousand times too fast.
    """
    purity = {}
    for rate in (0.0, 1_000.0, 20_000.0):
        matrix = None if rate == 0 else np.array([[0.0, rate], [rate, 0.0]])
        sim = simulate_smfret(**MFD, rate_matrix=matrix)
        keep = sim.species >= 0
        molecule, species = sim.molecule[keep], sim.species[keep]
        order = np.argsort(molecule, kind="stable")
        molecule, species = molecule[order], species[order]
        parts = np.split(species, np.flatnonzero(np.diff(molecule)) + 1)
        purity[rate] = float(np.mean([
            np.bincount(part, minlength=2).max() / part.size
            for part in parts if part.size >= 20
        ]))

    assert purity[0.0] == 1.0                       # static: never switches
    assert purity[1_000.0] < 0.95                   # exchange is visible
    assert purity[20_000.0] < purity[1_000.0]       # and grows with the rate


def test_the_irf_shifts_the_mean_micro_time_by_its_centre():
    """A Gaussian IRF convolves the decay rather than being ignored."""
    green = [MFD_STREAMS["g_par"], MFD_STREAMS["g_perp"]]

    def mean_micro(**changes):
        sim = simulate_smfret(**{**MFD, **changes})
        micro = np.asarray(sim.tttr.micro_times, dtype=float)
        return float(micro[np.isin(sim.stream, green)].mean()
                     * sim.parameters.microtime_resolution)

    bare = mean_micro()
    shifted = mean_micro(irf_centre=2.0, irf_width=0.12)
    assert shifted - bare == pytest.approx(2.0, abs=0.1)


def test_truth_bursts_are_single_molecule_transits():
    """The burst search a measurement cannot have: one transit, by definition."""
    sim = simulate_smfret(**MFD)
    bursts = sim.true_bursts(min_photons=20)
    assert len(bursts) > 20

    molecule, species = np.asarray(sim.molecule), np.asarray(sim.species)
    distinct = [
        len(set(molecule[a:b + 1][species[a:b + 1] >= 0].tolist()))
        for a, b in bursts
    ]
    # Two molecules can overlap in the focus; the point is that it is rare, so a
    # difference against searched bursts is the search's doing and not this.
    assert np.mean(np.asarray(distinct) == 1) > 0.9


@pytest.mark.parametrize("definition", ["truth", "search"])
def test_the_written_folder_reproduces_the_emitted_photons(tmp_path, definition):
    """Both burst routes write a folder the ordinary reader accepts, losing nothing.

    The per-detector columns are compared against the photons actually emitted in
    each span: a channel definition that is plausible but wrong makes everything
    downstream wrong and believable.
    """
    from chisurf.core.fluorescence.mfd.fit import load_mfd_data

    sim = simulate_smfret(**MFD)
    spans = (sim.true_bursts(min_photons=20) if definition == "truth"
             else sim.searched_bursts(min_photons=20))
    folder = sim.write_folder(tmp_path / definition, bursts=spans)

    data = load_mfd_data(folder, min_green_photons=20)
    preparation = data.preparation
    assert "green" in preparation.verified_channels
    assert "red" in preparation.verified_channels
    assert len(preparation) == len(spans)

    stream = np.asarray(sim.stream)
    green = [MFD_STREAMS["g_par"], MFD_STREAMS["g_perp"]]
    emitted = np.array([np.isin(stream[a:b + 1], green).sum() for a, b in spans])
    assert np.array_equal(emitted, preparation.counts[:, preparation.channel_index("green")])


def test_the_exchange_matrix_is_transposed_and_rescaled():
    """``K[target, source]`` in Hz becomes row-major source->target per millisecond."""
    params = SmfretParameters(
        efficiencies=(0.2, 0.8), donor_only=0.0, acceptor_only=0.0,
        rate_matrix=np.array([[0.0, 300.0], [700.0, 0.0]]),
    )
    flat = np.asarray(params.exchange_matrix_ms()).reshape(2, 2)
    # source 0 -> target 1 is K[1, 0] = 700 Hz = 0.7 / ms, and it lands in row 0.
    assert flat[0, 1] == pytest.approx(0.7)
    assert flat[1, 0] == pytest.approx(0.3)
