from emtk import i18n

_CATALOGS = {
    "de": {
        "Plot Settings": "Plot-Einstellungen",
        "Rendering Backend": "Rendering-Backend",
        "Colors": "Farben",
        "Actions": "Aktionen",
        "Apply": "Anwenden",
        "Save": "Speichern",
        "Reset": "Zurücksetzen",
        "Defaults loaded": "Standards geladen",
        "Applied": "Angewendet",
        "Node Graphs (Global View)": "Knotengraphen (Global View)",
        "Show grid": "Raster anzeigen",
        "Grid line width": "Rasterlinienbreite",
        "Node grid opacity": "Knotenraster-Deckkraft",
        "Grid spacing": "Rasterabstand",
        "Node size (Global View)": "Knotengröße (Global View)",
        "Show the background grid of a node graph.": "Hintergrundraster eines Knotengraphen anzeigen.",
        "Grid line thickness. Below one pixel draws a hairline, which is what keeps the grid under the edges drawn on top of it.": "Rasterliniendicke. Unter einem Pixel entsteht eine Haarlinie, damit das Raster hinter den darüber gezeichneten Kanten zurücktritt.",
        "Grid line opacity of a node graph.": "Rasterlinien-Deckkraft eines Knotengraphen.",
        "Distance between the grid lines of a node graph.": "Abstand der Rasterlinien eines Knotengraphen.",
        "The node radius a newly opened Global View starts its own node-size control at.": "Der Knotenradius, mit dem ein neu geöffnetes Global View seine Knotengröße startet.",
    },
    "fr": {
        "Plot Settings": "Paramètres des tracés",
        "Rendering Backend": "Moteur de rendu",
        "Colors": "Couleurs",
        "Actions": "Actions",
        "Apply": "Appliquer",
        "Save": "Enregistrer",
        "Reset": "Réinitialiser",
        "Defaults loaded": "Paramètres chargés",
        "Applied": "Appliqué",
        "Node Graphs (Global View)": "Graphes de nœuds (Global View)",
        "Show grid": "Afficher la grille",
        "Grid line width": "Épaisseur du quadrillage",
        "Node grid opacity": "Opacité du quadrillage des nœuds",
        "Grid spacing": "Pas du quadrillage",
        "Node size (Global View)": "Taille des nœuds (Global View)",
        "Show the background grid of a node graph.": "Afficher le quadrillage d’un graphe de nœuds.",
        "Grid line thickness. Below one pixel draws a hairline, which is what keeps the grid under the edges drawn on top of it.": "Épaisseur du quadrillage. Sous un pixel, un trait hairline laisse les arêtes passer devant.",
        "Grid line opacity of a node graph.": "Opacité du quadrillage d’un graphe de nœuds.",
        "Distance between the grid lines of a node graph.": "Distance entre les lignes du quadrillage.",
        "The node radius a newly opened Global View starts its own node-size control at.": "Rayon de nœud initial du contrôle de taille d’une nouvelle Global View.",
    },
    "es": {
        "Plot Settings": "Ajustes de gráficos",
        "Rendering Backend": "Motor de renderizado",
        "Colors": "Colores",
        "Actions": "Acciones",
        "Apply": "Aplicar",
        "Save": "Guardar",
        "Reset": "Restablecer",
        "Defaults loaded": "Valores cargados",
        "Applied": "Aplicado",
        "Node Graphs (Global View)": "Grafos de nodos (Global View)",
        "Show grid": "Mostrar cuadrícula",
        "Grid line width": "Grosor de cuadrícula",
        "Node grid opacity": "Opacidad de cuadrícula de nodos",
        "Grid spacing": "Paso de cuadrícula",
        "Node size (Global View)": "Tamaño de nodos (Global View)",
        "Show the background grid of a node graph.": "Mostrar la cuadrícula de fondo de un grafo de nodos.",
        "Grid line thickness. Below one pixel draws a hairline, which is what keeps the grid under the edges drawn on top of it.": "Grosor de la cuadrícula. Por debajo de un píxel dibuja un hilo fino que deja pasar las aristas.",
        "Grid line opacity of a node graph.": "Opacidad de la cuadrícula de un grafo de nodos.",
        "Distance between the grid lines of a node graph.": "Distancia entre las líneas de la cuadrícula.",
        "The node radius a newly opened Global View starts its own node-size control at.": "Radio de nodo con el que empieza el control de tamaño de un nuevo Global View.",
    },
    "pt": {
        "Plot Settings": "Definições de gráficos",
        "Rendering Backend": "Motor de renderização",
        "Colors": "Cores",
        "Actions": "Ações",
        "Apply": "Aplicar",
        "Save": "Guardar",
        "Reset": "Repor",
        "Defaults loaded": "Predefinições carregadas",
        "Applied": "Aplicado",
        "Node Graphs (Global View)": "Grafos de nós (Global View)",
        "Show grid": "Mostrar grade",
        "Grid line width": "Espessura da grade",
        "Node grid opacity": "Opacidade da grade de nós",
        "Grid spacing": "Espaçamento da grade",
        "Node size (Global View)": "Tamanho dos nós (Global View)",
        "Show the background grid of a node graph.": "Mostrar a grade de fundo de um grafo de nós.",
        "Grid line thickness. Below one pixel draws a hairline, which is what keeps the grid under the edges drawn on top of it.": "Espessura da grade. Abaixo de um píxel desenha um fio fino que deixa passar as arestas.",
        "Grid line opacity of a node graph.": "Opacidade da grade de um grafo de nós.",
        "Distance between the grid lines of a node graph.": "Distância entre as linhas da grade.",
        "The node radius a newly opened Global View starts its own node-size control at.": "Raio de nó com que um novo Global View inicia o seu controlo de tamanho.",
    },
    "ru": {
        "Plot Settings": "Настройки графиков",
        "Rendering Backend": "Движок визуализации",
        "Colors": "Цвета",
        "Actions": "Действия",
        "Apply": "Применить",
        "Save": "Сохранить",
        "Reset": "Сбросить",
        "Defaults loaded": "Настройки загружены",
        "Applied": "Применено",
        "Node Graphs (Global View)": "Графы узлов (Global View)",
        "Show grid": "Показать сетку",
        "Grid line width": "Толщина линии сетки",
        "Node grid opacity": "Непрозрачность сетки узлов",
        "Grid spacing": "Шаг сетки",
        "Node size (Global View)": "Размер узлов (Global View)",
        "Show the background grid of a node graph.": "Показать фоновую сетку графа узлов.",
        "Grid line thickness. Below one pixel draws a hairline, which is what keeps the grid under the edges drawn on top of it.": "Толщина линии сетки. Меньше пикселя даёт волосяную линию, не перекрывающую рёбра.",
        "Grid line opacity of a node graph.": "Непрозрачность линии сетки графа узлов.",
        "Distance between the grid lines of a node graph.": "Расстояние между линиями сетки графа узлов.",
        "The node radius a newly opened Global View starts its own node-size control at.": "Радиус узла, с которого новое окно Global View начинает управление размером.",
    },
}


def install_translations():
    for locale, values in _CATALOGS.items():
        i18n.add_translations(locale, values, context="Plot Settings")


def tr(text):
    return i18n.tr(text, context="Plot Settings")
