"""Tile maps: the ground a top-down game is played on.

The reference keeps its maps as Godot ``TileMap`` layers of 16-pixel atlas
cells. The port here is a numpy grid of cell ids plus a uv table: the grid is
content (generated by the game from its own data), the table says what each id
looks like, and :meth:`TileMap.draw_visible` turns the tiles a camera can see
into one bulk instance array — the batcher's fast path — so a screenful of
ground costs one vectorised pass and one buffer write, not thousands of Python
calls.
"""

from __future__ import annotations

import numpy as np

from .render import FLOATS_PER_INSTANCE, SPRITE, Camera


class TileMap:
    """A grid of atlas cells.

    Parameters
    ----------
    grid : numpy.ndarray
        ``(height, width)`` integer cell ids; negative cells are empty.
    uv_table : numpy.ndarray
        ``(n, 4)`` float32 uv rectangle per cell id, in cell-id order from 0.
    tile : float, optional
        World size of one cell.
    offset : tuple of float, optional
        World position of the grid's top-left corner.
    solid_ids : iterable of int, optional
        Cell ids that block movement.
    """

    def __init__(
        self,
        grid: np.ndarray,
        uv_table: np.ndarray,
        tile: float = 16.0,
        offset: tuple[float, float] = (0.0, 0.0),
        solid_ids=(),
    ) -> None:
        self.grid = np.ascontiguousarray(grid, dtype=np.int32)
        self.uv_table = np.ascontiguousarray(uv_table, dtype=np.float32)
        self.tile = float(tile)
        self.offset = np.asarray(offset, dtype=np.float64)
        self.solids = frozenset(int(i) for i in solid_ids)

    @property
    def shape(self) -> tuple[int, int]:
        """Grid shape in cells.

        Returns
        -------
        tuple of int
            ``(rows, columns)``.
        """
        return self.grid.shape  # type: ignore[return-value]

    def cell_at(self, x: float, y: float) -> int:
        """The cell id at a world position.

        Parameters
        ----------
        x, y : float
            World position.

        Returns
        -------
        int
            Cell id, or ``-1`` outside the grid.
        """
        column = int((x - self.offset[0]) // self.tile)
        row = int((y - self.offset[1]) // self.tile)
        if not (0 <= row < self.grid.shape[0] and 0 <= column < self.grid.shape[1]):
            return -1
        return int(self.grid[row, column])

    def solid_at(self, x: float, y: float) -> bool:
        """Whether a world position blocks movement.

        Parameters
        ----------
        x, y : float
            World position.

        Returns
        -------
        bool
            True on a solid cell; outside the grid counts as solid so a walk
            can never leave the map.
        """
        cell = self.cell_at(x, y)
        if cell < 0:
            return True
        return cell in self.solids

    def visible_instances(
        self, camera: Camera, aspect: float, margin: int = 1
    ) -> np.ndarray:
        """Build the instance rows for the tiles a camera can see.

        Parameters
        ----------
        camera : Camera
            The view.
        aspect : float
            Canvas width over height.
        margin : int, optional
            Extra tiles of skirt, so an edge tile scrolling in is already
            drawn.

        Returns
        -------
        numpy.ndarray
            ``(n, FLOATS_PER_INSTANCE)`` float32 rows for the batcher.
        """
        half = camera.half_extent(aspect)
        left = camera.center[0] - half[0]
        right = camera.center[0] + half[0]
        top = camera.center[1] - half[1]
        bottom = camera.center[1] + half[1]
        col0 = max(0, int((left - self.offset[0]) // self.tile) - margin)
        col1 = min(self.grid.shape[1], int((right - self.offset[0]) // self.tile) + margin + 1)
        row0 = max(0, int((top - self.offset[1]) // self.tile) - margin)
        row1 = min(self.grid.shape[0], int((bottom - self.offset[1]) // self.tile) + margin + 1)
        if col1 <= col0 or row1 <= row0:
            return np.zeros((0, FLOATS_PER_INSTANCE), dtype=np.float32)
        window = self.grid[row0:row1, col0:col1]
        rows, columns = np.nonzero(window >= 0)
        if rows.size == 0:
            return np.zeros((0, FLOATS_PER_INSTANCE), dtype=np.float32)
        ids = window[rows, columns]
        uvs = self.uv_table[ids]
        count = rows.size
        instances = np.zeros((count, FLOATS_PER_INSTANCE), dtype=np.float32)
        instances[:, 0] = self.offset[0] + (columns + col0 + 0.5) * self.tile
        instances[:, 1] = self.offset[1] + (rows + row0 + 0.5) * self.tile
        instances[:, 2] = self.tile
        instances[:, 3] = self.tile
        instances[:, 4:8] = 1.0
        instances[:, 8] = SPRITE
        instances[:, 12:16] = uvs
        return instances

    def draw_visible(self, scene, camera: Camera, aspect: float) -> int:
        """Queue the visible tiles.

        Parameters
        ----------
        scene : chisurf.gui.chigame.scene.Scene
            The frame under construction.
        camera : Camera
            The view.
        aspect : float
            Canvas width over height.

        Returns
        -------
        int
            Tiles queued.
        """
        instances = self.visible_instances(camera, aspect)
        if instances.size:
            scene.batch.add_array(instances)
        return instances.shape[0]
