from emtk import i18n

# ruff: noqa: E701, E702

_CATALOGS = {
    "de": {
        "Structure Tools": "Struktur-Werkzeuge",
        "Available tools": "Verfügbare Werkzeuge",
        "soon": "demnächst",
        "Tool unavailable": "Werkzeug nicht verfügbar",
        "Native version pending": "Native Version in Arbeit",
        "This tool is available in the Qt hub. Its native version is pending.": "Dieses Werkzeug ist im Qt-Hub verfügbar. Die native Version folgt.",
        "FPS JSON Editor": "FPS-JSON-Editor",
        "Docking & Screening": "Docking & Screening",
        "Kappa2 Distribution": "Kappa2-Verteilung",
        "QuEst": "QuEst",
        "HydroPro": "HydroPro",
        "Trajectory Tools": "Trajektorien-Werkzeuge",
        "Edit fps.json files for FRET accessible-volume modelling and fetch reference PDBs.": "Bearbeitet fps.json-Dateien für die FRET-Zugänglichkeitvolumen-Modellierung und lädt Referenz-PDBs.",
        "FRET-restrained rigid-body docking, refinement and structure-library screening (IMP + IMP.bff).": "FRET-restrigierte Starrkörper-Docking, Verfeinerung und Strukturbibliotheks-Screening (IMP + IMP.bff).",
        "Calculate and visualise the κ² orientation-factor distribution for FRET.": "Berechnet und visualisiert die κ²-Orientierungsfaktorverteilung für FRET.",
        "Quenching estimator — dye-diffusion simulation of fluorescence quenching and decays.": "Quenching-Schätzer — Farbstoffdiffusionssimulation von Fluoreszenzlöschung und Abklingen.",
        "Run HYDROPRO / HYDRO++ hydrodynamic calculations on structural files.": "Führt HYDROPRO-/HYDRO++-hydrodynamische Berechnungen auf Strukturdateien aus.",
        "Combined workspace for trajectory alignment, conversion, energy, FRET, joining, clash removal, rotation/translation and topology saving.": "Kombinierter Arbeitsbereich für Trajektorien-Ausrichtung, -Konvertierung, -Energie, FRET, -Zusammenführung, Kollisionsentfernung, Rotation/Translation und Topologie-Speicherung.",
    },
    "fr": {
        "Structure Tools": "Outils de structure",
        "Available tools": "Outils disponibles",
        "soon": "bientôt",
        "Tool unavailable": "Outil indisponible",
        "Native version pending": "Version native en préparation",
        "This tool is available in the Qt hub. Its native version is pending.": "Cet outil est disponible dans le hub Qt. Sa version native est en préparation.",
        "FPS JSON Editor": "Éditeur FPS JSON",
        "Docking & Screening": "Docking & criblage",
        "Kappa2 Distribution": "Distribution Kappa2",
        "QuEst": "QuEst",
        "HydroPro": "HydroPro",
        "Trajectory Tools": "Outils de trajectoire",
        "Edit fps.json files for FRET accessible-volume modelling and fetch reference PDBs.": "Édite les fichiers fps.json pour la modélisation en volume accessible FRET et récupère les PDB de référence.",
        "FRET-restrained rigid-body docking, refinement and structure-library screening (IMP + IMP.bff).": "Docking en corps rigide sous contrainte FRET, raffinement et criblage de bibliothèques structurales (IMP + IMP.bff).",
        "Calculate and visualise the κ² orientation-factor distribution for FRET.": "Calcule et visualise la distribution du facteur d'orientation κ² pour le FRET.",
        "Quenching estimator — dye-diffusion simulation of fluorescence quenching and decays.": "Estimateur de quenching — simulation de la diffusion des colorants pour l'extinction et les décroissances de fluorescence.",
        "Run HYDROPRO / HYDRO++ hydrodynamic calculations on structural files.": "Lance des calculs hydrodynamiques HYDROPRO / HYDRO++ sur des fichiers de structures.",
        "Combined workspace for trajectory alignment, conversion, energy, FRET, joining, clash removal, rotation/translation and topology saving.": "Espace de travail combiné pour l'alignement, la conversion, l'énergie, le FRET, la fusion, la suppression des chocs, la rotation/translation et l'enregistrement de topologies de trajectoires.",
    },
    "es": {
        "Structure Tools": "Herramientas de estructura",
        "Available tools": "Herramientas disponibles",
        "soon": "pronto",
        "Tool unavailable": "Herramienta no disponible",
        "Native version pending": "Versión nativa pendiente",
        "This tool is available in the Qt hub. Its native version is pending.": "Esta herramienta está disponible en el hub Qt. Su versión nativa está pendiente.",
        "FPS JSON Editor": "Editor FPS JSON",
        "Docking & Screening": "Docking y cribado",
        "Kappa2 Distribution": "Distribución Kappa2",
        "QuEst": "QuEst",
        "HydroPro": "HydroPro",
        "Trajectory Tools": "Herramientas de trayectorias",
        "Edit fps.json files for FRET accessible-volume modelling and fetch reference PDBs.": "Edita archivos fps.json para el modelado de volumen accesible FRET y obtiene PDB de referencia.",
        "FRET-restrained rigid-body docking, refinement and structure-library screening (IMP + IMP.bff).": "Docking de cuerpo rígido restringido por FRET, refinamiento y cribado de bibliotecas de estructuras (IMP + IMP.bff).",
        "Calculate and visualise the κ² orientation-factor distribution for FRET.": "Calcula y visualiza la distribución del factor de orientación κ² para FRET.",
        "Quenching estimator — dye-diffusion simulation of fluorescence quenching and decays.": "Estimador de apagado — simulación de difusión de tintas para el apagado y las decays de fluorescencia.",
        "Run HYDROPRO / HYDRO++ hydrodynamic calculations on structural files.": "Ejecuta cálculos hidrodinámicos HYDROPRO / HYDRO++ sobre archivos de estructura.",
        "Combined workspace for trajectory alignment, conversion, energy, FRET, joining, clash removal, rotation/translation and topology saving.": "Espacio de trabajo combinado para alineación, conversión, energía, FRET, unión, eliminación de choques, rotación/traslación y guardado de topologías de trayectorias.",
    },
    "pt": {
        "Structure Tools": "Ferramentas de estrutura",
        "Available tools": "Ferramentas disponíveis",
        "soon": "em breve",
        "Tool unavailable": "Ferramenta indisponível",
        "Native version pending": "Versão nativa pendente",
        "This tool is available in the Qt hub. Its native version is pending.": "Esta ferramenta está disponível no hub Qt. A sua versão nativa está pendente.",
        "FPS JSON Editor": "Editor FPS JSON",
        "Docking & Screening": "Docking e crivagem",
        "Kappa2 Distribution": "Distribuição Kappa2",
        "QuEst": "QuEst",
        "HydroPro": "HydroPro",
        "Trajectory Tools": "Ferramentas de trajetórias",
        "Edit fps.json files for FRET accessible-volume modelling and fetch reference PDBs.": "Edita ficheiros fps.json para a modelação de volume acessível FRET e obtém PDB de referência.",
        "FRET-restrained rigid-body docking, refinement and structure-library screening (IMP + IMP.bff).": "Docking de corpo rígido restringido por FRET, refinamento e crivagem de bibliotecas de estruturas (IMP + IMP.bff).",
        "Calculate and visualise the κ² orientation-factor distribution for FRET.": "Calcula e visualiza a distribuição do fator de orientação κ² para FRET.",
        "Quenching estimator — dye-diffusion simulation of fluorescence quenching and decays.": "Estimador de extinção — simulação da difusão de corantes para a extinção e os decaimentos de fluorescência.",
        "Run HYDROPRO / HYDRO++ hydrodynamic calculations on structural files.": "Executa cálculos hidrodinâmicos HYDROPRO / HYDRO++ sobre ficheiros de estrutura.",
        "Combined workspace for trajectory alignment, conversion, energy, FRET, joining, clash removal, rotation/translation and topology saving.": "Espaço de trabalho combinado para alinhamento, conversão, energia, FRET, junção, remoção de colisões, rotação/translação e gravação de topologias de trajetórias.",
    },
    "ru": {
        "Structure Tools": "Инструменты структуры",
        "Available tools": "Доступные инструменты",
        "soon": "скоро",
        "Tool unavailable": "Инструмент недоступен",
        "Native version pending": "Нативная версия в работе",
        "This tool is available in the Qt hub. Its native version is pending.": "Этот инструмент доступен в Qt-хабе. Нативная версия в работе.",
        "FPS JSON Editor": "Редактор FPS JSON",
        "Docking & Screening": "Докинг и скрининг",
        "Kappa2 Distribution": "Распределение Kappa2",
        "QuEst": "QuEst",
        "HydroPro": "HydroPro",
        "Trajectory Tools": "Инструменты траекторий",
        "Edit fps.json files for FRET accessible-volume modelling and fetch reference PDBs.": "Редактирует файлы fps.json для моделирования доступного объёма FRET и загружает эталонные PDB.",
        "FRET-restrained rigid-body docking, refinement and structure-library screening (IMP + IMP.bff).": "Жёсткотельный докинг с ограничениями FRET, уточнение и скрининг библиотек структур (IMP + IMP.bff).",
        "Calculate and visualise the κ² orientation-factor distribution for FRET.": "Вычисляет и визуализирует распределение фактора ориентации κ² для FRET.",
        "Quenching estimator — dye-diffusion simulation of fluorescence quenching and decays.": "Оценка тушения — моделирование диффузии красителей для тушения и затуханий флуоресценции.",
        "Run HYDROPRO / HYDRO++ hydrodynamic calculations on structural files.": "Запускает гидродинамические расчёты HYDROPRO / HYDRO++ для файлов структур.",
        "Combined workspace for trajectory alignment, conversion, energy, FRET, joining, clash removal, rotation/translation and topology saving.": "Объединённое рабочее пространство для выравнивания, конвертации, энергии, FRET, объединения, удаления столкновений, поворота/сдвига и сохранения топологий траекторий.",
    },
}


def install_translations():
    for locale, values in _CATALOGS.items():
        i18n.add_translations(locale, values, context="Structure Tools")


def tr(text):
    return i18n.tr(text, context="Structure Tools")
