import inspect
import os
import pathlib
from functools import lru_cache

from qtpy import QtWidgets, uic

import chisurf as cs
from chisurf import typing


@lru_cache(maxsize=512)
def _resolve_ui_path_cached(base_path: str, ui_filename: str) -> pathlib.Path:
    path = pathlib.Path(base_path) / ui_filename
    if not path.exists():
        raise FileNotFoundError(f"UI file not found: {path}")
    return path


def resolve_ui_path(ui_filename: str, path: os.PathLike | str) -> pathlib.Path:
    base = pathlib.Path(path)
    return _resolve_ui_path_cached(str(base), ui_filename)


#: Compiled ``Ui_*`` classes, keyed by (path, mtime). ``None`` marks a file that
#: could not be compiled, so the fallback is taken without retrying.
_UI_CLASS_CACHE: dict = {}


def _compiled_ui_class(ui_path: pathlib.Path):
    """Return a compiled ``Ui_*`` class for ``ui_path``, or ``None``.

    ``uic.loadUi`` re-parses the ``.ui`` XML on *every* widget construction,
    which measured 1.2-1.8 ms per file and 6.4 ms of a 21 ms ``LinePlot``.
    Compiling once and calling the generated ``setupUi`` is 3.2-4.7x faster and
    is what ``pyuic5`` produces ahead of time anyway.

    The key includes the file's mtime so editing a ``.ui`` during development is
    picked up rather than serving a stale layout. Anything that fails to compile
    or execute -- an unusual promoted widget, a missing resource module --
    returns ``None`` and the caller falls back to ``uic.loadUi``.
    """
    try:
        key = (str(ui_path), os.path.getmtime(ui_path))
    except OSError:
        return None
    if key in _UI_CLASS_CACHE:
        return _UI_CLASS_CACHE[key]

    ui_class = None
    try:
        import io

        buf = io.StringIO()
        uic.compileUi(str(ui_path), buf)
        namespace: dict = {}
        exec(buf.getvalue(), namespace)  # noqa: S102 - generated by uic from our own .ui
        ui_class = next(
            (v for k, v in namespace.items() if k.startswith("Ui_") and isinstance(v, type)), None
        )
    except Exception:
        cs.logging.debug("Could not compile UI %s; using uic.loadUi", ui_path)
        ui_class = None

    _UI_CLASS_CACHE[key] = ui_class
    return ui_class


class init_with_ui:
    """
    This is a decorator for __init__ methods of QtWidget objects.
    The decorator accepts an ui_filename, calls the super class of
    the object, and initializes the ui file to a target specified
    by the target option. If no target is provided the ui file
    is initialized into the object of the __init__ function.

    """

    def __init__(self, ui_filename: str, path: str = None):
        """

        :param ui_filename: The filename (without path) of the ui file.
        It is assumed that the ui file is in the same path as the file
        of the class that is being initialized.

        """
        self.ui_filename = ui_filename
        self.path = path

    def __call__(self, f: typing.Callable):

        def load_ui(target: QtWidgets.QWidget, ui_filename: str, path: str):
            ui_path = resolve_ui_path(ui_filename=ui_filename, path=path)
            ui_class = _compiled_ui_class(ui_path)
            if ui_class is None:
                uic.loadUi(ui_path, target)
            else:
                # pyuic5's setupUi() parents the widgets to `target` but binds
                # them as attributes of the *Ui_ instance* (`self.lineEdit`),
                # whereas loadUi(path, target) binds them on `target` itself.
                # Copy them across, or every `self.<widget>` in the widget's own
                # code raises AttributeError. Actions are covered too: they are
                # not QWidget children but are bound the same way.
                ui = ui_class()
                ui.setupUi(target)
                for name, value in vars(ui).items():
                    setattr(target, name, value)
            target._chisurf_ui_path = str(ui_path)

        def wrapped(cls: QtWidgets.QWidget, *args, **kwargs):
            if self.path is None:
                path = pathlib.Path(inspect.getfile(cls.__class__)).parent
            else:
                path = self.path

            # Call superclass __init__ method if it exists
            try:
                super(cls.__class__, cls).__init__(*args, **kwargs)
            except TypeError:
                super(cls.__class__, cls).__init__()

            # Only if the chain above did not reach QWidget. It used to run
            # unconditionally -- `super(QtWidgets.QWidget, cls).__init__()`,
            # which is QObject's initialiser on a widget that has already been
            # initialised. Initialising one C++ object twice is undefined, and
            # it crashed: a segfault inside this decorator, in whichever widget
            # happened to be built at the time. Asking the widget a question
            # only an initialised one can answer is how PyQt lets us tell.
            try:
                cls.objectName()
            except RuntimeError:
                QtWidgets.QWidget.__init__(cls)
            load_ui(cls, self.ui_filename, path)

            f(cls, *args, **kwargs)

        return wrapped


# reference taken from : http://stackoverflow.com/questions/11872141/drag-a-file-into-qtgui-qlineedit-to-set-url-text
# https://stackoverflow.com/questions/11872141/drag-a-file-into-qtgui-qlineedit-to-set-url-text
class lineEdit_dragFile_injector:
    def __init__(
        self,
        lineEdit,
        auto_inject=True,
        call=None,
        target: typing.List[pathlib.Path] = None,
        sorted: bool = True,
    ):
        self.lineEdit = lineEdit
        self.call = call
        self.sorted = sorted
        self.target = target if target is not None else []
        if auto_inject:
            self.inject_dragFile()

    def inject_dragFile(self):
        self.lineEdit.setDragEnabled(True)
        self.lineEdit.dragEnterEvent = self._dragEnterEvent
        self.lineEdit.dragMoveEvent = self._dragMoveEvent
        self.lineEdit.dropEvent = self._dropEvent

    def _dragEnterEvent(self, event):
        data = event.mimeData()
        urls = data.urls()
        if urls and urls[0].scheme() == "file":
            event.acceptProposedAction()

    def _dragMoveEvent(self, event):
        data = event.mimeData()
        urls = data.urls()
        if urls and urls[0].scheme() == "file":
            event.acceptProposedAction()

    def _dropEvent(self, event):
        data = event.mimeData()
        if isinstance(self.target, list):
            for url in data.urls():
                if url.scheme() == "file":
                    filepath = str(url.toLocalFile())
                    filepath = pathlib.Path(filepath).as_posix()
                    cs.logging.log(0, f"lineEdit_dragFile_injector::_dropEvent: {filepath}")
                    self.target.append(filepath)

            # Sort the target list of file paths
            if self.sorted:
                self.target.sort()

        if data.urls()[0].scheme() == "file":
            filepath = str(data.urls()[0].toLocalFile())
            filepath = pathlib.Path(filepath).as_posix()
            self.lineEdit.setText(filepath)

        if callable(self.call):
            self.call()
