"""``settings.tttr.json`` build/load + LUT correction application (no Qt).

This is the *consumer* side of the LUT pipeline: it takes computed LUTs, assigns
them to routing channels, applies them to TTTR data, and (de)serializes the
portable ``settings.tttr.json`` bundle. Correction application reuses the single
LUT-aware reading seam :func:`chisurf.core.fio.staging.open_tttr`, so the tool and
every reader linearize photons identically.
"""

from __future__ import annotations

import json

import numpy as np

SETTINGS_VERSION = "1.0"
SETTINGS_DESCRIPTION = "TTTR microtime correction settings"


def json_safe(obj: object) -> object:
    """Convert numpy values to JSON-serializable Python objects (recursively)."""
    if isinstance(obj, np.generic):
        return obj.item()
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    if isinstance(obj, dict):
        return {str(json_safe(k)): json_safe(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [json_safe(v) for v in obj]
    return obj


def build_settings_dict(
    channel_luts: dict[int, np.ndarray],
    channel_shifts: dict[int, int] | None = None,
    reading_routine: str | None = None,
    used_channels: list[int] | None = None,
    created: str | None = None,
) -> dict:
    """Assemble a portable ``settings.tttr.json`` dict.

    Parameters
    ----------
    channel_luts : dict
        ``{routing_channel: NTAC_fract}``.
    channel_shifts : dict, optional
        ``{routing_channel: int}`` photon-level shifts.
    reading_routine : str, optional
        tttrlib container/reading-routine.
    used_channels : list of int, optional
        Channels present in the loaded data (metadata only).
    created : str, optional
        Creation timestamp (metadata only); ``None`` omits it.

    Returns
    -------
    dict
        JSON-safe settings dictionary.
    """
    channel_shifts = channel_shifts or {}
    return {
        "description": SETTINGS_DESCRIPTION,
        "version": SETTINGS_VERSION,
        "reading_routine": reading_routine,
        "channel_luts": {
            int(ch): np.asarray(arr, dtype=float).tolist() for ch, arr in channel_luts.items()
        },
        "channel_shifts": {int(ch): int(s) for ch, s in channel_shifts.items()},
        "metadata": {
            "created": created,
            "used_channels": [int(c) for c in (used_channels or [])],
            "notes": "Generated by TTTR LUT Tools plugin",
        },
    }


def save_settings(path: str, settings: dict) -> str:
    """Write a settings dict to ``path`` as JSON; return the path."""
    with open(path, "w") as fh:
        json.dump(json_safe(settings), fh, indent=2)
    return path


def load_settings(path: str) -> dict:
    """Load a ``settings.tttr.json`` file, normalizing keys/arrays.

    Returns
    -------
    dict
        ``{"reading_routine", "channel_luts": {int: ndarray}, "channel_shifts":
        {int: int}, ...}``.
    """
    with open(path) as fh:
        raw = json.load(fh)
    luts = {
        int(k): np.asarray(v, dtype=float).ravel()
        for k, v in (raw.get("channel_luts") or {}).items()
    }
    shifts = {int(k): int(v) for k, v in (raw.get("channel_shifts") or {}).items()}
    return {
        "reading_routine": raw.get("reading_routine"),
        "channel_luts": luts,
        "channel_shifts": shifts,
        "metadata": raw.get("metadata", {}),
    }


def apply_luts_to_tttr(
    path: str,
    channel_luts: dict[int, np.ndarray],
    channel_shifts: dict[int, int] | None = None,
    routine: str | None = None,
):
    """Open a TTTR file with per-channel LUTs + shifts applied (LUT-aware read).

    Thin wrapper over :func:`chisurf.core.fio.staging.open_tttr` — the same seam
    every LUT-aware reader uses — so previews match production reads.

    Returns
    -------
    tttrlib.TTTR
        The linearized TTTR object.
    """
    from chisurf.core.fio.staging import open_tttr

    return open_tttr(
        path,
        routine,
        channel_luts=channel_luts,
        channel_shifts=channel_shifts or {},
        apply_lut=bool(channel_luts),
    )


def corrected_histogram(
    path: str,
    channel: int,
    channel_luts: dict[int, np.ndarray],
    channel_shifts: dict[int, int] | None = None,
    routine: str | None = None,
    coarsening: int = 1,
) -> tuple[np.ndarray, np.ndarray]:
    """Return the ``(counts, axis)`` micro-time histogram of one channel after LUT.

    Parameters
    ----------
    path : str
        TTTR file.
    channel : int
        Routing channel to histogram.
    channel_luts, channel_shifts : dict
        The correction to apply.
    routine : str, optional
        tttrlib reading routine.
    coarsening : int
        Micro-time histogram coarsening factor.
    """
    tttr = apply_luts_to_tttr(path, channel_luts, channel_shifts, routine)
    sel = tttr.get_tttr_by_channel([int(channel)])
    counts, axis = sel.get_microtime_histogram(coarsening)
    return np.asarray(counts, dtype=float), np.asarray(axis, dtype=float)
